### ISSUE TITLE
Text() returns weird characters.

### ISSUE THREAD

**Issue by umayr** [PuerkitoBio/goquery#103]
I'm using the very basic setting.
```go
    doc, err := goquery.NewDocument(url)
	if err != nil {
		panic(err)
	}
	doc.Find("title").Text()
``` 
Above snippet returns weird characters.
 
For example:
```
Scientists Stored These Images in DNA—Then Flawlessly Retrieved Them
```
returns 
```
Scientists Stored These Images in DNAâ€”Then Flawlessly Retrieved Them
```
Second example:
```
The 11 students, whose ages range from 7 to 14, have their identities protected in the suit, though the complaint included examples of the types of violence they claim to be the victims of.
```
returns
```
The 11 students, whose ages range fromÂ 7Â to 14,Â have their identitiesÂ protected in theÂ suit, though the complaint includedÂ examples of the types of violenceÂ they claim to be the victims of
```
Moreover, I checked both pages are using `utf-8` charset.

**Comment by PuerkitoBio** [comment]
Hi Umayr,

In absence of the actual URL I tested the provided string, the dash after DNA is indeed a multibyte unicode character (U+2014) that may have been encoded in another charset. The individual bytes for the dash in UTF-8 are `\xE2\x80\x94`. The corresponding characters in Latin-1 encoding are `â€”`, so the source wasn't UTF-8 but Latin-1.

Martin

**Comment by umayr** [comment]
I apologize for not providing the actual URLs.

URL: http://gizmodo.com/darpas-submarine-destroying-drone-ship-is-called-sea-hu-1769820431
Content:
```
Say hello to Sea Hunter. Thatâ€™s the new name for DARPAâ€™s autonomous warship, which is designed to seek-and-destory submarines without a crew aboard.The ship used to be called ACTUV before it got its new name on Thursday in Portland, Oregon. Weâ€™ll admit that Sea Hunter sounds much better than ACTUVâ€”which stands for Anti-Submarine Warfare Continuous Trail Unmanned Vesselâ€”but it does sound a bit like something out of a 1980s movie, doesnâ€™t it?Anyhow, the entirely new class of ship is considered to be a game changing feature in naval warfare: It is unmanned, has autonomous navigational capabilities and can be operated safely in all weather and traffic conditions, day or night. Impressive.The remotely piloted 130-foot twin-screw trimaran is now ready for open-water testing. Itâ€™ll have to prove itâ€™s able to traverse thousands of miles over the open seas for months at a time with nobody on board. And at some point, one assumes, itâ€™ll also have to prove that in can live up to its name. 
```
And here's the `meta` tag: `<meta charset="utf-8" />`. Its in the first line.

Another example from a different site:

URL: http://www.businessinsider.com/bentleys-holographic-butlers-in-cars-2016-4
Content: 
```
The 21st century Jeeves will be beamed directly into your personal transportation pod, serving up glasses of champagne, bouquets of roses and a freshly ironed copy of that morningâ€™s Times newspaper â€“ at least according to Bentleyâ€™s graphic designers., Bentley design director Stefan Sielaff said that the "yet-to-be-invented connectivity and technologies... are integrated into the cabin will become ever more important".In a world of autonomous driving it seems that our vehicles will be given a human face and personality to remove the awkwardness of barking instructions to your iPhone 12.Read the on . Copyright 2016. Follow The Drum on .
```
There are using the same meta tag. `<meta http-equiv="content-type" content="text/html;charset=utf-8" />`

**Comment by PuerkitoBio** [comment]
Thanks for the URLs, yes indeed the HTML document is UTF-8, it's probably your terminal that doesn't support it. I tested it and it prints just fine for me. The apostrophe used in the first example is U+2019, individual bytes `\xE2\x80\x99` in UTF-8. As you can probably guess, it translates to `â€™` in Latin-1.

**Comment by PuerkitoBio** [comment]
Actually, running `enca` on the first link returns 7bit ASCII, and on the second it returns "Unrecognized encoding", so there may be issues with the encoding of those pages after all.

**Comment by umayr** [comment]
That make sense. Thank you for your time.
