### ISSUE TITLE
Setting Timeout to selection.Find()

### ISSUE THREAD

**Issue by philipjkim** [PuerkitoBio/goquery#105]
I'm using goquery in [goreadability](https://github.com/philipjkim/goreadability), Go port of arc90's readability project.

I found bottleneck on `document.Find("*")` when a document is abnormally big (ex: http://activedomaining.com/).

I think it'll be quite useful if there's a function such as `selection.FindWithTimeout(selector string, timeout time.Duration)`, but it's not that simple what to return when time is up and the operation is still in progress. 

The return type of `FindWithTimeout()` can be `(*Selection, error)`. But then the method chaining is impossible. Or, we can return an imcomplete `*Selection`, aborted at the timeout. Of course it doesn't make sense.

It'll be great if we share some idea about handling timeout.

p.s. : To avoid bottlenecks, I set a maximum size of HTTP response (1Mb) and skip traversing if size is greater than the threshold.

**Comment by PuerkitoBio** [comment]
Hello,

A timeout would only help return control to the caller before the end of the Find call, but the Find would continue processing. For `Find`, most of the work occurs in the cascadia package (goquery could cancel a top-level loop in case of a stop signal, but that would not be helpful in many cases).

That kind of timeout (return control to caller and let Find continue processing in the background) is easy to do outside the package, e.g. something like (untested):

```
done := make(chan *goquery.Selection)
go func() {
  done <- doc.Find("x")
}()

select {
  case <- time.After(timeout):
    log.Print("timed out")
  case sel := <- done:
    // use sel...
}
```

I would question the use of `Find("*")` though?

Hope this helps,
Martin

**Comment by philipjkim** [comment]
@PuerkitoBio Thanks for the advice. I was actually using the same pattern you showed, and it works well in heavy-traffic (> 200 TPS) production environment. There're some of the patterns on my code:

- https://github.com/philipjkim/goreadability/blob/master/readability.go#L396
- https://github.com/philipjkim/goreadability/blob/master/readability.go#L438

Talking about `Find("*")`, I just copied the business logic of readability via the [ruby-readability](https://github.com/cantino/ruby-readability). I think the `*` selector is inefficient (or meaningless) in most cases.
