### ISSUE TITLE
What's "MISSING"?

### ISSUE THREAD

**Issue by peterbe** [PuerkitoBio/goquery#106]
I wanted to write a script that parses an HTML file, opens the `style` tags and investigates the content of those style tags. Wrote this:

```go
package main

import (
	"fmt"
	"log"
	"os"
	"github.com/PuerkitoBio/goquery"
)

func main() {
	var reader, err = os.Open("index2.html")
	doc, err := goquery.NewDocumentFromReader(reader)
	if err != nil {
		log.Fatal(err)
	}

	doc.Find("style").Each(func(i int, s *goquery.Selection) {
		css := s.Text()
		fmt.Printf(css)
	})
}
```

The `index2.html` file contains:

```
<style type="text/css">
html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}
</style>
```
And the output is bizarre:
```
html{font-family:sans-serif;-ms-text-size-adjust:100%!;(MISSING)-webkit-text-size-adjust:100%!}(MISSING)
```

I admit, I haven't done any go for over a year and I have to look up the docs for even the most basic things but what's this "MISSING" stuff?

Because of it, I can't use https://github.com/aymerick/douceur to parse the CSS text.

**Comment by PuerkitoBio** [comment]
Hey Peter,

You're using `fmt.Printf` to print the content, so it handles percent signs as a format verb, but without matching value to print, hence the MISSING tags. If you use `fmt.Print` it will work.

Have fun!
Martin

**Comment by peterbe** [comment]
Well, that's embarrassing.

**Comment by PuerkitoBio** [comment]
Don't worry about it, happens to all of us.
