### ISSUE TITLE
Should not escape &

### ISSUE THREAD

**Issue by gitchs** [PuerkitoBio/goquery#109]
# HOW TO REPRODUCE
```golang
package main

import (
        "bytes"
        "fmt"

        "github.com/puerkitobio/goquery"
)

var srcHTMLBytes = []byte(`<!DOCTYPE html><html><head>
</head>
<body>
<img src="http://image/url/with/query?k0=v0&k1=v1&k2=v2"/>
</body></html>`)

func main() {
        document, _ := goquery.NewDocumentFromReader(bytes.NewReader(srcHTMLBytes))
        dstHTML, _ := document.Html()
        fmt.Println(dstHTML)
}
```

OUTPUT
```html
<!DOCTYPE html><html><head>
</head>
<body>
<img src="http://image/url/with/query?k0=v0&amp;k1=v1&amp;k2=v2"/>
</body></html>
```

> But image element's source URL should be `"http://image/url/with/query?k0=v0&k1=v1&k2=v2"`

**Comment by gitchs** [comment]
# Version Info
> My goquery version is `2e29ea41f0d13f4a303c75553f4eeadddc7a4c56`

**Comment by gitchs** [comment]
Sorry, this bug should post to `golang.org/x/net/html`.

**Comment by PuerkitoBio** [comment]
Hello Leon,

I did reproduce it just using the `net/html` package (calling `ParseFragment` on the `img` node and then `Render` that node), however note that comment in the godoc of the `html.Render` function:

> Rendering is done on a 'best effort' basis: calling Parse on the output of Render will always result in something similar to the original tree, but it is not necessarily an exact clone unless the original tree was 'well-formed'. 'Well-formed' is not easily specified; the HTML5 specification is complicated.

The commet is more related to issues of correctly nested elements and does not directly address the issue of escaping, but it may fall under that caveat of "best effort". However if you do go ahead and file an issue on that package, could you post the link here? I think it would be interesting to follow that discussion.

Thanks,
Martin

**Comment by yonnic** [comment]
this bug is still there, I always get broken URLs.

**Comment by zhangxiansheng** [comment]
for another example, from the HTML source code of bing.com

`
<div style="display:none" "></div><div style="display:none" ">

`
pay attention to "&"

**Comment by zhangxiansheng** [comment]
for another example, from the HTML source code of bing.com

```
<div style="display:none" "><!--//<![CDATA[
  | 0;var ErrFuncs;(function(n){function i(n,i,r){t("Error",n,i,r)}function r(n,i,r){t("Warning",n,i,r)}function t(n,t,i,r){var u,f;if(r?(u=r,u.message+=" "+t):u=new Error(t),u.extra="manualError",i&&(u.extra+=" "+i),
...
//]]>--></div>
```

pay attention to "&"

**Comment by mna** [comment]
Please open a new issue with a clear explanation of the expected output, the actual output and why you think it is wrong, along with a short but complete program (code + html data) to reproduce the issue. This issue was closed in 2016.
