### ISSUE TITLE
Selection with AddNodes doesn't find children, but NewDocumentFromNode does.

### ISSUE THREAD

**Issue by RayfenWindspear** [PuerkitoBio/goquery#112]
Here is a playground link of a working program. Of course it doesn't run there, but I can't format it here because I use backticks for my string.

https://play.golang.org/p/8hKaJRcUNY

EDIT: Note that this sometimes works, but not in this given instance.

**Comment by PuerkitoBio** [comment]
Hello Rayfen,

Most methods on a selection return a new `*Selection`, but in your snippet you call `sel.AddNodes(nod)` but you throw away the newly created selection with the added node, and then call `sel.Children()` on the original, empty `sel` selection. I updated your code with a comment, this should work as you expect (though it is unusual to see a `*Selection` object created like this, usually you'd start from a selection obtained via one of the method calls on the document):

https://play.golang.org/p/BKCsaCMomO

Hope this helps,
Martin

**Comment by RayfenWindspear** [comment]
Holy crap! I didn't realize that AddNodes returned a new Selection. I feel silly now. Thanks for clearing up my shortsightedness...

**Comment by PuerkitoBio** [comment]
No worries, it's a quite large API that can be confusing. Have fun with your project!
