### ISSUE TITLE
ReplaceWithHtml sees html entity where there is none

### ISSUE THREAD

**Issue by frankMilde** [PuerkitoBio/goquery#113]
I try to replace a `href` with a string using `ReplaceWithHtml()`. The `href` contains queries, one of which is `&region=...`. Somehow, it is identified as the html entity for *registered trademark* `&reg;` although the `;` is missing:
```
    got :   <html><head></head><body>\href{http://www.nytimes.com/action=keypress®ion=FixedLeft}{Text}</body></html>
                                                                              ---^---
    want:   <html><head></head><body>\href{http://www.nytimes.com/action=keypress&region=FixedLeft}{Text}</head><body>
```
Minium working example:
```
    package main
    
    import (
            "fmt"
            "strings"
    
            "github.com/PuerkitoBio/goquery"
            "golang.org/x/net/html"
    )
    
    func main() {
    
            test := `<a href="http://www.nytimes.com/action=keypress&amp;region=FixedLeft">Text</a>`
    
            node, _ := html.Parse(strings.NewReader(test))
            doc := goquery.NewDocumentFromNode(node)
    
            convertLink(doc)
    
            got, _ := doc.Html()
            want := `<html><head></head><body>\href{http://www.nytimes.com/action=keypress&region=FixedLeft}{Text} After</head><body>`
    
            fmt.Println("got :   " + got)
            fmt.Println("want:   " + want)
    }
    
    func convertLink(doc *goquery.Document) {
            //html, _ := doc.Html()
            //fmt.Println("Before : " + html)
    
            doc.Find("a").Each(func(_ int, s *goquery.Selection) {
                    href, _ := s.Attr("href")
                    text := s.Text()
    
                    replace := "\\href{" + href + "}{" + text + "}"
    
                    //fmt.Println("Replace:                             " + replace)
    
                    s.ReplaceWithHtml(replace)
            })
    
            //html, _ = doc.Html()
            //fmt.Println("After  :    " + html)
            //fmt.Println("")
    }
```
When uncommenting the comments you can see, that the string `replace` is still correct. Only after calling `ReplaceWithHtml` the document `doc` converts it to the *trademark* sign.

With `jquery` there is no problem: https://jsfiddle.net/1tj3hkwm/

My guess is, that the problem might lie with golangs html package, but maybe I am doing something wrong, too.

**Comment by PuerkitoBio** [comment]
Hello,

Yeah it seems similar to #109 , though in that case I don't see how the `html` package could automatically detect it should not escape, since you are not rendering an html tag. But yeah, this is the behaviour of the html package and AFAICS, there is no option to tweak to make it stricter when parsing escaped entities (for the missing `;`).

Maybe it could work by manually building an `html.Node` and setting its `Data` field directly. I'll give it a shot a bit later.

Martin

**Comment by frankMilde** [comment]
Thanks for looking into this. Let me know when you find something.

**Comment by PuerkitoBio** [comment]
No, that doesn't work either, attribute values are always escaped: https://github.com/golang/net/blob/master/html/render.go#L166

Here's my little test: https://play.golang.org/p/LeqopgO0kr

**Comment by frankMilde** [comment]
Alrighty.. i just added some post processing in my code when dealing with hrefs to catch these.

**Comment by liudanking** [comment]
@frankMilde I meet the same issue. What is your final solution?

**Comment by frankMilde** [comment]
@liudanking Nothing fancy really. I just added some post processing and sanatized the href:

```
func sanatizedHref(s *string) {
	*s = strings.Replace(*s, "®", "&reg", -1)
}
```

**Comment by liudanking** [comment]
@frankMilde it seems that escaping attribute values is correct:
http://stackoverflow.com/questions/3705591/do-i-encode-ampersands-in-a-href
