### ISSUE TITLE
Find("") should return an empty selector

### ISSUE THREAD

**Issue by riking** [PuerkitoBio/goquery#114]
Expected: `doc.Find("")` should match no nodes
Actual: Operations return an error of `expected selector, found EOF instead`

Use-case: 

```
	s = doc.Find("")
	for _, sel := range someSelectors {
		s = s.Add(sel)
	}
	someOperation(s)
```

**Comment by PuerkitoBio** [comment]
Thanks, yes in fact any invalid selector string should return an empty selection, I'll fix this.
