### ISSUE TITLE
ReplaceWith() does not update parent selection

### ISSUE THREAD

**Issue by riking** [PuerkitoBio/goquery#116]
I *think* this might be more of a usability bug than anything, but I didn't find any documentation saying this wouldn't work:

```go
type Page struct {
	document *goquery.Document
	body *goquery.Selection
}

func (p *Page) fixHtmlProblems() {
	p.body.Find("p.heading").Each(func(_ int, s *goquery.Selection) {
		s.Nodes[0].Data = "h3"
	})
	p.body.Find("p:contains(\u00a0\u00a0\u00a0\u00a0\u00a0)").ReplaceWith("hr")
	// etc
}

func NewPage(...) *Page {
	p := new(Page)
	p.document := goquery.NewFrom...(...)
	p.body := p.document.Find("article").Clone() // !!! ← this /might/ be relevant?
	if p.body.Length() != 1 {
		panic("bad source html structure")
	}
	return p
}

func TestFixHtmlProblemsDoesSomething(t *testing.T) {
	p := NewPage(...)
	oldHtml, _ := goquery.OuterHtml(p.body)
	p.fixHtmlProblems()
	newHtml, _ := goquery.OuterHtml(p.body)

	if oldHtml == newHtml {
		t.Error()
	}
}
```

I fixed this by changing `p.body` to a method that applies the Find() to the document.

**Comment by PuerkitoBio** [comment]
`ReplaceWith` takes a selector string and replaces the nodes in the selection (the `p.contains...` in your case) with **nodes matching the `hr` selector** (https://godoc.org/github.com/PuerkitoBio/goquery#Selection.ReplaceWith). I suspect there's an issue with your `p.contains` selector, may not be supported by cascadia or may not match anything, and if your `hr` selector doesn't match anything in the body, then it would simply remove the `p.contains` nodes.

What I think you really want is `ReplaceWithHtml`, e.g.:

```
var srci116 = `<html>
<head>
	<title>T</title>
</head>
<body>
	<p>p1</p>
	<p>p2</p>
	<p>p3</p>
</body>
</html>`

func TestIssue116(t *testing.T) {
	doc, _ := NewDocumentFromReader(strings.NewReader(srci116))
	body := doc.Find("body")

	oldHtml, _ := OuterHtml(body)
	rem := body.Find("p").ReplaceWithHtml("<div>")
	newHtml, _ := OuterHtml(body)

	t.Log(oldHtml)
	shortPrintSel(t, rem)
	t.Log(newHtml)
}
```

(Note that it replaces the full `p` nodes, so the content of those nodes is lost).

**Comment by riking** [comment]
Oh, I thought that the library was going to synthesize a minimal HTML element that matched `hr`, namely `<hr>`.
