### ISSUE TITLE
code sample on readme doc doesn't iterate

### ISSUE THREAD

**Issue by austin1237** [PuerkitoBio/goquery#120]
I could be wrong since I'm generally new to this language and started playing around with this library the function
```go
func ExampleScrape() {
  doc, err := goquery.NewDocument("http://metalsucks.net") 
  if err != nil {
    log.Fatal(err)
  }

  doc.Find(".reviews-wrap article .review-rhs").Each(func(i int, s *goquery.Selection) {
    band := s.Find("h3").Text()
    title := s.Find("i").Text()
    fmt.Printf("Review %d: %s - %s\n", i, band, title)
  })
}
```
doesn't acutally iterate on the .Each(). Maybe metalsucks's design changed since this was written and those selctors are no longer valid?

**Comment by PuerkitoBio** [comment]
Thanks for the heads-up, indeed the structure of the website did change.
