### ISSUE TITLE
Should consider error on HTTP status != 200

### ISSUE THREAD

**Issue by bep** [PuerkitoBio/goquery#121]
NewDocument and friends does not return an error on 403 etc., and that doesn't feel right.

**Comment by PuerkitoBio** [comment]
Hello Bjørn Erik,

You're right, but `NewDocument(string)` is really just a helper that should be used only in the simplest of prototypes or code examples. Anything more serious would want to use a custom `*http.Client` with timeouts, and as you mention, check status codes before creating a goquery document.

As I commented in #111 , if I could turn back time I'd remove this helper function and leave just a `New` with an `io.Reader` and an `*html.Node`, but it's there and it will remain there, and it will keep the same behaviour. The right way is not to make goquery do the fetching for you anyway.

Thanks and have fun!
Martin
