### ISSUE TITLE
Panic: Runtime error getting the webpage

### ISSUE THREAD

**Issue by k0pernicus** [PuerkitoBio/goquery#122]
I'm trying to get a web page to parse it to get some informations about a `div id`.  
I've got some URLs in a structure, and I give as parameter an URL to a function, which get the document to parse it.

This is the code of my function:
```
func checkError(err *error) {
	if *err != nil {
		fmt.Sprintf("Error: %s", *err)
	}
}

func getInformationAbout(applicationUrl string, ch chan string) {
	applicationDocument, err := goquery.NewDocument(applicationUrl)
	checkError(&err)
	toReturn := "None"
	applicationDocument.Find("#appheader").Each(func(_ int, s *goquery.Selection) {
		links := s.Find("p")
		links.Each(func(_ int, s *goquery.Selection) {
			toReturn = fmt.Sprintf("Parsing %s: %s", applicationUrl, s.Text())
		})
	})
	ch <- toReturn
}

func main() {
...
        for n := 0; n < newApps; n++ {
	        if appToProcess, err := appToScrape.Pop(); err == nil {
		        go getInformationAbout(appToProcess, ch)
	        }
        }
        for n := 0; n < newApps; n++ {
	        fmt.Println(<-ch)
        }
}
```

When I execute my program, it returns to me this error:
``` 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x2299]

goroutine 1419 [running]:
panic(0x3912e0, 0xc82000a0e0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
main.getInformationAbout(0xc820326f00, 0x48, 0xc82006e1e0)
	/Users/.../scraper.go:78 +0x159
created by main.main
	/Users/.../scraper.go:156 +0x728
```

The line 78 corresponding to `applicationDocument.Find("#appheader").Each(func(_ int, s *goquery.Selection)`.

Is anybody here can help me to fix that error please?

**Comment by k0pernicus** [comment]
This is, for example, a URL that my code raise an error: https://f-droid.org/repository/browse/?fdid=org.dyndns.fules.ck&fdpage=12

As you can see displaying the source code, this web page contains a `div id` named `app header`...

**Comment by PuerkitoBio** [comment]
If your `goquery.NewDocument` fails, you call `checkError` but you still proceed with `applicationDocument.Find` (which would be nil in the case of an error). If you have an error, you should return.

**Comment by k0pernicus** [comment]
Thanks - my bad, sorry...

Error to fetch the web page is `read tcp 172.29.128.53:63732->107.150.51.2:443: read: connection reset by peerNone`.  
Is there a server problem or a problem from the library?

**Comment by PuerkitoBio** [comment]
`NewDocument(url)` is only a helper that executes an `http.Get` (i.e. with the default http client). For better over the timeouts, response, status codes (that is, for "production" use) you should make the request before calling goquery (and call it only if you're happy with the http response, using either `NewDocumentFromResponse` or `NewDocumentFromReader` if you want to handle the response's body yourself).

For that error you can try to run curl with your URL to see if that fails too, but the error fetching the page is unrelated to goquery.

**Comment by k0pernicus** [comment]
Ok - I will try it :-)

Thanks a lot!
