### ISSUE TITLE
Is There a Mechanism for Releasing Memory?

### ISSUE THREAD

**Issue by nitronick600** [PuerkitoBio/goquery#125]
Hi,
I've used Gokogiri for another project and they had the concept of "Free" in which you free the doc after you're done manipulating.  Is there a similar concept in goquery?

**Comment by PuerkitoBio** [comment]
Hello Nick,

No, Go is garbage-collected, the GC will take care of reclaiming the memory once the goquery document goes out of scope. Gokogiri is a C wrapper, which is why it needs to manually manage memory.

Have fun!
Martin
