### ISSUE TITLE
Still uses old golang.org/x/net/html

### ISSUE THREAD

**Issue by sim4life** [PuerkitoBio/goquery#127]
Goquery still uses the old golang.org/x/net/html instead of the latest standard "net/html". Can you kindly refactor the code?

**Comment by PuerkitoBio** [comment]
I don't understand what you mean. There is no net/html, golang.org/x/net/html is the "standard" package.

**Comment by sim4life** [comment]
IMHO, golang.org/x/net/html is not the standard package. It is an experimental package. Once such a package is mature enough for use, it gets moved to standard packages. So now you can just do 
```go
import "net/html"
```

Instead of

```go
import "golang.org/x/net/html"
```

**Comment by PuerkitoBio** [comment]
https://github.com/golang/go/wiki/SubRepositories (aka the `golang.org/x` repositories):

> These packages are part of the Go Project but outside the main Go tree.
> They are developed under looser compatibility requirements than the Go core.

You seem to think there *is* a `net/html` package in the stdlib. As of Go1.7, there isn't, the "official" one until (if it ever) it gets merged into the stdlib is the one `golang.org/x/net/html` one.
