### ISSUE TITLE
Can we print the current selection object

### ISSUE THREAD

**Issue by sim4life** [PuerkitoBio/goquery#128]
If I try to print selection object using %#v option, I get something like:
`&goquery.Selection{Nodes:[]*html.Node(nil), document:(*goquery.Document)(0xc4201a1ea0), prevSel:(*goquery.Selection)(0xc42022b680)}`

Can I print the selection object with meaningful html sub-document/tags etc.?

**Comment by PuerkitoBio** [comment]
OuterHtml will give you the html of the first element in the selection. If what you want is more a debugging tool to inspect a Selection, you can use github.com/davecgh/go-spew or github.com/kr/pretty.

**Comment by sim4life** [comment]
Thanks.
