### ISSUE TITLE
In .Each func how “return”

### ISSUE THREAD

**Issue by mejinke** [PuerkitoBio/goquery#13]
doc.Find("dl[class='brand_tree'] dd ul li").Each(func(index int, s *goquery.Selection) {
brandLiId, exists := s.Attr("id")
if exists == false {
return // End "Each" ?
} 

//......
})

**Comment by feltrite** [comment]
@mna I just came across the same need, except i need to return a string value and not a bolean value
`wantedtext := doc.Find("span").EachWithBreak(func(i int, s *goquery.Selection) string{
		attrValue, ok := s.Attr("itemprop")
		if !(ok == true && attrValue == "description") {
			return s.Html()
		}
	})`
itd be cool if .EachWithBreak could return other types of variables as well
