### ISSUE TITLE
Hosts file not read

### ISSUE THREAD

**Issue by Sean-Brown** [PuerkitoBio/goquery#131]
System: Windows 10
I have four dummy websites in different domains (hosta, hostb, hostc, hostd... taken from your [gocrawl project](https://github.com/PuerkitoBio/gocrawl/tree/master/testdata)). 
In %WINDIR%\system32\drivers\etc\hosts I added the following lines:
>127.0.0.1 hosta
>127.0.0.1 hostb
>127.0.0.1 hostc
>127.0.0.1 hostd

I created a simple server in Go that assigns each host a different IP address then serves the host files on that IP address, some sample output from the console:
>2016/09/22 12:33:33 Host hostd listening on port 43665
>2016/09/22 12:33:33 Host hostc listening on port 43664
>2016/09/22 12:33:33 Host hosta listening on port 44137
>2016/09/22 12:33:33 Host hostb listening on port 43662

I open a web browser to hosta:44137 and am able to see that the files are served correctly.

My issue is that when I try to create a GoQuery document, it either fails to create the document:
`doc, err := goquery.NewDocument("hosta:44137")`
>"2016/09/22 12:48:25 Unable to create a new document for hosta:44137"

or it attempts to go to the internet directly instead of noticing the host mapping:
`doc, err := goquery.NewDocument("http://hosta:44137")`
>"Network Access Message: The website cannot be found."
>"Explanation: The IP address for the website you requested could not be found."
>"Error Code 11001: Host not found"

Again, opening a web browser and navigating works as expected, but it does not work from Go.

**Comment by Sean-Brown** [comment]
What does work is:
`doc, err := goquery.NewDocument("http://127.0.0.1:44137")`
but then I don't get to test what I want, which is to test that my code only accesses websites under a specific domain.

**Comment by Sean-Brown** [comment]
I think the behavior I was experiencing was with the http Server that I setup... closing the issue until I can figure out something more definitive about the issue (and if it actually has anything to do with goquery)

**Comment by Sean-Brown** [comment]
Still experiencing the issue when trying to get text from the dummy webpage:
2016/09/22 16:05:02 hostb:49970
2016/09/22 16:05:02 http://hostb:49970
2016/09/22 16:05:02
          X
    Network Access Message: The website cannot be found

    Explanation: The IP address for the website you requested could not be found.
    Try the following:

        Refresh page: Search for the page again by clicking the Refresh button. The timeout may have occurred due to Internet congestion.
Check spelling: Check that you typed the Web page address correctly. The address may have been mistyped.
Access from a link: If there is a link to the page you are looking for, try accessing the page from that link.

If you are still not able to view the requested page, try contacting your administrator or Helpdesk.

    Technical Information (for support personnel)

        Error Code 11001: Host not found
Background: This error indicates that the gateway could not find the IP address of the website you are trying to access. This is usually due to a DNS-related error.
Date: 9/22/2016 8:05:01 PM [GMT]
Server: <<My Company's internal DNS server>>
Source: DNS error

**Comment by Sean-Brown** [comment]
I created a [sample project to demonstrate this issue](https://github.com/Sean-Brown/LocalhostServerTest)
All that's needed is to add:
`127.0.0.1 hosta`
to your hosts file

**Comment by PuerkitoBio** [comment]
Hello Sean,

I don't have a Windows box around, but it works fine on my macbook with a caddy server. Regardless of what's going on, though, it has nothing to do with goquery, if you look at `NewDocument`, it is just a helper function that calls the stdlib's `http.Get()` function and then creates the goquery document from the response. Goquery itself doesn't make network calls.

I'd suggest you try it out with a simpler setup - I looked at your sample project and there was a lot going on in there, I just started caddy on a given port (https://caddyserver.com/, could also be nginx or whatever) and added the `hosta` entry in my `/etc/hosts` file. You should then try a simple `http.Get("http://hosta:<port>")` and see what you get (and make sure to check any error).

Hope this helps,
Martin

**Comment by Sean-Brown** [comment]
That is helpful and http.Get() returns a 502 so it's got to do with my setup. Thanks for the response.
