### ISSUE TITLE
Debug - add method to dump the request

### ISSUE THREAD

**Issue by gelidus** [PuerkitoBio/goquery#136]
There are cases where we need to see the dump of the request. Go actually provides a way to dump http.Request, however, we must adapt goquery.Request to http.Request every time we want to dump it.

It would be awesome if goquery could provide a way to dump the request, e.g. `myreq.Dump()`

The implementation is pretty much clear:
```go
req, err := greq.MakeRequest()
if err != nil {
  return err
}

requestDump, err := httputil.DumpRequest(req, true)
if err != nil {
  return err
}
fmt.Println(string(requestDump))
```

**Comment by PuerkitoBio** [comment]
What's goquery.Request? Sounds like you may be posting to the wrong repo?

**Comment by gelidus** [comment]
Damn, yeah, bad repo
