### ISSUE TITLE
Can't Download

### ISSUE THREAD

**Issue by pchenghao** [PuerkitoBio/goquery#138]
Look this msg:
```
C:\WINDOWS\system32>go get github.com/PuerkitoBio/goquery
package golang.org/x/net/html: unrecognized import path "golang.org/x/net/html" (https fetch: Get https://golang.org/x/net/html?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
```
I visit `https://golang.org/x/net/html?go-get=1` in my browser,and get 
`Nothing to see here; move along.`
and then it redirect to `https://godoc.org/golang.org/x/net/html`
How to deal with this? please.

**Comment by pchenghao** [comment]
I download the package (`https://golang.org/x/net/html`) from `http://golangtc.com/download/package` ...
then run `go get github.com/PuerkitoBio/goquery` success.but i think this is a problem...

**Comment by PuerkitoBio** [comment]
That's unrelated to goquery, possibly a temporary network error or a firewall issue.
