### ISSUE TITLE
function Find returns more than expected

### ISSUE THREAD

**Issue by HouLinwei** [PuerkitoBio/goquery#140]
Thank you for your code.
 
When I use it, I find a  problem(may be my bad use)

my test documents are like this:

`
<channel>
<items><title>name1</title></items>
<items><title>name2</title></items>
</channel>
`
and I want to get items.title. What I write at first is:
`
// for loop
doc.Find("item").Eq(index).Find("title").Text()
`
I find the outputs are:
`
name1 name2
name2
`
I read your code https://github.com/PuerkitoBio/goquery/blob/master/traversal.go#L541
Later I change my code as belongs:
`
// for loop
doc.Find("item").Eq(index).Find("title").Eq(0).Text()
`
and it works.

My question is:
 It's designed like this? if yes, why?

**Comment by PuerkitoBio** [comment]
Hello,

This is confusing with the pseudo-code and the "it works" statement that doesn't say what actually changed. You say you want items.title, and that's what the first output prints as far as I can tell (though you could do it much more succinctly).

Can you please provide a clear description of the issue (given this html, if I run this code, I expect this output, instead I get that output) along with the intent (I want to achieve this) and the complete code to run it.

Thanks,
Martin

**Comment by HouLinwei** [comment]
Sorry for my bad statement and markdown format. 

My documents are like this:

```
<channel> 
    <items><title>name1</title></items> 
    <items><title>name2</title></items>
 </channel>
```

code (version 1)  is:

```
// the variable doc is an pointer that point to my documents     
items := doc.Find("channel items")    
for index := range items{
    node := items.Eq(index)    //  the node ponits to an "<items><title>nameN</titile></items>"
    fmt.Println(node.Find("title").Text()) 
    //  Notice: 
    //     when index is 0, the output is "name1 name2", 
    //     when index is 1 , the output is "name2" .
    // what I want is :  index = 0 , output: "name1" , index =1 , output : "name2"
    // and I can realize my purpose by change the code to fmt.Println(node.Find("title").Eq(0).Text()).
    // but I think the code(version 1) will work.
    // So I am doubt of the use of "Find" , does it  return all the matched node(for example <titlle>nameN</title>, in another word "Selection" ) including the current node and currentNonde.Next() ?
    //  thx~
}
```

**Comment by PuerkitoBio** [comment]
Thanks for the details, that works as expected for me: https://play.golang.org/p/V7PgHgb2YG

Note that you can't range on `items`, but that was probably a typo when you copied the code as the compiler would've warned you anyway.

**Comment by HouLinwei** [comment]
I know what you mean, and I think is should be like this.

After several retries, I find it is caused by my raw data, it looks like this:
```
<channel> 
    <items>
        <url/>   <!--this tag can not be handled correctly.-->
        <title>name1</title>
    </items> 
    <items><title>name2</title></items>
 </channel>
```
And I have to use 
```
singleNode.Find("title").Eq(0).Text()
``` 
instead of 
```
singleNode.Find("title").Text()
```

Can you have any suggestions on this problem?

**Comment by PuerkitoBio** [comment]
Again, please give:

1. The exact data that actually causes the issue
2. The exact code that reproduces the issue (full, runnable main.go)
3. What you would expect the exact output to be vs what you get

I'll try to help you out. I think it may be related to the use of what looks like rss data with an html parser. The go html parser treats some well-known html tags differently (it enforces some restrictions based on the html spec, and those may not make sense in a non-html document).

Martin

**Comment by HouLinwei** [comment]
I have comfirmed this problem, and the root reason is I use goquery as a RSS parser. 
Later, I will learn the differences between them(HTML parser and RSS parser).

I'm going to close this issue.

Thank you for you reply.   

: )
