### ISSUE TITLE
Is it support XPath?

### ISSUE THREAD

**Issue by alexandresgf** [PuerkitoBio/goquery#141]
Is it?

Thanks!

**Comment by PuerkitoBio** [comment]
Hello Alexandre,

No, it is based on an HTML(5) parser and supports CSS-style selectors (like its javascript inspiration, jQuery). You may want to check `xmlpath` (https://godoc.org/gopkg.in/xmlpath.v2) for a pure Go XPath engine, or `gokogiri` (https://godoc.org/github.com/moovweb/gokogiri/xpath) for a Go wrapper over the C libxml library.

Have fun!
Martin
