### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by Arnold1** [PuerkitoBio/goquery#143]
Hi, 
how can i use a SOCKS5 proxy with your library? e.g:

```
 // Create a socks5 dialer
  dialer, err := proxy.SOCKS5("tcp", "127.0.0.1:9050", nil, proxy.Direct)
  if err != nil {
    log.Fatal(err)
  }

  // Setup HTTP transport
  tr := &http.Transport{
    Dial: dialer.Dial,
  }
  client := &http.Client{Transport: tr}

  res, err := client.Get("http://google.com")
```

how can you send a post request to login to a website?

Thanks,
Arnold

**Comment by aaudis** [comment]
Arnold,

1) 

use `goquery.NewDocumentFromResponse` on your response from `client.Get`

2) 

sending Post requests is Go thing not goquerys and you use Go standard `net/http` library, use `http.Post` or `http.PostForm`  which ever suits best for your work and then parse response with goquery

**Comment by Arnold1** [comment]
@aaudis thanks for your reply. are there any examples available for 2.?

**Comment by aaudis** [comment]
>>> @aaudis thanks for your reply. also use NewDocumentFromResponse for 2?

yes

>>> could you tell me how goquery is different from https://github.com/PuerkitoBio/gocrawl ?

`gocrawl` is more like robot who walks through web page
`goquery` is more like if you targeting specific page and specific things

it depends on your use case, if you tell more about what you want to accomplish maybe I can give advice on what to use

**Comment by Arnold1** [comment]
ok, i saved the response to a file. is it possible to pass ```goquery.NewDocumentFromResponse``` the response string read from a file?

**Comment by PuerkitoBio** [comment]
Use `goquery.NewDocumentFromReader`, the open file is a `io.Reader` so it can be passed to this func directly.

**Comment by Arnold1** [comment]
hi, i want to read the following infos from this website:
https://gist.github.com/Arnold1/5de9823fc0382580fd3004bf18bdaba7

title="American Eagle Outfitters jacket"
<div class="price">$10 or data-post-actual-price="$10"

how would that work?

here is what i tried:
```
  doc.Find(".right-col .masonry .listing-con.shopping-tile.masonry-brick").Each(func(i int, s *goquery.Selection) {
    // For each item found, get the title and price
    title := s.Find("a").Text()
    //price := s.Find("i").Text()
    fmt.Printf("%d: %s\n", i, title)
  })
```

**Comment by PuerkitoBio** [comment]
Untested:

```
doc.Find(".listing-con.shopping-tile").Each(func(_ int, s *goquery.Selection) {
  price := s.AttrOr("data-post-actual-price", "$0")
  title := s.Find(".image-con").AttrOr("title", "<unknown>")
  fmt.Println(price, title)
})
```

**Comment by Arnold1** [comment]
thanks for the fast reply :)
ok, where can i find the syntax for .Find?

is goquery good for parsing websites like that?

**Comment by PuerkitoBio** [comment]
The full documentation for goquery is on godoc: https://godoc.org/github.com/PuerkitoBio/goquery

But what you want is probably the doc on the CSS selectors (i.e. what you can send in the string parameter to `Find`), and that is very much the same as jQuery, which is very much the same as the CSS selectors browser standard. The selector doc is not documented as part of the goquery package, but you can find some good reference here: https://developer.mozilla.org/en/docs/Web/Guide/CSS/Getting_started/Selectors

Goquery is exactly for that kind of job, manipulating an HTML document like that. Gocrawl is a web crawler/spider kind of tool.

**Comment by Arnold1** [comment]
is it as powerful as Scrapy (python lib)?

**Comment by PuerkitoBio** [comment]
Probably not? I don't know scrapy, the scope of goquery is roughly jquery in Go, minus some methods that don't make as much sense outside of a real live DOM (which jquery gets in a browser vs goquery with a static parsed tree).

**Comment by Arnold1** [comment]
how to handle dynamic generated pages?

**Comment by PuerkitoBio** [comment]
You will need other packages/tools to help you parse javascript-generated pages. Some pointers here: https://github.com/PuerkitoBio/goquery/wiki/Tips-and-tricks#handle-javascript-based-pages
