### ISSUE TITLE
read javascript

### ISSUE THREAD

**Issue by Arnold1** [PuerkitoBio/goquery#149]
hi,

how can i read 
xpid: "XQMGVFNACwYCXFVaBAg=" and 
token: "dg5HCVrXr1yzEUWnzBqpw8Fgxiz8GkuarbUZcX03l/M=" 
from this page?
https://gist.github.com/Arnold1/348694104769205652b3b11fa9b45e41

**Comment by PuerkitoBio** [comment]
For the xpid in the javascritp, you can get the content of the script tag, but after that goquery won't help you. You need to parse the javascript yourself.

For the token, something like (untested):

```
token := doc.Find("meta[name='token']").AttrOr("content", "")
```

**Comment by Arnold1** [comment]
can i still read the xpid with goquery? i just want to send it with a get request and set it in the header...

like that?
```
xpid := doc.Find("xpid")
```

**Comment by PuerkitoBio** [comment]
goquery manipulates HTML tags and attributes (via the net/html parser), it doesn't parse javascript. You can get the content of the script with the xpid value (via something like `doc.Find("script")` and iterate to find the right one), and then extract the xpid with some other means (an actual javascript parser, or a regex if you don't mind).
