### ISSUE TITLE
doc.Find() Doesn't Work When Inside Brackets

### ISSUE THREAD

**Issue by Acidic9** [PuerkitoBio/goquery#153]
I am trying to use `doc.Find(".mw-content-ltr .function_line .function_args")` for the following HTML:

```html
<div class="function_line">
	<span class="client" title="Client">&nbsp;</span>

	GM:CreateMove(
		<span class="function_args">
			<a href="/page/Category:CUserCmd" title="Category:CUserCmd">CUserCmd</a>
			cmd
		</span>
	)
</div>
```

The `".mw-content-ltr .function_line .function_args"` cannot find the `<span class="function_args">` because it is inside `GM:CreateMove( )` which is just plain text.

Is it just me doing something wrong or is this a bug?

I am trying it with the page at http://wiki.garrysmod.com/page/GM/CreateMove

**Comment by PuerkitoBio** [comment]
In that excerpt, there is no "mw-content-ltr" class, but 

```
doc.Find(".function_line .function_args")
```

works fine for me and returns the span.

**Comment by Acidic9** [comment]
Sorry, there was some previous html element with the class "mw-content-ltr", I wasn't getting any results. Must be a mistake on my end, sorry about that.
