### ISSUE TITLE
Find using regex

### ISSUE THREAD

**Issue by didn0t** [PuerkitoBio/goquery#159]
I am currently trying to rewrite some python code in go, for Python I used Beautiful Soup to extract the required HTML content/

I am trying to match this content:

```<span class="playerlevel slid4">D</span>```

However the number following slid varies, using BS it was possible to use a regex to match this:

soup.find(class_=re.compile(r"slid\d+")).text

However goquery Find requires a string.  Is there a way to match based on a regex?

Apologies if I'm missing something basic, I'm very new to Go.

**Comment by PuerkitoBio** [comment]
Hello,

The content got lost in the formatting, you should paste it inside a code block (triple backticks).

Martin

**Comment by PuerkitoBio** [comment]
There is no regular expression match, just standard css selectors, but you can use something like that (untested, not 100% sure off the top of my head if cascadia, the selector engine used by goquery, supports this but I think it does): http://stackoverflow.com/a/13352103/1094941
