### ISSUE TITLE
How to get attribut value?

### ISSUE THREAD

**Issue by banghasan** [PuerkitoBio/goquery#160]
hi, i`m newbie,

```
<img src="any.jpg" alt="image" title="something" />
```

how to get `any.jpg` and or get a title `something`  text ?

**Comment by PuerkitoBio** [comment]
Hello,

Look at `Attr("src")` and `AttrOr("src", "default")`. (https://godoc.org/github.com/PuerkitoBio/goquery#Selection.Attr).

Martin
