### ISSUE TITLE
How to check  the large file exists or not？

### ISSUE THREAD

**Issue by xpbliss** [PuerkitoBio/goquery#161]
```doc, err := goquery.NewDocument("/myweb/aa.mp4")```

because ```aa.mp4```  is a large file.  I only want to check it exists or not. no necessary to read all the content. 

How to check the large file exists  by using goquery?

**Comment by xpbliss** [comment]
````
      doc, err := goquery.NewDocument(uri)
	if err != nil {
		fmt.Println(uri,err)
	}
```
If the ```uri``` does not  exists,  the ``` err=nil`` ?

**Comment by PuerkitoBio** [comment]
Hello,

About the initial comment, goquery parses html files only (manipulates html nodes would be more accurate). You wouldn't be able to do much with an mp4.

About checking for existence of file/size of file, look at the stdlib os package (os.Stat). https://golang.org/pkg/os/#Stat

About the 2nd comment, `NewDocument` is really just a helper more relevant for tests or quick prototypes, as it passes the result of http.Get to NewDocumentFromReader (even if the http code is a 404, for example).

In more serious apps, you'd want to make the http call yourself, and call NewDocumentFromReader once you're sure the result is what you want to work with.

Hope this helps,
Martin
