### ISSUE TITLE
goquery.NewDocument脱离git环境即执行无结果

### ISSUE THREAD

**Issue by xjjrocker** [PuerkitoBio/goquery#163]
goquery只有在git环境下go run test.go可以正确执行，把编译好的exe放到cmd执行就goquery.NewDocument执行无结果！如何破！

**Comment by PuerkitoBio** [comment]
Hello,

Sorry, I don't understand chinese and google translate can't seem to make much sense of it. I'll leave it open in case someone who speaks chinese can give you a hand (or translate it for me so I can help).

Martin

**Comment by xjjrocker** [comment]
`doc1, err1 := goquery.NewDocument()`
I can get result just in git bash "go run test.go",but if i click test.exe or in windows cmd run test.exe, then err1 is nil , but doc1 also like '',nothing;why?

**Comment by PuerkitoBio** [comment]
Hard to tell, can you paste your complete code?
