### ISSUE TITLE
cannot convert s (type *goquery.Selection) to type string

### ISSUE THREAD

**Issue by AndreaM16** [PuerkitoBio/goquery#164]
Hi everybody, IO cannot find a way to convert HTML to string. I need to do that in order to work on a given id's innerHTML.

    doc, err := goquery.NewDocument("myPage.html")
	if err != nil {
		log.Fatal(err)
	}
	s := doc.Find("#myId")
	html, err := s.Html()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(html)/ Prints out the proper html

How can I cast type *goquery.Selection to string?

Thanks in advance.

**Comment by boolow5** [comment]
The only mistake I see in your code is how you opened your `.html` file.
Try this, I hope it will work:
`
file, err = os.Open("myPage.html")
// code to handle err
doc, err := gocode.NewDocumentFromReader(file)
// code to handle err

s := doc.Find("#myId")
html, err := s.Html() **// html does not need to be converted, it already is string**
`
