### ISSUE TITLE
Can not parse iframe node

### ISSUE THREAD

**Issue by IphoneCoder** [PuerkitoBio/goquery#165]
when i parse the address (http://www.163.com/),the id node l1 can not find ,but when i parse other node ,it success

doc, err := goquery.NewDocument("http://www.163.com/") 
  if err != nil {
    log.Fatal(err)
  }

  d,er := doc.Find("#l1").First().Html()
  if er != nil{
    log.Fatal(er)

  }
  fmt.Printf("%v\n", d)

**Comment by mna** [comment]
Hello,

I assume what you mean by "node l1 can not find" is that it does find it, but the html is empty?

Here's some code where `doc.html` is the content of that web page (`curl http://www.163.com > doc.html`). It finds one node for `#l1`, and although `Html()` returns an empty string, `OuterHtml()` correctly returns the `iframe` node.

```
func main() {
	f, err := os.Open("doc.html")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	doc, err := goquery.NewDocumentFromReader(f)
	if err != nil {
		log.Fatal(err)
	}
	s := doc.Find("#l1")
	fmt.Printf("lines: %d\n", s.Size()) //  prints 1
	h, err := goquery.OuterHtml(s)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(h) // prints <iframe id="l1" name="l1" ...></iframe>
}
```

That's how iframes work, the content is not part of the document that has an iframe, it is part of the document specified in the `src` attribute of the iframe.

HTH,
Martin
