### ISSUE TITLE
goquery Found that I want to get a tag of the HTML code

### ISSUE THREAD

**Issue by kaliwdsn** [PuerkitoBio/goquery#166]
Found that I want to get a tag of the HTML code and not  HTML Text

**Comment by mna** [comment]
Hello,

Not sure I understand the question, but maybe those links will help:

* `Selection.Html()` returns the (inner) HTML of the first element in the selection: https://godoc.org/github.com/PuerkitoBio/goquery#Selection.Html
* `Selection.Text()` returns the text content of all elements in the selection (i.e. HTML markup is stripped): https://godoc.org/github.com/PuerkitoBio/goquery#Selection.Text
* `OuterHtml()` (a package-level function) returns the *outer* HTML of the first element in the selection (i.e. the surrounding html tags of the element are returned too, unlike with `Selection.Html()`) : https://godoc.org/github.com/PuerkitoBio/goquery#OuterHtml
* `NodeName()` (a package-level function) returns the name of the HTML tag of the first element in the selection (i.e. `p` or `div`): https://godoc.org/github.com/PuerkitoBio/goquery#NodeName

I think you may want something like that, but not sure which.

Hope this helps,
Martin
