### ISSUE TITLE
Allow you to set a timeout on a NewDocument method call

### ISSUE THREAD

**Issue by evanmosseri** [PuerkitoBio/goquery#167]
I currently have to use a separate request library to have this functionality, I may implement this and create a pull request with your permission.

**Comment by mna** [comment]
Hello,

Thanks for your interest, but as I mentioned in other issues (e.g. https://github.com/PuerkitoBio/goquery/issues/161#issuecomment-285486665), the `NewDocument` function is really just an (unfortunate) helper that shouldn't be used for robust apps - what you'd want instead is to handle the request using the `net/http` package directly, with all the timeouts and bells and whistles at your disposition, and when you're happy with the response, call `NewDocumentWithReader`.

In fact, the documentation should mention this and I'd be glad to merge a doc PR that helps make that clear. But not a PR to add features around this helper function, this (and arguably the helper function itself) is out of scope for goquery.

Thanks,
Martin
