### ISSUE TITLE
Create feature that allows you to make all links in a document absolute

### ISSUE THREAD

**Issue by evanmosseri** [PuerkitoBio/goquery#168]
Similar to pyquery.PyQuery(url).make_links_absolute() in Python. I may implement this and create a pull request with your permission.

**Comment by mna** [comment]
Hello,

The HTML document may not have the necessary context to make a link absolute (e.g. it may not have the base URL). I see that in PyQuery, you have to pass the base URL to the function. There's not much value for goquery to add this, as the `net/url` stdlib package got you covered here, given an absolute base URL: https://golang.org/pkg/net/url/#URL.ResolveReference.

So again, that would be out of scope for goquery.

Thanks,
Martin
