### ISSUE TITLE
Can you help please.

### ISSUE THREAD

**Issue by jetbasrawi** [PuerkitoBio/goquery#169]
Hi I am stuck on this issue and have tried for two days now to solve it.

http://stackoverflow.com/questions/43023935/limit-the-scope-of-selector-find-to-the-selected-element

**Comment by mna** [comment]
You now have a comment from `Zoyd` that tells you what you have seems to work. That person is right, here's some code (where `data` is the exact HTML you pasted in the question):

```
func main() {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}

	doc.Find(".cont_block").Each(func(i int, s *goquery.Selection) {
		date := strings.TrimSpace(s.Find(".date").Text())
		fmt.Println(date)
		s.Find(".block_table td").Each(func(j int, c *goquery.Selection) {
			if text := strings.TrimSpace(c.Text()); text != "" {
				fmt.Println("inside ", date, ">>> ", text)
			}
		})
	})
}
```

The output is:

```
Saturday, Apr 16,2016
inside  Saturday, Apr 16,2016 >>>  Loerem ipsum dolor sit amet
Friday,Dec 18,2015
inside  Friday,Dec 18,2015 >>>  Loerem ipsum dolor sit amet
inside  Friday,Dec 18,2015 >>>  Loerem ipsum dolor sit amet
```

Seems like what you want.

HTH,
Martin

**Comment by jetbasrawi** [comment]
Hi, it turns out that the HTML files that I am processing have unclosed elements and this is leading to the issues that I am experiencing. Sorry.

**Comment by jetbasrawi** [comment]
Thanks for taking the time to look at this btw. Much appreciated.
