### ISSUE TITLE
How to load data by custom field name and custom class name?

### ISSUE THREAD

**Issue by iamatsundere** [PuerkitoBio/goquery#171]
Hi, I want to get data from 
`<ul data-script="pl_stats" data-widget="top-stats-header" data-header-id="homeTopPlayerStats" class="block-list-4 mobileScrollList"/>`
which has some custom fields like "data-header-id" or kind of and a class named "block-list-4 mobileScrollList" which is seperated by a space character, what can I do to get data from this? Thank you!

**Comment by mna** [comment]
Hello,

Goquery (via cascadia, the selector engine it uses) supports most css selector strings constructs, such as `.classname` and `#identifier` and `elementName` (the official spec may be too much to read if you just want a quick answer, see https://oscarotero.com/jquery/ for a cheat sheet - the "selectors" section in yellow).

In your example, the class name separated by a space character is actually **two** class names (that's how you set multiple class names, space-separated). You can use `doc.Find(".block-list-4")` to get all elements that have this class name, or `doc.Find(".block-list-4.mobileScrollList")` for elements that have both classes.

To get the value for an attribute such as `data-header-id`, once you have selected the element, you can call `val, ok := sel.Attr("data-header-id")` to get the value of the attribute. If you want to select elements based on that attribute, as shown in the cheat sheet, that would be `doc.Find("[data-header-id='homeTopPlayerStats']")`.

Hope this helps,
Martin

**Comment by iamatsundere** [comment]
Wow, your comment saved me! Thank you so much!
