### ISSUE TITLE
seems  goquery.NewDocumentFromResponse can not hand gzip response

### ISSUE THREAD

**Issue by suconghou** [PuerkitoBio/goquery#172]
I send some http headers to let it just like human visit the url 
so I use the `NewDocumentFromResponse` but found it can not hand the gzip response 
I found your source code which is just pass response to the `html.Parse`
without check the encoding 
`https://github.com/PuerkitoBio/goquery/blob/master/type.go#L69`
```
root, e := html.Parse(res.Body)
```
It is very unfriendly , would you please fix this bug , thank you very much !

**Comment by mna** [comment]
Hello,

`NewDocument` and `NewDocumentFromResponse` are just helpers that (in hindsight) shouldn't have been added to `goquery`. Indeed, `NewDocumentFromResponse` does very little but parse the response reader as html. If you need more control over the HTTP request/response before passing it to goquery, the correct way is to do the HTTP manipulation before, and when you're happy with the resulting response, call `NewDocumentFromReader`.

Note that if you don't explicitly set the gzip Accept-Encoding headers, the default Go http client (Transport) will automatically unzip the response.

Hope this helps,
Martin

**Comment by kerneltravel** [comment]
should manuly decode gzip content to text. e.g.
```
package main

import (
	"compress/gzip"
	"fmt"
	"io"
	"log"
	"net/http"
	"strings"

	"github.com/PuerkitoBio/goquery"
)

func main() {
	url := "https://www.google.com/"

	// Create a new HTTP client
	client := &http.Client{}

	// Create a new HTTP request
	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		log.Fatal(err)
	}

	// Set headers
	
	req.Header.Set("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36")

	// Make HTTP GET request
	response, err := client.Do(req)
	if err != nil {
		log.Fatal(err)
	}
	defer response.Body.Close()

	if response.StatusCode != 200 {
		log.Fatalf("status code error: %d %s", response.StatusCode, response.Status)
	}

	// Check if the response body is gzip compressed
	var reader io.Reader
	if response.Header.Get("Content-Encoding") == "gzip" {
		reader, err = gzip.NewReader(response.Body)
		if err != nil {
			log.Fatal(err)
		}
	} else {
		reader = response.Body
	}

	// Load the HTML document
	doc, err := goquery.NewDocumentFromReader(reader)
	if err != nil {
		log.Fatal(err)
	}

	
	fmt.Println("Text of element ", doc.Text())
}

```
