### ISSUE TITLE
Deprecate NewDocument and NewDocumentFromResponse

### ISSUE THREAD

**Issue by mna** [PuerkitoBio/goquery#173]
The documentation should mention that `NewDocument(url)` and `NewDocumentFromResponse(httpResponse)` are just helpers for quick prototyping/testing, but for "production" code, the HTTP handling should be done outside goquery, and call `NewDocumentFromReader(io.Reader)` when needed.

Many recent issues are raised because people expect a wide array of behaviour from those 2 functions which shouldn't have been added in the first place. Maybe they should be properly deprecated (as explained here: https://rakyll.org/deprecated/).

At the very least the docs should mention that "advanced" usage of those functions is not recommended. WIth better wording of course.

**Comment by kakera87** [comment]
I am sorry I don'n use goQuery. I just newb TT
