### ISSUE TITLE
How to simulate a brwose header?

### ISSUE THREAD

**Issue by qsbaq** [PuerkitoBio/goquery#174]
Hi:
I'm useing the goquery to get the html , but it returns 403 now . 
Maybe i must simulate a browse to get it .
Could u tell me how to simulate the header.

**Comment by mna** [comment]
Hello,

You probably call `NewDocument` with an URL? This is really just a helper method, what you should use is the Go `net/http` package to control the request as needed and then call `NewDocumentFromReader` with the response's reader when you're happy with what you received.

As for what you need to pass to avoid the 403, that depends on the website, typically you need some kind of authentication with an identity that grants you access to this page. But this is unrelated to the goquery package.

Hope this helps,
Martin
