### ISSUE TITLE
go get fail

### ISSUE THREAD

**Issue by ssr66994053** [PuerkitoBio/goquery#176]
go version : 1.8.1

error message:
package golang.org/x/net/html: unrecognized import path "golang.org/x/net/html" (https fetch: Get https://golang.org/x/net/html?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

**Comment by mna** [comment]
Working fine here, possibly a temporary glitch or an issue with your network settings (proxy, blocked by ISP, DNS etc.). This package hasn't moved AFAIK.
