### ISSUE TITLE
SetHtml and AppendHtml not working on second call

### ISSUE THREAD

**Issue by lansana** [PuerkitoBio/goquery#177]
Every time I try to update the `body` of a document after I edit the `head`, it fails. Why is this happening?

```go
doc, err := goquery.NewDocument(url)
if err != nil {
        // ...
}

headHtml, _ := doc.Find("head").Html()
bodyHtml, _ := doc.Find("body").Html()

doc.Find("head").SetHtml(headHtml + someString) // Works
doc.Find("body").SetHtml(bodyHtml + someString) // Doesn't work
```

Why does the second one fail? The HTML is never updated.

Even when I do it this way, it still fails:
```go
doc, err := goquery.NewDocument(url)
if err != nil {
        // ...
}

doc.Find("head").AppendHtml(someString) // Works
doc.Find("body").AppendHtml(someString) // Doesn't work
```

The `body` element definitely exists, so that isn't the issue. I don't understand what I'm doing wrong. Some help would be very appreciated.

**Comment by mna** [comment]
Hello Lansana,

Can you provide the full HTML document needed to reproduce? I'll give it a look.

Thanks,
Martin

**Comment by lansana** [comment]
Make an HTTP request using `goquery.NewDocument()` to "
https://www.webufacture.com".

**Comment by mna** [comment]
Can you elaborate what you mean when you say it doesn't work? How do you check if the result is correct? I tested with the following:

```
doc.Find("head").SetHtml("<span>head</span>")
doc.Find("body").SetHtml("<span>body</span>")

head, _ := doc.Find("head").Html()
body, _ := doc.Find("body").Html()

fmt.Println(head)
fmt.Println(body)
fmt.Println(goquery.OuterHtml(doc.Selection))
```

And it prints the following:

```
<span>head</span>

<span>body</span>

<!DOCTYPE html><html lang="en"><head><span>head</span></head>
<body id="page-top"><span>body</span></body></html> <nil>
```

(whitespace adjusted for readability, and the final <nil> is the error of the call to OuterHtml).

Martin

**Comment by lansana** [comment]
Oops, I forgot that I was calling a `removeScripts` function, and the text
I was adding was a script. 😅

**Comment by mna** [comment]
Also, note that the HTML is not correctly formed, so the html parser will automatically fix some issues (there are elements outside the head and before the body, e.g. the styles with `.ui-tooltip` class, and the `<div class="remove-tablet">`).

**Comment by mna** [comment]
Haha ok well that makes sense then :)

**Comment by lansana** [comment]
Such a facepalm, I was stuck on this for 2 days trying to read through the goquery code in hopes to find the bug to no avail, and finally gave in and opened the issue.

**Comment by mna** [comment]
No worries, we've all been there. Have fun with your project!

Martin
