### ISSUE TITLE
How to get the node itself html?

### ISSUE THREAD

**Issue by herozzm** [PuerkitoBio/goquery#179]
```html
<table id="test">
  <tr></tr>
</table>
```
```
doc.Find("#test").Html()
```
result: ``<tr></tr>``

I want the result:
```
<table id="test">
  <tr></tr>
</table>
```

**Comment by mna** [comment]
Hello,

That would be `OuterHtml`: https://godoc.org/github.com/PuerkitoBio/goquery#OuterHtml

This is not a method on the `Selection` because this is not a jQuery method (in JS-land this is automatically provided by the DOM).

Have fun!
Martin
