### ISSUE TITLE
multiple-value doc.Selection.Find

### ISSUE THREAD

**Issue by tingfeng-key** [PuerkitoBio/goquery#188]
doc, err := goquery.NewDocumentFromReader(res.Body)
log.Fatal(doc.Find(".sk_applist").Html())

tip: multiple-value doc.Selection.Find(".sk_applist").Html() in single-value context

**Comment by mna** [comment]
Hello,

Not sure what issue you're raising here, you'd like a multiple-value `doc.Selection.Find()`? Or a single-value `Selection.Html()`?

Martin

**Comment by tingfeng-key** [comment]
Thank you. I've found the problem and the solution

**Comment by mna** [comment]
Ok, cool. Have fun!
