### ISSUE TITLE
how to create New Document From String?

### ISSUE THREAD

**Issue by a57571735** [PuerkitoBio/goquery#189]
how to create New Document From String??????????????

**Comment by wngmnheiko** [comment]
Create a Reader from the string [https://golang.org/pkg/strings/#NewReader] and then create a new document from the Reader [http://godoc.org/github.com/PuerkitoBio/goquery#NewDocumentFromReader].

**Comment by a57571735** [comment]
`r := strings.NewReader(html)
	doc, err := goquery.NewDocumentFromReader(r)
	if err != nil {
		log.Fatal(err)
	}`

**Comment by a57571735** [comment]
@wngmnheiko thank you very much
