### ISSUE TITLE
Can't query img?

### ISSUE THREAD

**Issue by breerly** [PuerkitoBio/goquery#191]
My doc contains several `img` nodes, but goquery can't find them:

```
doc.Find(".container img").Each(func(i int, s *goquery.Selection) {
    fmt.Println("hello there")
})
```

Is this expected behavior?

**Comment by mna** [comment]
Hello,

Please provide the html data required to reproduce the issue.

Thanks,
Martin

**Comment by breerly** [comment]
```
<div class="container">
  <img src="..." >
</div>
```

**Comment by mna** [comment]
This html fragment works fine with the code you posted. This is why I ask for a complete, minimal example to reproduce the issue (code and data). Please make sure the program does reproduce the behaviour.
