### ISSUE TITLE
Get current URL via Find()?

### ISSUE THREAD

**Issue by tusing** [PuerkitoBio/goquery#192]
I was curious if it's possible to get the current page URL via `document.Find(...)`. (I am aware that `document.Url` also returns the URL.)

For example, in JS, we can use `window.location.href` to get the current page's URL. A project I'm working on would benefit if we could do something similar using the Find function.

**Comment by mna** [comment]
Hello Tushar,

No, unless the URL is stored somewhere in the HTML, there is no way to get it like that. Also, note that `document.Url` is only filled if `NewDocument(url string)` or `NewDocumentFromResponse(*http.Response)` are used (otherwise goquery has no idea where the html comes from).

Martin
