### ISSUE TITLE
stop after first result for `.Find`

### ISSUE THREAD

**Issue by reteps** [PuerkitoBio/goquery#193]
is it possible to stop after first result for `.Find`? I don't want to read through the rest of the html.

**Comment by mna** [comment]
Hello Peter,

If your selector is based on an html element, you can use the `:first-of-type` pseudo-selector, e.g.:

```
doc.Find("div:first-of-type")
```

Note that this only works for html elements, not for classes or attributes selectors. For those, you can use `doc.Find("...").First()` to reduce the set of matches to the first one. Yes, it will look for all matches first, but the html is already fully parsed and loaded into memory anyway, as it is the first step done when creating a `goquery.Document` (using the net/html parser), so this is quite fast.

Hope this helps,
Martin

**Comment by reteps** [comment]
perfect. thanks.
