### ISSUE TITLE
Travel down path to find tag [feature request]

### ISSUE THREAD

**Issue by reteps** [PuerkitoBio/goquery#194]
Goquery doesn't travel down a chain of `div` tags to search for a my `span` tag.  I would love if it could.

My code:        
```go
func main() {
        query := strings.Join(os.Args[1:], "+")
        response, err := http.Get("http://google.com/search?q=" + query)
        checkError(err)

        defer response.Body.Close()
        doc, err := goquery.NewDocumentFromReader(io.Reader(response.Body))
        checkError(err)

        doc.Find("span").Each(func(i int, s *goquery.Selection) {
                text := s.Text()
                if strings.Contains(text, "days ago") == false && strings.Contains(text, "day ago") == false && text != "" {
                        fmt.Println(text)
                }   
        })  
}
```

Something recursive might work, but I don't know how I would get it to work, as I am not that experienced with goroutines and channels. here is a mockup:
```
function recursivefind(data):
    divs = finddiv(data)
	if divs is not none:
	   for div in divs:
	       recursivefind(div)
    else:
	   stuff = data.find(MYTAG)
	   mychan <- stuff

function finddiv(data):
	return alldivs in data
```

**Comment by mna** [comment]
Hello Peter,

Not sure what you mean here, goquery does search the whole document for `span`s in that case. Please provide a minimal reproducible example with static html data, and explain what it does vs what you'd expect it to do.

Thanks,
Martin

**Comment by reteps** [comment]
using my code, it shows 
<img width="1280" alt="screen shot 2017-07-25 at 9 21 40 pm" src="https://user-images.githubusercontent.com/13869303/28600337-601d1548-717f-11e7-8850-c756a69eb9ca.png">

but looking into the google page
