### ISSUE TITLE
gbk编码问题

### ISSUE THREAD

**Issue by yangaowei** [PuerkitoBio/goquery#196]
页面编码是gbk，出现乱码问题

**Comment by mna** [comment]
Hello,

According to Google Translate, that would be:

> The page code is gbk, there are garbled problems.

Goquery requires the input HTML to be valid UTF-8 (a requirement inherited by the HTML parser). You can take a look at the wiki for ways to detect and transform other encodings to UTF-8: https://github.com/PuerkitoBio/goquery/wiki/Tips-and-tricks#handle-non-utf8-html-pages

Hope this helps, have fun!
Martin
