### ISSUE TITLE
panic error after running 4 hours

### ISSUE THREAD

**Issue by tommoholmes10** [PuerkitoBio/goquery#197]
haii I'm always getting error after running 4 hours and here I copy my log error
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4016cf]

goroutine 1 [running]:
panic(0x68fce0, 0xc42000a080)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
main.crawlerdetik(0xc420704c60, 0x5e, 0xc42060bc00, 0x6a, 0xc420073170, 0x83, 0xc420b14b00, 0x36, 0xc4205$
        /opt/go/src/gitlab.com/getboards/getboards-scrapper/handlers/news.go:134 +0x21f
main.main()
        /opt/go/src/gitlab.com/getboards/getboards-scrapper/handlers/news.go:78 +0x328
```
and here my code error
```
if(docs.Find("meta").Length() > 0){
			docs.Find("meta").Each(func(i int, s *goquery.Selection) {
				if (i > 0){
					if images, _ := s.Attr("name"); strings.EqualFold(images, "twitter:image:src") {
			           imagess, _ := s.Attr("content")
			           image = strings.TrimSpace(imagess)
			        }else if articletypes, _ := s.Attr("name"); strings.EqualFold(articletypes, "articletype") {
			           articletype, _ = s.Attr("content")
			        }	
				}
		    })
		}
```
please help me

**Comment by mna** [comment]
Hello,

Can you provide the (exact same) news.go file? What's at line 134 and 78? Did you log what input it was processing when it panics?

Martin

**Comment by tommoholmes** [comment]
thanks your respon
here my code looks like news.go
``` package main

 import (
"github.com/PuerkitoBio/goquery"
)

 var(
 	desc string
 )
 func main() {
 	for {
 		crawlernews("link")
	}
 }
 func crawlernews(link string){
 	docs, _ := goquery.NewDocument(link)
 	if(docs.Find("meta").Length() > 0){
 		docs.Find("meta").Each(func(i int, s *goquery.Selection) {
 			if (i > 0){
 				if images, _ := s.Attr("name"); strings.EqualFold(images, "twitter:image:src") {
 					imagess, _ := s.Attr("content")
 					image = strings.TrimSpace(imagess)
 					}else if articletypes, _ := s.Attr("name"); strings.EqualFold(articletypes, "articletype") {
 						articletype, _ = s.Attr("content")
 					}	
 				}
 				})
 	}
 }
```
`crawlernews` at line 78 and then ` if(docs.Find("meta").Length() > 0){ ` at line 134
hmmm I didn't log panic because already error at if docs

**Comment by tommoholmes10** [comment]
thanks your respon
here my code looks like news.go
``` package main

 import (
"github.com/PuerkitoBio/goquery"
)

 var(
 	desc string
 )
 func main() {
 	for {
 		crawlernews("link")
	}
 }
 func crawlernews(link string){
 	docs, _ := goquery.NewDocument(link)
 	if(docs.Find("meta").Length() > 0){
 		docs.Find("meta").Each(func(i int, s *goquery.Selection) {
 			if (i > 0){
 				if images, _ := s.Attr("name"); strings.EqualFold(images, "twitter:image:src") {
 					imagess, _ := s.Attr("content")
 					image = strings.TrimSpace(imagess)
 					}else if articletypes, _ := s.Attr("name"); strings.EqualFold(articletypes, "articletype") {
 						articletype, _ = s.Attr("content")
 					}	
 				}
 				})
 	}
 }
```
`crawlernews` at line 78 and then ` if(docs.Find("meta").Length() > 0){ ` at line 134
hmmm I didn't log panic because already error at if docs

**Comment by mna** [comment]
Ok, you ignore the error at `goquery.NewDocument`. Don't do that, handle that error and return. That's very likely why you get a nil reference error on the next line (docs is nil).

**Comment by tommoholmes10** [comment]
okeeee martin.

**Comment by tommoholmes10** [comment]
hai @mna I have been add log if nil
and I get log `net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`
I have been added with `goquery.NewDocumentFromReader(r)` and use your package `github.com/PuerkitoBio/rehttp` but still get error
please help me

**Comment by mna** [comment]
Not sure what you mean here, if the request fails there's nothing I can do for you. There are many reasons why a network request may fail, this is not a goquery bug so this is not the right place to discuss this. I suggest you try to `curl` the failing URL and see if that works, but regardless, your program should be able to handle failing requests, log it or save it to some failed requests table/queue/etc. and continue with other URLs.
