### ISSUE TITLE
Support HTML Event Handler

### ISSUE THREAD

**Issue by stnight** [PuerkitoBio/goquery#199]
I just noticed that goquery unable to do common DOM events, like Click, Hover etc. Do you any plans on the future to support this kind of feature?

**Comment by mna** [comment]
Hello,

That's because goquery doesn't run in a "live" DOM (e.g. a browser), it's just a static tree of nodes as parsed by the net/html parser (http://godoc.org/golang.org/x/net/html), there are no events that can be triggered.

Martin
