### ISSUE TITLE
get nil from NewDocumentFromReader

### ISSUE THREAD

**Issue by gssdromen** [PuerkitoBio/goquery#200]
Hello, I try to get Document from [http://www.xinyadianwan.com/bbs/exchangeps4/index.php?page_c=1&search_name=&gametype=&gamelang=&page=20](http://www.xinyadianwan.com/bbs/exchangeps4/index.php?page_c=1&search_name=&gametype=&gamelang=&page=20) with

```go
func getDocument(url string) *goquery.Document {
	res, err := http.Get(url)
	if err != nil {
		// handle error
		fmt.Println(err.Error())
	}
	defer res.Body.Close()

	// Convert the designated charset HTML to utf-8 encoded HTML.
	// `charset` being one of the charsets known by the iconv package.
	utfBody, err := iconv.NewReader(res.Body, "gbk", "utf-8")
	if err != nil {
		// handler error
		fmt.Println(err.Error())
	}

	// use utfBody using goquery
	doc, err := goquery.NewDocumentFromReader(utfBody)
	if err != nil {
		// handler error
		fmt.Println(err.Error())
	}
	// use doc...
	return doc
}
```

the error message is invalid argument

but get Document of page 19 [http://www.xinyadianwan.com/bbs/exchangeps4/index.php?page_c=1&search_name=&gametype=&gamelang=&page=19](http://www.xinyadianwan.com/bbs/exchangeps4/index.php?page_c=1&search_name=&gametype=&gamelang=&page=19) is valid

Thanks

**Comment by mna** [comment]
Hello,

Your code keeps going after an error. If something fails before getting the goquery document, it will return nil.

Martin

**Comment by shenshouer** [comment]
@gssdromen I met the same problem, How did you solve it ?

**Comment by shenshouer** [comment]
It was bug for `github.com/djimenez/iconv-go`

I convert string from GBK to UTF8 worked find when used `golang.org/x/text/encoding/simplifiedchinese` 

```
	// GBK 2 UTF-8
	reader := simplifiedchinese.GB18030.NewDecoder().Reader(res.Body)
	r := bufio.NewReader(reader)
	var buf bytes.Buffer

	if _, err := r.WriteTo(&buf); err != nil {
		log.Printf("[ERROR] load url %s data to buf error: %v", url, err)
		return nil, err
	}
```
