### ISSUE TITLE
bug for wrap function

### ISSUE THREAD

**Issue by penhauer-xiao** [PuerkitoBio/goquery#204]
```
content := `<p>aaaa</p><hr/>`
reader := strings.NewReader(content)
doc, err := goquery.NewDocumentFromReader(reader)
if err != nil {
	logrus.Errorln(err)
	return
}

doc.Find("html body").Each(func(_ int, s *goquery.Selection) {
		wrapTag(1, s)
})

func wrapTag(depth int, s *goquery.Selection) {
	for i, n := range s.Nodes {
		if n.Type != html.ElementNode {
			continue
		}
             
               if n.Data=="hr" {
                   s.Eq(i).Wrap("p")
              }
	     wrapTag(depth+1, s.Children())
	}
}
```
```
I expect the result is: <html><body><p>aaaa</p><p><hr/></p></body></html>,
but the result is:      <html><body><p>aaaa</p><p>aaaa<hr/></p></body></html>
```
I just want to wrap a hr tag with a p tag;  but it's unimaginable that it adds the contents of aaaa previous tag

**Comment by mna** [comment]
Hello,

Yes, that's what `Wrap(selectorString)` will do (https://godoc.org/github.com/PuerkitoBio/goquery#Selection.Wrap). That is:

- For each element in the set of matched elements (in your case, `<hr>`, that you match via `s.Eq(i)`)...
- Wrap it inside the first element matched by the selector passed to `Wrap()` (in your case, `<p>aaaa</p>`)...
- The matched child (`<p>aaaa</p>`) is cloned before being inserted in the document.

So `<hr/>` becomes `<p>aaaa<hr/></p>`, with the `p` node cloned and inserted to wrap the `hr`. I agree that this is a bit convoluted, but it is consistent with the jQuery API **when a selector is passed as argument**.

What you're looking for, I believe, is `WrapHtml`. This example is simpler than your code and I think achieves what you try to achieve (wrap *each* `<hr>` in a `<p>`):

```
var data = `
<html>
  <head>
  </head>
  <body>
    <p>aaaa</p>
    <hr/>
    <div>
    <hr>
    </div>
  </body>
</html>`

func main() {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}

	doc.Find("hr").WrapHtml("<p></p>")
	h, _ := goquery.OuterHtml(doc.Selection)
	fmt.Println(h)
}
```

`WrapHtml` will wrap each element in the set of matched elements (here, all `<hr>`) inside the inner-most child of the provided html (the `<p>`): https://godoc.org/github.com/PuerkitoBio/goquery#Selection.WrapHtml

Hope this helps,
Martin
