### ISSUE TITLE
Interact over dt

### ISSUE THREAD

**Issue by ZeusMode** [PuerkitoBio/goquery#205]
How can i interact over this list?

```
<dl class="row">
    <dt class="col-md-4">Foo</dt>
    <dd class="col-md-8">Bar</dd>
    <dt class="col-md-4">Bar</dt>
    <dd class="col-md-8">Foo</dd>
</dl>
```

```
doc.Find("dl dt").Each(func(i int, s *goquery.Selection) {
		name := s.Text()
})
```

how can i access each "dd" element, corresponding to dt

I already have tested things like

value := doc.Find("dl dd:nth-child(1)").Text()
value := doc.Find("dl dd:eq(1)").Text()

didn't work

i'm sorry if it's pretty obvious but i didn't get it.

**Comment by ZeusMode** [comment]
I already have tested things like 

value := doc.Find("dl dd:nth-child(1)").Text()
value := doc.Find("dl dd:eq(1)").Text()

didn't work

**Comment by mna** [comment]
Hello,

You're probably looking for `NextFiltered(filter)` or possibly `NextFilteredUntil(filter, until)`. The first will get the next sibling of the current selection (inside your `Each` closure, that would be the `dt`) if it matches the filter selector string, while `NextFilteredUntil` returns all next siblings that match the filter selector string, up until the until selector string.

To make things a little clearer, consider this code:

```
var data = `<dl class="row">
    <dt class="col-md-4">Foo</dt>
    <div>blah</div>
    <dd class="col-md-8">Bar</dd>
    <dt class="col-md-4">Quz</dt>
    <br>
    <dd class="col-md-8">Qax</dd>
</dl>`

func main() {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}
	doc.Find("dt").Each(func(i int, s *goquery.Selection) {
		nf := s.NextFiltered("dd")
		nfu := s.NextFilteredUntil("dd", "dt")
		fmt.Println(">>> ", s.Text(), nf.Text(), nf.Length())
		fmt.Println(">>> ", s.Text(), nfu.Text(), nfu.Length())
	})
}
```

This will print:

```
>>>  Foo  0
>>>  Foo Bar 1
>>>  Quz  0
>>>  Quz Qax 1
```

That is, `NextFiltered` will not return any `dd` if the next sibling is not a `dd`, while `NextFilteredUntil`, in this scenario, will return all the `dd`s between each `dt`s.

Hope this helps, have fun!
Martin

**Comment by ZeusMode** [comment]
works great!

Thanks
