### ISSUE TITLE
Text() include a js scripts...

### ISSUE THREAD

**Issue by monopollly** [PuerkitoBio/goquery#206]
I think that .Text() extract only text, not script...

but now the result looks like

Jim Clark is back
```
var _sf_startpt = (new Date()).getTime()
window.bN_cfg={h:window.location.hostname};
window.mediaconductor=window.mediaconductor||function()
{(mediaconductor.q=mediaconductor.q||[]).push(arguments);}
mediaconductor("init", "8e3e705039964bb9860e38cc7cf5ffd1");
mediaconductor("exec");
```

you just cut the <script> tag...
how to ignore all js script?

**Comment by mna** [comment]
Hello,

Yes that is the normal behaviour, `Text` returns the content of all text nodes, removing any element nodes (tags). If you don't want to have the content of script tags, you have to remove those before calling `Text`, e.g. (untested, but along those lines):

```
doc, err := goquery.NewDocumentFromReader(r)
if err != nil {
  // handle error
}
doc.Find("script").Remove()
doc.Find("whatever").Text()
```

Hope this helps,
Martin

**Comment by monopollly** [comment]
cool, thank you!
