### ISSUE TITLE
Documentation about struct fields

### ISSUE THREAD

**Issue by mauricioklein** [PuerkitoBio/goquery#207]
Hello!

Thanks for the effort put on this library.

It would be nice if the README contains a reference to the CSS selectors available.
As far I've seen, `goquery` relies on [cascadia](https://github.com/suntong/cascadia) to fetch the information from the HTML tree, but for some reason, some selectors that should be working are not.

Is there a good documentation about the available selectors we can use in the struct tags, avoiding to write the fetch of attributes manually via API?

Thanks in advance!

**Comment by mna** [comment]
Hello Mauricio,

I agree that a reference of available selectors would be nice, but I think the right place to document those should be in the cascadia project. Same thing if "some selectors that should be working are not", as you mention. If this is the case, an issue should be raised on the cascadia project. The goquery readme already points to cascadia as the underlying selector package.

I'm not sure I understand that last part about struct tags and fetch of attributes manually? I think you may be using the `Goq` package with struct tags?

Thanks,
Martin
