### ISSUE TITLE
Hope to provide API: `NewDocumentFromString`

### ISSUE THREAD

**Issue by Lizhooh** [PuerkitoBio/goquery#208]
Sometimes you don't want to use `url / io.reader / response`,
Rather, I want to parse `dom` by using a `string`
It's going to be easier

```go
html := `
    <div id='app'>
        <h2 class='title'>Hello world!</h2>
        <p class='time'> 2017-09-08 </p>
    </div>
`

dom, err := goquery.NewDocumentFromString(html);
dom.Find("#app > .title").Text()  // Hello world!
```

**Comment by mna** [comment]
Hello,

You can create a reader from a string with `goquery.NewDocumentFromReader(strings.NewReader(s))`.

Thanks,
Martin
