### ISSUE TITLE
NewDocumentFromString?

### ISSUE THREAD

**Issue by polds** [PuerkitoBio/goquery#21]
I saw this: https://github.com/PuerkitoBio/goquery/issues/20 for `NewDocumentFromReader` . I could also really use `NewDocumentFromString`... I have the unfortunate responsibility to "clean" some html and resave that is in an XML pseudo-RSS feed. So by time I get down to the parts I'd need to manipulate the html I'm within a loop of strings.

**Comment by drgrib** [comment]
@mna This is a very common use case, especially for testing. You may want to put a note and code example in the README.md and/or the preamble to the godoc.

**Comment by mna** [comment]
Good idea, I'll add something.
