### ISSUE TITLE
How to modify attribute of node

### ISSUE THREAD

**Issue by lansana** [PuerkitoBio/goquery#212]
@mna

I am looping through some nodes I got from a `*Selection`, and there is no method to `SetAttribute` on the respective nodes.

Is there any way to do this?

For instance:

```go
for _, node := range doc.Find("img").Nodes {
        // some stuff...

	node.SetAttribute("src", "foo.png") // I need to do something like this
}
```

And each node needs to have it's own custom attribute value, so it isn't a catch all thing.

**Comment by lansana** [comment]
Never mind, I think I solved it with the following (can't actually test it atm, but it reads correctly):

```go
document.Find("img").Each(func(index int, img *goquery.Selection) {
        // some stuff...

        img.SetAttr("src", "...")
})
```

**Comment by mna** [comment]
Looks about right. Note that `SetAttr` would set the attribute on each node in the selection, so you don't need to loop with `Each` (though I see you have other stuff going on in there, so maybe you have to).

Have fun!
Martin

**Comment by kumarsiva07** [comment]
```
document.Find("img").Each(func(index int, img *goquery.Selection) {
        // some stuff...

        img.SetAttr("src", "new")
})

```
`document.Html()` return with old src

**Comment by mna** [comment]
@kumarsiva07 please don't comment on closed issues, open a new one with a minimal, reproducible example (code + html data) for your specific scenario.

Thanks,
Martin
