### ISSUE TITLE
How to get text of a tag without text of children?

### ISSUE THREAD

**Issue by marcelloh** [PuerkitoBio/goquery#213]
Let's say I have this code:

```
	<ul class="slimdemo-menu">
		<li>
			<a href="/upload" class="mdl-navigation__link"><i class="material-icons" role="presentation">file_upload</i>Upload</a>
		</li>
		<li>
			<a href="/data" class="mdl-navigation__link"><i class="material-icons" role="presentation">check_circle</i>Data</a>
		</li>
		<li>
			<a href="/info" class="mdl-navigation__link"><i class="material-icons" role="presentation">info</i>Info</a>
		</li>
	</ul>
```
and I want to extract each text of an A-tag. but not with the text of the I-tag, how to do this?

I know there is s.Text() but in the first A-tag, it gives me:
file_uploadUpload
and I only want Upload

**Comment by marcelloh** [comment]
My workaround:
```
		remove := s.Children().Text()
		text := s.Text()
		result := strings.Replace(text, remove, "", -1)
```
but can it be 1 instruction?
Something like s.Text(true)
- gives me only the text of the current tag
while s.Text(false) or s.Text()
gives me the original value (all of this text inside the tag)

**Comment by mna** [comment]
Hello,

You can do this with this code:

```
s := doc.Find("a")
s.Contents().Not("i").Each(func(i int, s *goquery.Selection) {
	fmt.Println(s.Text())
})
// Prints Upload, Data, Info
```

`Contents` will give you the children of each node in the selection, including text nodes (https://godoc.org/github.com/PuerkitoBio/goquery#Selection.Contents), and `Not` removes the `<i>` elements from the selection, leaving only the text nodes.

Have fun!
Martin

**Comment by marcelloh** [comment]
Ehm, that solution is not a generic solution, so in my eyes a bad one.
It looks hardcoded for an I-tag, but what if the tags are a lot of different ones.
The html code was just an example. (so it looks like it is not closed yet)

**Comment by mna** [comment]
Sorry, wasn't clear from the question that this was not specific to the provided html. I close issues when it is obvious that the reply answers the question. This would be a generic solution:

```
s.Contents().Each(func(i int, s *goquery.Selection) {
	if goquery.NodeName(s) == "#text" {
		fmt.Println(s.Text())
	}
})
```

**Comment by marcelloh** [comment]
Now that is a solution that I was looking for :-)

**Comment by psyduckduck123** [comment]
Hi all, I have a similar issue, but with more nested elements.

What would you do if the internal elements also have `#text` node, but you only wanted  the text of the parent element?

e.g.  I want the `td_text` only, and not the `a_text1` and `a_text2`, that are also found because they are the `#text` node of the child elements?

Thanks!

```
<td>

<span >
<a href="index.php" >a_text1</a>
</span> 

<span>
<a href="index.php?">a_text2</a>
</span>

td_text

</td>
```

**Comment by mna** [comment]
If you try the proposed solution with a valid html document, it works too:

```
var data = `
<html>
  <body>
    <table>
      <tr><td>
        <span >
        <a href="index.php" >a_text1</a>
        </span>

        <span>
        <a href="index.php?">a_text2</a>
        </span>

        td_text
      </td></tr>
    </table>
  </body>
</html>
`

func main() {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}

	s := doc.Find("td")
	s.Contents().Each(func(i int, s *goquery.Selection) {
		if goquery.NodeName(s) == "#text" {
			fmt.Println(s.Text())
		}
	})
}
```

This only loops over the immediate children of `td`, and so the only `#text` node is the `td_text`.
Please open a new issue in the future, instead of commenting on closed ones.

Hope this helps,
Martin

**Comment by HenriqueSilverio** [comment]
I used this code to get only direct immediate text:

```go
row.Find(grossValueSelector).First().Clone().Children().Remove().End().Text()
```

And to trim white spaces:
```go
strings.TrimSpace(row.Find(grossValueSelector).First().Clone().Children().Remove().End().Text())
```

Adapted from [this](https://stackoverflow.com/a/8851526).

**Comment by apkrieg** [comment]
Easiest way to do:

```go
dom.Find("a").Each(func(i int, s *goquery.Selection) {
    fmt.Println("Only the text of the selection node:", s.Nodes[0].FirstChild.Data)
})
```

**Comment by danthegoodman1** [comment]
The cleanest way to do this is probably `selection.Contents().First().Text()`
