### ISSUE TITLE
How to get a tag "data-xxx" value

### ISSUE THREAD

**Issue by haijiandong** [PuerkitoBio/goquery#214]
I have a HTML `<sapn class="s1" data-timespan="123456789"></span>`.
I use the following ,don't get value
```Golang
timespan := s.Find("span.s1").AttrOr("data-timespan","123456")
```
What should I do?

**Comment by wngmnheiko** [comment]
Could it be that you just misspelled "span"?
This works for me:

package main

import (
	"fmt"
	"strings"

	"github.com/PuerkitoBio/goquery"
)

func main() {
	s := `<span class="s1" data-timespan="123456789"></span>`
	doc, _ := goquery.NewDocumentFromReader(strings.NewReader(s))
	timespan := doc.Find("span.s1").AttrOr("data-timespan", "123456")
	fmt.Println(timespan)
}

**Comment by haijiandong** [comment]
@wngmnheiko 
I'm sorry, my english is not very good, misspelled the word😵
I did the test again:
```golang
package main

import (
	"fmt"
	"github.com/PuerkitoBio/goquery"
	"strings"
)

func main() {
	s:=`<a href="javascript:void(0)" data-uigs="wap_3_1_14_fxsc"><span class="s3" data-except="1" data-lastModified="1507270735"></span></a>`
	doc,_:=goquery.NewDocumentFromReader(strings.NewReader(s))
	timespan:=doc.Find("span.s3").AttrOr("data-lastModified","123123123")
	class:=doc.Find("span.s3").AttrOr("class","123123123")
	fmt.Println(timespan,class)
}
```
Output:
![image](https://user-images.githubusercontent.com/12838659/31268875-cccda274-aab0-11e7-86a1-5595937db97c.png)

**Comment by wngmnheiko** [comment]
Attribute names are case insensitive. Try this:
timespan := doc.Find("span.s3").AttrOr("data-lastmodified", "123123123")

**Comment by haijiandong** [comment]
@wngmnheiko 👍 
Successful !
Thank you very much !

**Comment by zzaba** [comment]
I just had the same issue. I think this behavior should at least be documented, or the `Attr` method should be doing `ToLower` to input.

**Comment by mna** [comment]
Yeah that's an unfortunate and error-prone behaviour, but as for most things with the web, it cannot be as simple as doing `ToLower` on the key - I believe the html spec defines attributes as case-insensitive only for ascii letters, and there are special cases for math and svg attributes where they are not parsed as lowercase by Go's html parser. So for all those reasons, I prefer to be cautions and leave it to match the key as provided. I'd be happy to accept a documentation PR, though, that would clarify this behaviour.
