### ISSUE TITLE
find children convert to html may fail

### ISSUE THREAD

**Issue by zerozh** [PuerkitoBio/goquery#216]
`page.html` here:
```html
<!DOCTYPE html>
<html>
<head></head>
<body>
<div class="content">
  <p>Line 1</p>
  <pre>Pre Code</pre>
  <p>Line 2</p>
  <script>alert('ALERT');</script>
  <div class="ad">AD1</div>
  <div class="ad">AD2</div>
  <p>Line 3</p>
</div>
</body>
</html>

```
```go
package main

import (
	"log"
	"os"
	"github.com/PuerkitoBio/goquery"
)

func main() {
	file, _ := os.Open("./page.html")
	doc, _ := goquery.NewDocumentFromReader(file)

	// we need all children of .content except `div.ad`,`script`
	content, _ := doc.Find(".content *").Html()
	text := doc.Find(".content *").Text()
	// or content, _ := doc.Find(".content").First().Children().Html()
	// or text := doc.Find(".content").First().Children().Text()

	log.Printf("%s", content)
	log.Printf("%s", text)
}
```

Result:
```
2017/10/10 11:25:32 Line 1
2017/10/10 11:25:32 Line 1Pre CodeLine 2alert('ALERT');AD1AD2Line 3
```

Desire:
```
2017/10/10 11:25:32 <p>Line 1</p><pre>Pre Code</pre>...(omit)
2017/10/10 11:25:32 Line 1Pre CodeLine 2alert('ALERT');AD1AD2Line 3
```

Thanks!

**Comment by mna** [comment]
Hello,

The difference between `Html()` and `Text()` is that `Html` returns the html for the **first** element in the selection, while `Text` gets the combined text for all elements in the selection. With your selector `".content *"`, the first element in the selection for the call to `Html` is a *text* node that contains only whitespace.

If you use the selector `".content"`, you will get the desired results (that is, `Html()` returns the **inner** html).

Hope that helps,
Martin

**Comment by zerozh** [comment]
Hi mna,

Sorry I was not aware of the word first element and each element. I want to get all children of `.content ` except `.ad`,`script`, trim ads and additional scripts. However, I try `goquery.OuterHtml(doc.Find(".content").First().Children().Not("script,.ad"))`, but it does not work well, as you said, the first element in the selection.

It seems the behavior `.Html()` is differ from jQuery. Could you please show me the best practice for doing this?

Thank you.

**Comment by mna** [comment]
Hello,

I believe this is the same behaviour as jquery, e.g. from http://api.jquery.com/html/:

> In an HTML document, .html() can be used to get the contents of any element. If the selector expression matches more than one element, only the first match will have its HTML content returned

However, the html of may elements is basically the concatenation of the html of each element, so you could do something like that (warning, untested code and it's late :):

```
var buf bytes.Buffer
doc.Find(".content").Each(func (i int, s *goquery.Selection) {
  if s.Is("script") || s.HasClass("ad") {
    return
  }
  h, _ := s.Html()
  buf.WriteString(h)
})
fmt.Println(buf.String())
```

I think that should do the trick.

Martin

**Comment by mna** [comment]
Of course this was all kinds of wrong :) Here's a simpler (and correct) solution, using `Not` as you alluded to, and `OuterHtml` since we now process child elements:

```
	var buf bytes.Buffer
	doc.Find(".content").Children().Not("script,.ad").Each(func(i int, s *goquery.Selection) {
		h, _ := goquery.OuterHtml(s)
		buf.WriteString(h)
	})
	fmt.Println(buf.String())
```

**Comment by zerozh** [comment]
Hi mna,

I did it like your code and pass test. I think it is the best way.

Thank you very much 👍
