### ISSUE TITLE
The single quotation marks will be escaped as &#39;

### ISSUE THREAD

**Issue by penhauer-xiao** [PuerkitoBio/goquery#218]
For example the original text 'hello' it will be converted to &#39; from '
I think it's a big bug

**Comment by mna** [comment]
Hello,

Please provide a minimal but complete code example with data to reproduce the issue, along with the expected result.

Thanks,
Martin

**Comment by penhauer-xiao** [comment]
@mna  My code as following:
```
content := ` aaa'hello'bbb ccc"hello"ddd`
reader := strings.NewReader(content)
doc, err := goquery.NewDocumentFromReader(reader)
if err != nil {
    return
}
response, err2 := doc.Html()
if err2 != nil {
		return
}
fmt.Println(response)  
```

**Comment by mna** [comment]
Hello,

This behaviour is as expected, when you call `doc.Html()`, it returns HTML-escaped text. If you want the text and not the HTML, use `doc.Text()` (it will return the text unescaped).

Hope this helps,
Martin
