### ISSUE TITLE
i can  not find the exactly class

### ISSUE THREAD

**Issue by iOSwang** [PuerkitoBio/goquery#219]
in my find source code ,have two class the one is class="download" the other is class ="download downloadBox",i don`t want to math the class "download",i want to Each the class ="a class="download downloadBox"" ,the html is other website,i want to loop the site,what should i do?

**Comment by mna** [comment]
Hello,

If what you want is the elements with `downloadBox` (but not just `download`), then you can use this:

```
// assuming doc is a *goquery.Document created from your HTML data
doc.Find(".downloadBox").Each(func (i int, s *goquery.Selection) {
   // do something with each `s`, which is an element with the downloadBox class
})
```

Hope this helps,
Martin
