### ISSUE TITLE
Pretty print output of .Html()

### ISSUE THREAD

**Issue by geek1011** [PuerkitoBio/goquery#223]
Currently, there aren't any good pretty printers for html written in go. It would be nice if goquery could have the option of pretty printing the html.

**Comment by mna** [comment]
Hello Patrick,

I agree that an HTML pretty-printer would be nice (I don't know of any either), but I don't think this belongs in goquery. Something that would work directly with a `golang.org/x/net/html` node would be better, and it would be trivial to call it from a goquery Selection.

Martin

**Comment by geek1011** [comment]
I partly agree with your point, but the thing is that goquery seems to unpretty the code, and make it really unreadable.

Also, not much of an issue, but goquery mangles the <?xml ?> tag, and turns it into a comment (but I just fix this manually).

BTW, I am using this library in https://github.com/geek1011/kepubify

**Comment by geek1011** [comment]
Some unprettifying I have come across so far:
- Puts `<!DOCTYPE html><html><head>` in one line
- Puts `</body></html>` in one line
- Adds random newlines everywhere
- Puts contents of p tag in one line, even when it contains child elements
- pre tags causes indentation to be really unusual from there on
- Some other things I cannot remember off the top of my head

**Comment by mna** [comment]
What you're describing is the behaviour of Go's `net/html` parser used by goquery, not goquery itself:

```
var data = `
<!doctype html>
<html>
	<head>
	</head>
	<body>
		<p>
			Text
		</p>
	</body>
</html>
`

func main() {
	n, err := html.Parse(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}

	if err := html.Render(os.Stdout, n); err != nil {
		log.Fatal(err)
	}
}

// Output:
<!DOCTYPE html><html><head>
	</head>
	<body>
		<p>
			Text
		</p>


</body></html>
```

Note that it doesn't change the semantics of the document. I understand wanting a pretty-printer for humans (or to compare docs against some canonical format, but then an html minifier is probably better), but for code this shouldn't matter, this is an equivalent html document.

**Comment by mna** [comment]
Your tool seems pretty cool btw!

**Comment by geek1011** [comment]
@mna Thanks! For myself, I don't care too much about the prettiness about the code, but a bunch of users have been complaining (~30 so far).

I do care sometimes though, such as when I make one-off tools in go to do some transformations on my html.

**Comment by mna** [comment]
Closing this issue, since as I said it doesn't belong in goquery, but it would be nice to have one in Go for sure. I may hack on one in the next few weeks if I have some free time (no promises!) as this is a fun project for sure.

**Comment by geek1011** [comment]
@mna OK, I'll work on one too if I have time ;)

**Comment by a-h** [comment]
I came here looking for this too.

I noted that https://github.com/ericchiang/pup did almost what I wanted (it actually did far too much), but didn't support anything other than CLI usage, so I forked it, chopped it down and refactored a little to https://github.com/a-h/htmlformat

It uses `net/html` to parse (document fragments by default), and prints the results.
