### ISSUE TITLE
How do you copy a `*Selection` as a new `*Selection`?

### ISSUE THREAD

**Issue by YamiOdymel** [PuerkitoBio/goquery#224]
In Golang, you could dereference the pointers with the `*` symbol. But it's not possible to do that to a `*Selection` struct since the fields of the `Selection` struct are pointers.

```go
sel := doc.Find("h3").NextUntil("pre")

// The `copiedSel` is still pointing back to the `sel`,
// because the fields of `copiedSel` are pointers.
copiedSel := *sel
```

How do I copy a `*Selection` struct so I won't modify the original one? I don't see any `Copy` functions.

**Comment by mna** [comment]
Hello,

You're probably looking for `Clone`: https://godoc.org/github.com/PuerkitoBio/goquery#Selection.Clone

Martin

**Comment by YamiOdymel** [comment]
It seems like the `NextUntil` returns another `*Selection` instead of modifying the original one and returning it. 

My usage problem in #225 makes me thought the `NextUntil` changed the original `*Selection`, so the `Clone` or `Copy` function is no longer needed for me, thanks.
