### ISSUE TITLE
`AndSelf` has been replaced by `AddBack` since jQuery 1.8

### ISSUE THREAD

**Issue by YamiOdymel** [PuerkitoBio/goquery#226]
[`AndSelf`](https://api.jquery.com/andself/) has been removed since jQuery 1.8, and it's been replaced by [`AddBack`](https://api.jquery.com/addback/), though they does the same thing but [`AddBack`](https://api.jquery.com/addback/) accepts a selector.

**Comment by mna** [comment]
Thanks for the heads-up! I didn't see that, will leave open until I find time to add this (or someone sends in a PR for it with tests). Should be simple enough, basically `AndSelf` should call a new `*Selection.AddBack` method without argument, and there should be new `*Selection.AddBackFiltered` and `*Selection.AddBackMatcher` methods (that take a selector string and a `Matcher` interface as argument, respectively).
