### ISSUE TITLE
Getting immediate Text from the selected nodes

### ISSUE THREAD

**Issue by AMekss** [PuerkitoBio/goquery#228]
Hello, thank you for providing such a nice and useful lib  :)

I have an issue with getting text from the following HTML snippet:
```html
<div id="foo">
  <div id="bar">
    A quick brown fox
  </div>
  jumps over a lazy dog!
</div>
```
and following goquery
```go
doc, _ := goquery.NewDocumentFromReader(html)
doc.Find("#foo").Text()
```
it will return something like _"A quick brown fox jumps over a lazy dog!"_ which is expected and good as jQuery [would do the same](http://viralpatel.net/blogs/jquery-get-text-element-without-child-element/). While I do need to get only immediate text from the node _"jumps over a lazy dog!"_.

My question is what would be the best way to achieve this with `goquery` and/or what do you think of a PR adding a method like `func  (s *Selection) ImmediateText() string` which would do that?

**Comment by AMekss** [comment]
I solved my issue by using following private helper function:
```go
func immediateText(s *goquery.Selection) string {
	var buf bytes.Buffer

	for _, node := range s.Nodes {
		for child := node.FirstChild; child != nil; child = child.NextSibling {
			if child.Type == html.TextNode {
				buf.WriteString(child.Data)
			}
		}
	}

	return buf.String()
}
```
Let me know if you think that might be useful for others and I'll create a PR for it or just close this issue

**Comment by mna** [comment]
Hello Arturs,

You can do it without dropping down to raw html nodes with the solution explained in #213 . Let me know if that works for you. It's still not a straight method call, but a bit simpler.

Thanks,
Martin

**Comment by AMekss** [comment]
Hello Martin,

That works and is indeed better. Thank you very much!

The only downside I can see here is that I can't use it in conjunction with [Goq](https://github.com/andrewstuart/goq) un-marshaling, which was my initial path, but for now I switched off of it and using goquery directly, so this is not a problem at hand.

Thanks,
Arturs
