### ISSUE TITLE
something wrong with NewDocumentFromReader

### ISSUE THREAD

**Issue by snaigle** [PuerkitoBio/goquery#230]
I am coding for a crawler , like this 
```
   htmlContent = convertToGBK(...)
   doc,err :=goquery.NewDocumentFromReader(htmlContent)
```
but I  got the tag a[href] like this `/a/b/d/a.html` , it's not start with the host
so can you add the below method to improve it ?

```go
func NewDocumentFromReader(r io.Reader,url *url.URL) (*Document, error) {
	root, e := html.Parse(r)
	if e != nil {
		return nil, e
	}
	return newDocument(root, url), nil
}
```

best wishes!!

**Comment by mna** [comment]
Hello,

Given that the `Document.Url` field is exported, you can set it yourself after calling `NewDocumentFromReader`, i.e.:

```
htmlContent = convertToGBK(...)
doc, err := goquery.NewDocumentFromReader(htmlContent)
if err != nil { ... }
doc.Url = theURL
```

Hope that helps!
Martin

**Comment by snaigle** [comment]
It worked ,thanks very much!!!
