### ISSUE TITLE
.Slice should have end be an optional parameter

### ISSUE THREAD

**Issue by davidjwilkins** [PuerkitoBio/goquery#232]
In jQuery, the slice method only requires the first argument.

https://api.jquery.com/slice/
> The supplied start index identifies the position of one of the elements in the set; if end is omitted, all elements after this one will be included in the result.

The go code:

    func (s *Selection) Slice(start int, end ...int) *Selection

would work exactly as jQuery does - always use start, use end if it is provided as the second argument, and ignore any other arguments provided.

**Comment by mna** [comment]
Commented on the pr.

**Comment by mna** [comment]
As discussed in #233 , one interesting use-case that would be supported with a `SliceWithoutEnd` kind of method would be:

```
s.Find("tr").Slice(3).Find("td").Each(func(i int, s *goquery.Selection) { /* ... */ })
```

That is, slice without having to breakt out of the chained calls. Reopening the issue to think more about how we could support this.
