### ISSUE TITLE
how could i set a timeout for http request?

### ISSUE THREAD

**Issue by vanniuner** [PuerkitoBio/goquery#238]
how could i set a timeout for http request?

**Comment by cokeboL** [comment]
you can write in your app like this:
`func NewDocumentWithTimeout(url string, timeout time.Duration) (*Document, error) {
	// Load the URL
	var netTransport = &http.Transport{
		Dial: (&net.Dialer{
			Timeout: timeout,
		}).Dial,
		TLSHandshakeTimeout: 60 * time.Second,
	}
	client := &http.Client{
		Timeout:   timeout,
		Transport: netTransport,
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			return http.ErrUseLastResponse
		},
	}
	req, e := http.NewRequest(http.MethodGet, url, nil)
	if e != nil {
		return nil, e
	}

	res, e := client.Do(req)
	//res, e := http.Get(url)
	if e != nil {
		return nil, e
	}
	return goquery.NewDocumentFromResponse(res)
}`

**Comment by mna** [comment]
Hello,

cokeboL showed a way to do this in your code (you may not want to set the `CheckRedirect` field though, if you still want to use the default behaviour of following up to 10 redirections). As mentioned in #173 , having this code provided by goquery does not make sense, as this package should not be concerned with how you retrieve the html document, only about manipulating it. For this reason, setting a timeout on your request is something that belongs in your code, using the features provided by Go's standard library (such as the `net.Client` and `net.Transport`).

There are many different timeouts you may want to set, in the above example cokeboL uses the same value for the dial timeout and the whole-request timeout and a hard-coded one for TLS handshake, but differe use-cases may call for different values here.

Once you have executed your HTTP request and validated the response (e.g. checked the status code, maybe some header validations, etc.) then you should call `NewDocumentFromReader` and pass the response's body as reader.

Hope this helps,
Martin
