### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by qiusunshine** [PuerkitoBio/goquery#245]
run my project after several hours, i get the error, 
i think is the func which is "Find" and "Each" , beacuse at first time , i use Each(f func(int, *Selection)) ,i get the error : panic: runtime error: invalid memory address or nil pointer dereference, then i search the question from the internet, i think maybe the problem is ":=", so that  i  correct 
-->
```
func (s *Selection) Each(f func(int, *Selection)) *Selection {
	var i int
	var n *html.Node
	for i, n = range s.Nodes {
		f(i, newSingleSelection(n, s.document))
	}
	return s
}
```
but after some hours, occured a new problem 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x7ea0ef]
```
from 
```
doc,_ := goquery.NewDocument(movie.Url)
text:=doc.Find(".vodInfo").First().Find("span").First().Text()
```

can you help me?

**Comment by mna** [comment]
Hello,

The problem is that you ignore the error. If NewDocument fails, doc is nil
and the call to doc.Find panics.

Martin

**Comment by qiusunshine** [comment]
sorry, the error occured ad this line
```text:=doc.Find(".vodInfo").First().Find("span").First().Text()```
not NewDocument

**Comment by mna** [comment]
I understand, but it occurs there *because* the error is not checked
before.

**Comment by mna** [comment]
Ok I'm now on my laptop (was on my phone before), so what I mean is those two lines:

```
doc,_ := goquery.NewDocument(movie.Url) // here you ignore the error
text:=doc.Find(".vodInfo").First().Find("span").First().Text()
```

Should be replaced by:

```
doc, err := goquery.NewDocument(movie.Url)
if err != nil {
   log.Fatal(err) // or whatever, but do not continue using doc - it is nil!
}
text:=doc.Find(".vodInfo").First().Find("span").First().Text() // note that the second call to `First()` is not necessary
```

Also, if this is for anything more critical than an experiment or a personal project for fun, I strongly advise you make the requestl to the `movie.Url` using Go's `net/http` package, and then, once you've validated the results, use `goquery.NewDocumentFromReader(response.Body)` instead.

Hope this helps,
Martin

**Comment by qiusunshine** [comment]
i get it.
thanks a lot!
