### ISSUE TITLE
How to update the HTML of a document?

### ISSUE THREAD

**Issue by HoboKristian** [PuerkitoBio/goquery#249]
I have the following snipper of code which should update all the attributes in the document accordingly.

```
// Load the HTML document
doc, err := goquery.NewDocumentFromReader(resp.Body)
if err != nil {
	log.Fatal(err)
}
selections := doc.Find("*")
for _, node := range selections.Nodes {
	for _, attr := range node.Attr {
		attr.Val = prefix + attr.Val
	}
}
```

However, it is not reflected when I try to get the HTML document from the selection:

```
goquery.OuterHtml(selections)
doc.Text()
doc.Html()
```

**Comment by mna** [comment]
Hello Kristian,

That's because `node.Attr` returns a copy of the Attribute, so the change doesn't stick. You can use `goquery.SetAttr` to update an attribute's value, however there's no way to list the attributes with `goquery` so you still need to loop over the node's attributes. Something like that would work:

```
var data = `
<html>
	<head>
	</head>
	<body>
		<h1 class="x">
			Title
		</h1>
		<p a="b" c="d">
		</p>
	</body>
</html>
`

const prefix = "!!!"

func main() {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}
	doc.Find("*").Each(func(i int, s *goquery.Selection) {
		for _, attr := range s.Nodes[0].Attr {
			s.SetAttr(attr.Key, prefix+attr.Val)
		}
	})
	h, err := doc.Html()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(h)
}
```

Hope this helps!
Martin

**Comment by HoboKristian** [comment]
That works for iterating over the nodes. However I am hitting a performance wall.

What I am trying to change is have all src/href attributes point to my own domain.

So I am now doing
```
prefix := "localhost:8080/content/"
s.SetAttr(attr.Key, prefix+attr.Val)
```
which runs fine for the setAttr(), but when I do doc.Html() it halts forever (waited up to 1 minute).

**Comment by mna** [comment]
Are you sure you're only timing the call to `doc.Html()` and not anything else? That would be very surprising that one prefix causes that slowdown but not the other, it sounds as though something is making network calls (presumably to that localhost address) when you hit a slowdown?

Calling `doc.Html` is basically calling Go's `net/html` parser to render the nodes to an HTML string. I'd be very surprised if an attribute's value could slow down that rendering like this, and if that rendering somehow involved network calls (AFAICS this package does not use `net`).

**Comment by HoboKristian** [comment]
I was unable to recreate my bug in a minimal testing environment so it is probably due to some concurrency. Consider this closed :) Thanks for all the help!
