### ISSUE TITLE
How to retrieve text elements

### ISSUE THREAD

**Issue by Raggaer** [PuerkitoBio/goquery#250]
I have the current div with elements that are not inside any element

```html
<div class="box-inner">
            <h2>Basic Information</h2>
            <strong>Guild:</strong>
                        <em>Test</em>
                        <br><br>
            <strong>Forum Posts:</strong>
            7            <small class="italic">
                (0 posts per day)
            </small>
            <br>
                        <br>
            <strong>Joined:</strong>
            Jan 23, 2013            <br>
            <strong>Last Visited:</strong>
            Apr 2, 2018            <br>
</div>
```

So, retrieve **Guild** is easy, but retrieving the number of forum posts or joined/visited dates its not, how should I retrieve this values that are not wraped inside any element?

I know I can use `element.Text()` but since there are several elements I dont know what to do

**Comment by Raggaer** [comment]
Thanks for the reply, I tried removing the child elements and then working with `*html.Node` however I cant figure it out, I check the nodes and there is only one node (and its the div itself) and doesnt seem to have anything inside...

If you could post the node example, thanks

**Comment by mna** [comment]
Hello,

It would look something like that:

```
	// only one node in the selection, the "div"
	n := div.Get(0)
	for nn := n.FirstChild; nn != nil; nn = nn.NextSibling {
		if nn.Type == html.TextNode {
			s := strings.TrimSpace(nn.Data)
			if s != "" {
				fmt.Println(">>>> ", s)
			}
		}
	}
```

 Obviously, this isn't super robust code, as a slight change in the HTML could break it.

Have fun!
Martin

**Comment by Raggaer** [comment]
Thanks for the support =)
