### ISSUE TITLE
Find all descendant comment nodes

### ISSUE THREAD

**Issue by imjasonmiller** [PuerkitoBio/goquery#252]
Hi, 

I am new to Go and have been looking at the [API](https://godoc.org/github.com/PuerkitoBio/goquery) in order to figure out how to retrieve all descandant comment nodes, but I am stuck. The html I am working with looks like the following:

```html
<td>
    <!-- a  href="...?id=123">Name</a> -->
    Name
</td>
...
```

Where the _id_ and _name_ are strings I am interested in retrieving.

The above works in my current implementation, which looks like:

```go
node.Contents().Each(func(i int, node *goquery.Selection) {
    if goquery.NodeName(node) == "#comment" {
        ...
   }
})
```

The above only returns the children, not all descendants to my understanding. That means that it will fail when a `<span />` might be wrapped around it:

```html
<td>
    <span style="text-decoration:line-through">
        <!-- a  href="...?id=123">Name</a> -->
        Name
    </span>
</td>
...
```

Another approach would be to print the entire node using `.Html()`, but I preferably would narrow it down to only comments beforehand.

I am confident that there are much better approaches out there, looking at how extensive the package is, so how could this be done?

Thanks in advance!

**Comment by imjasonmiller** [comment]
Martin, many thanks for the detailed answer! It means a lot to me.

I was playing around with a callback, recursion based function from some other code I found and it ended up doing this:

```go
func traverseNodes(node *html.Node, fn func(*html.Node)) {
	if node == nil {
		return
	}

	fn(node)

	cur := node.FirstChild

	for cur != nil {
		next := cur.NextSibling
		traverseNodes(cur, fn)
		cur = next
	}
}

traverseNodes(sel.Nodes[0], func(node *html.Node) {
    if node.Type == html.CommentNode {
        comment := node.Data
        // do things
    }
})
```

It is similar to your solution in recursion being key. I am going to play around with it a bit and see what will work best for my use case.

Thanks a ton for the help and package!

**Comment by mna** [comment]
Hello Jason,

Yeah, that's good too, similar approach but using lower-level `*html.Node` instead (should be a bit more efficient). One thing that comes down to preference but I feel like is more readable is to write your loop in `traverseNodes` like this:

```
for cur := node.FirstChild; cur != nil; cur = cur.NextSibling {
    traverseNodes(cur, fn)
}
```

But either works of course. Have fun and thanks for the kind words!
Martin
