### ISSUE TITLE
Why is there no method that can find first element which match a selector?

### ISSUE THREAD

**Issue by excosy** [PuerkitoBio/goquery#255]
Sometimes we shall find an element by id. In general, there is only one element which match a specific id. Is find first is more effecient for no need to  scan whole document? I use doc.Find(id).First to find the element now, is it correctly?
And, it is necessary to add method which can select element by xpath?

**Comment by mna** [comment]
Hello, 

No, currently there is no method to stop after the first match is found. There's the `:first-child` or `:nth-child` pseudo-classes, but it only stops for children of the parent node, it keeps looking at the rest of the document. I agree that it  would make sense to have something like that, similar to jquery's `:first` pseudo-selector (https://api.jquery.com/first-selector/). I'm not sure how well it can fit in the API though. I'm open to design discussions on this subject on this ticket, if anyone cares enough about this feature to think this through and bounce ideas with me.

Not sure I understand your second point about xpath? Goquery uses CSS selector strings via the `cascadia` Go package that it uses as a dependency (i.e. what is typically used in `querySelectorAll` in javascript in the browser), it does not support xpath.

Thanks,
Martin

**Comment by uurtech** [comment]
I believe this could solve your problem
` item := doc.Find(".tabbody").First().Text()`

**Comment by gdollardollar** [comment]
Hello!

Sorry this is a bit old, but I faced a similar issue (finding multiple single elements in a page) and played with it a bit.

I ended up creating this struct:

```golang
// SingleMatcher matches a single node
type SingleMatcher struct {
	cascadia.Selector
}

// MatchAll implements the Matcher interface
func (s SingleMatcher) MatchAll(n *html.Node) []*html.Node {
	out := s.Selector.MatchFirst(n)
	if out == nil {
		return nil
	}
	return []*html.Node{out}
}
```

Here is my benchmark:
```golang
func BenchmarkSingleMatcher(b *testing.B) {
	doc := ...
	matcher := cascadia.MustCompile(`meta[itemprop="name"]`)
	single := SingleMatcher{Selector: matcher}

	b.ResetTimer()

	b.Run("regular", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			_ = doc.FindMatcher(matcher)
		}
	})
	b.Run("single", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			_ = doc.FindMatcher(single)
		}
	})
}
```

The results are promising:
```
BenchmarkSingleMatcher/regular-16         	   17252	           73655 ns/op	      72 B/op	       4 allocs/op
BenchmarkSingleMatcher/single-16          	 1000000	      1036 ns/op	      72 B/op	       4 allocs/op
```

I am sort of new to go so it might not be super gon-ic ?

**Comment by mna** [comment]
Hey, 

I think your on to something, that would allow introducing single-node matching without too much API changes, and your benchmarks shows that this is worth it.

I'll take a closer look at the current usage of `MatchAll` in the goquery codebase, but having something that creates a `goquery.Matcher` with a `MatchAll` method that actually does a `cascadia.MatchFirst` is a very interesting approach. Yes, it means that you have to use `Matcher`s to get the single-node behaviour (vs strings), but I think that'd be acceptable to unlock the additional behaviour. 

Martin

**Comment by mna** [comment]
Allright so I'm thinking adding something like this:

```
func Single(string) Matcher {...}
func SingleMatcher(Matcher) Matcher {...}
```

The idea being that it follows the naming convention of the rest of the goquery API, with the selector string function version having no specific suffix, and the Matcher-based one have the `Matcher` suffix. Both return a `Matcher` that stops matching at the first match and allows using the methods like this:

```
sel.FindMatcher(goquery.Single("div.someClass"))
```

In other words, you call the `Matcher` version of the functions instead of the selector string one, and convert the selector string to a single matcher using this call. Similarly if you already have a compiled `Matcher`, you can easily convert it to the single version like this:

```
m := cascadia.MustCompile("div.someClass")
sel.FindMatcher(goquery.SingleMatcher(m))
```

Thoughts?
Martin

**Comment by gdollardollar** [comment]
That looks great!

**Comment by mna** [comment]
Thanks but I got it mostly done already in `wip-i255-single-match` branch. I'm gonna improve the docs a bit and it should land today with a new version.

**Comment by mna** [comment]
It's now merged, thanks for the help on this!
