### ISSUE TITLE
Can the result of func (*Selection) Map not be []string?

### ISSUE THREAD

**Issue by excosy** [PuerkitoBio/goquery#256]
Can `func (*Selection) Map` be defined as `func (s *Selection) Map(f func(int, *Selection) interface{}) (result []interface{})`? Or only use func (s *Selection) Each(f func(int, *Selection)) to do it?

**Comment by mna** [comment]
Hello,

Yeah as you mention, `Map` is only used to return `string`s, as it seems the most likely use-case for it when processing html and I wanted to avoid any use of `interface{}` in the signatures. If you need `Map`-style iteration for something else, as you hinted at, you can use `Each` with a closure over your typed slice, e.g. (untested):

```
var ints []int
sel.Each(func(i int, s *goquery.Selection) {
  // use s to get a value
  someInt, _ := strconv.Atoi(someString)
  ints = append(ints, someInt)
})
// use the ints slice
```

Hope this helps,
Martin

**Comment by excosy** [comment]
Got it. Thanks for explaining patiently.
