### ISSUE TITLE
Can embedded html tags be interpreted

### ISSUE THREAD

**Issue by ericmontreal** [PuerkitoBio/goquery#257]
1st, thx for your lib !
In the RSS scraping I'm setting up, I'm stuck with one of my section  that html tagged. So instead of getting  well-formatted final text I get : 

> `<p>First paragraph</p><p>Second paragraph</p>`

 and so on... All other sections are fine.

Based on samples I found, here's my source code  
```
...
doc.Find("item").Each(
		func(index int, item *goquery.Selection) {
                       //
			titleTag := item.Find("title")
			title := titleTag.Text()

			descriptionTag := item.Find("description")
			description := html.UnescapeString((descriptionTag.Text())

			temp := Article{NumArticle: index, TitleArticle: title, ContentArticle: description}
			ArticlesPageData = append(ArticlesPageData, temp)
		})
               return ArticlePageData
....

```
I used UnescapeString() to get rid of specific HTML codes (as &eacute; or &rsquo;) and retrieve accented letters but all embedded HTML tags remains. Does goquery able to interpret them ?

**Comment by mna** [comment]
Hello Eric,

Can you provide the full input text that you're parsing (the RSS document)? I suspect that the html is escaped in the RSS, and so once unescaped it (correctly) returns html content. You could get around that by re-parsing the text that is returned with goquery, and extract the text-only content that you want.

Also note that goquery is for parsing html, using it to parse arbitrary XML-based data may return weird results as some tags have specific meaning in html and the parser may apply html5-specified corrections.

Martin

**Comment by ericmontreal** [comment]
Thank you Martin for your fast answer. Here's,for example, what RSS looks like:

```
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xml:base="http://www.montrealmatin.com"  xmlns:dc="http://purl.org/dc/elements/1.1/">
<channel>
 <title>Montreal Matin</title>
 <link>http://www.montrealmatin.com/rss.php</link>
 <description></description>
 <language>fr</language>
<item>
 <title>Apple devient la première entreprise privée à valoir 1.000 milliards de dollars en Bourse</title>
 <link>http://www.montrealmatin.com/article-383915-Apple-devient-la-premiere-entreprise-privee-a-valoir-1000-milliards-de-dollars-en-bourse.html</link>
 <description>&lt;p&gt;Apple, le groupe am&amp;eacute;ricain connu pour avoir r&amp;eacute;volutionn&amp;eacute; le monde de l&#039;informatique avec ses t&amp;eacute;l&amp;eacute;phones et ses tablettes, est devenu jeudi la premi&amp;egrave;re entreprise priv&amp;eacute;e &amp;agrave; valoir plus de 1.000 milliards de dollars en Bourse.&amp;nbsp;&lt;br&gt;&lt;span style=&quot;color: #333333; font-family: Georgia, Arial, Helvetica, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;&quot;&gt;&lt;span&gt;&lt;br&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;&lt;p style=&quot;text-align: center;&quot;&gt;&lt;iframe src=&quot;//www.dailymotion.com/embed/video/x6cbn9q?autoPlay=1&amp;amp;mute=1&quot; allowfullscreen=&quot;&quot; allow=&quot;autoplay&quot; width=&quot;770&quot; height=&quot;420&quot; frameborder=&quot;0&quot;&gt;&lt;/iframe&gt;&lt;/p&gt;
</description>
</item>
...
<item>
...
</item>
</channel>
</rss>
```

Eric

**Comment by mna** [comment]
Merci Eric,

Indeed there is escaped html inside the `<item><description>` tag, so when you get the unescaped text (by calling `Text()`), it returns the content with html tags, that's the proper behaviour of `Text()`.

What you can do then, since this is html, is to parse *that* content with goquery and retrieve only the text, e.g.:

```
        // "data" is the RSS document string
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}
        // Find with a simplified selector string just for this example, you should still loop on item of course
	t := doc.Find("item description").Text()

	d2, err := goquery.NewDocumentFromReader(strings.NewReader(t))
	if err != nil {
		log.Fatal(err)
	}
	t2 := d2.Text()
	fmt.Println(t2)
```

That being said, for the RSS parsing you should definitely use an RSS parser instead (https://godoc.org/?q=rss), as I mentioned earlier goquery is an html parser and follows rules that are meant for html that may not apply or may do surprising things with RSS. The *content* of the description, however, can definitely be parsed with goquery.

Hope this helps!
Martin

**Comment by ericmontreal** [comment]
Parsing twice is a solution not to see all these tags. But it then loose layout.... The ideal would be to make them interpreted...

Anyways, you pinpoint my mistake about parsing an RSS file.

Merci encore !
;)

**Comment by mna** [comment]
No problem Eric. Sorry I misunderstood your issue, I thought you wanted to get the text without the html tags. I'm not sure I understand what you mean by interpreting them? This is html, so if you render them in a web browser, it will display as expected (without losing the layout) - you don't even have to unescape the string for accents and all, this is correctly encoded for html and will render as expected.

So basically if what you want is to parse RSS and render the descriptions in a web browser, you don't need goquery at all (unfortunately! :D just kidding, right tool for the job is the goal). You need an RSS/Atom parser, and then save the descriptions to be rendered at some point in a web browser (assuming that's what you want to do). Note that there are some security concerns with that (displaying arbitrary html from a source you don't control), but I don't know the context of your app, just keep that in mind if that's for anything more than hobby / experimentation!

Have fun!
Martin

**Comment by ericmontreal** [comment]
Sorry for my english, Martin. You write:

> "This is html, so if you render them in a web browser, it will display as expected"

Unfortunately not in my case  :( as tags are first encoded.

Chrome returns _description_ section with all HTML tags obtained as-is from my code and not layout'd (not **interpreted**) by browser as I could expect..

Indeed, I summarize my issue for future readers. The line of my source code:

`description := descriptionTag.Text()`

took this _description_ section of RSS source file:

`<description>&lt;p&gt;Apple, le groupe am&amp;eacute;ricain connu pour avoir r&amp;eacute;volutionn&amp;eacute; le monde...`

and rendered into this:

`<p>Apple, le groupe am&eacute;ricain connu pour avoir r&eacute;volutionn&eacute; le monde...`

I then added the UnescapeString() command :

`description := html.UnescapeString((descriptionTag.Text())`

to render accents properly:
`<p>Apple, le groupe américain connu pour avoir révolutionné le monde...`

The next step would be to get these remaining tags being executed by brower in order to get a non-monolithic _description_ section...

I targeted RSS thinking that it could easier my task. Maybe I need to fully rethink my approach.

**Comment by mna** [comment]
Sorry, what I meant is that this (that you currently get via goquery):

```
description := descriptionTag.Text()
```

Gets you valid html, and that html can then be rendered by a browser properly (without the need to unescape `description`, as this is a correct way to encode accents and browsers will handle it).

E.g. if you save the string `<p>Apple, le groupe am&eacute;ricain connu pour avoir r&eacute;volutionn&eacute; le monde...</p>` into a file, and then use File -> Open File in your favorite browser, it will render as `Apple, le groupe américain connu pour avoir révolutionné le monde...` (inside a `<p>` tag).

I will close the issue, since I don't think there's much more that involves goquery, but feel free to reopen (or open a new issue) if there's something else!

Thanks,
Martin
