### ISSUE TITLE
How to get html/text result of current selection?

### ISSUE THREAD

**Issue by Tom29** [PuerkitoBio/goquery#258]
After selected an element, how do i get the whole text of it, like printing out meta tag strings?
`d.document.Find("meta[property=\"og:description\"]")`

**Comment by mna** [comment]
Hello,

I believe what you are looking for is `OuterHtml` (https://godoc.org/github.com/PuerkitoBio/goquery#OuterHtml). It returns the element for the first item in the selection, as well as any attributes and inner elements.

Hope this helps,
Martin
