### ISSUE TITLE
[Question]  Is there any way to identify hidden elements?

### ISSUE THREAD

**Issue by Faegy** [PuerkitoBio/goquery#260]
I'm porting a Javascript library to Go and encountered the following function:
```js
_isProbablyVisible: function(node) {
    return node.style.display != "none" && !node.hasAttribute("hidden");
  }
```

Is there any way to translate the `node.style.display  != "none"` in Go ?
If not, are there any libraries that, according to css rules, modify the nodes by reporting these rules inside the node's style attribute?

**Comment by mna** [comment]
Hello,

Unfortunately, unlike when running javascript in the browser, goquery works with a "static" DOM so it cannot access those dynamic properties. You can check for the `hidden` attribute, but the `style`, if set via an external CSS stylesheet or dynamically using javascript, will not be available to goquery. I don't know of any library that applies a set of CSS rules to an HTML source document, but although that would be nice, it still wouldn't handle classes and style done via javascript (unless you use a headless browser to grab the source).

The short anwser is no, unfortunately! If you find a package that applies the CSS to the HTML nodes, please let me know, I'd be happy to add something in the doc to mention it.

- Martin

**Comment by Faegy** [comment]
Made a solution: [goApplyCss](https://gitlab.com/Maxithi/goApplyCss). Still some testing needed to verify spec validity but does the trick as hell 😊
