### ISSUE TITLE
Break or Limit .Each goquery selection ?

### ISSUE THREAD

**Issue by radiaku** [PuerkitoBio/goquery#262]
Hey, How to limit goquery each? ( I'm still new in golang, so please bear with me )
The elements have 50 item. But I want to get 10 of its. I cant use break cause its not select or switch 

So I implemented with my own limit. Not pretty but its works. 

```
doc.Find(".item a.thumb").Each(func(i int, s *goquery.Selection) {

		if i <= int(limit) {
                  //download image in here
                }
})

```

My question is, Is there any wise solution than this, More "resource-wise"?

Thank you.

**Comment by mna** [comment]
Hello,

There's the `EachWithBreak` function (https://godoc.org/github.com/PuerkitoBio/goquery#Selection.EachWithBreak) that stops looping as soon as you return `false`. But if you know in advance that you just want to loop over N elements, you can first reduce your selected items with `Slice(0, N)` (https://godoc.org/github.com/PuerkitoBio/goquery#Selection.Slice) and then loop with `Each` on each of them.

Hope this helps!
Martin

**Comment by radiaku** [comment]
> Hello,
> 
> There's the `EachWithBreak` function (https://godoc.org/github.com/PuerkitoBio/goquery#Selection.EachWithBreak) that stops looping as soon as you return `false`. But if you know in advance that you just want to loop over N elements, you can first reduce your selected items with `Slice(0, N)` (https://godoc.org/github.com/PuerkitoBio/goquery#Selection.Slice) and then loop with `Each` on each of them.
> 
> Hope this helps!
> Martin

Thank you martin, I prefer eachwithbreak is more suitable ( in my case ) than slice. I dont need check number of element in doc.find. :D
