### ISSUE TITLE
Selection order

### ISSUE THREAD

**Issue by mbaranovzuzex** [PuerkitoBio/goquery#263]
I'm wondering if there is any way to walk through my selection from the last found element to the first one. For example: 
I have html: 
```
<div class="one">1</div>
<div class="one">2</div>
<div class="one">3</div>
<div class="one">4</div>  
```
and I use your .Each function for selection 'one' elements (of course there is no elements with this class anymore). But Each func walks by default order. Can I walk through this selection from '4' to '1' element?

**Comment by mna** [comment]
Hello,

Since a `goquery.Selection` is basically a struct with a slice of html nodes, you can loop on it in reverse order almost like you would a standard Go slice:

```
var data = `
<html>
  <head>
  </head>
  <body>
    <div class="one">1</div>
    <div class="two">2</div>
    <div class="three">3</div>
    <div class="four">4</div>
  </body>
</html>
`

func main() {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}

	divs := doc.Find("div")
	for i := divs.Length() - 1; i >= 0; i-- {
		fmt.Println(divs.Eq(i).Text())
	}
}

// Prints 4, 3, 2, 1
```

Hope this helps!
Martin

**Comment by mbaranovzuzex** [comment]
> I'm wondering if there is any way to walk through my selection from the last found element to the first one. For example:
> I have html:
> 
> ```
> <div class="one">1</div>
> <div class="one">2</div>
> <div class="one">3</div>
> <div class="one">4</div>  
> ```
> and I use your .Each function for selection 'one' elements (of course there is no elements with this class anymore). But Each func walks by default order. Can I walk through this selection from '4' to '1' element?

**Comment by mbaranovzuzex** [comment]
Thanks, It did. Could figure out myself 8)
