### ISSUE TITLE
AddBack func error 

### ISSUE THREAD

**Issue by mbaranovzuzex** [PuerkitoBio/goquery#264]
for i := 27; i >= 26; i--{
	
    if (countErr > 10) {
		fmt.Printf("Failed to load %v page. End prog!", i)
		// return nil, err
	}

	fmt.Printf("page %v\n", i)
	pageUrl = myUrl + "/discuss?page=" + strconv.Itoa(i)
	doc, err := goquery.NewDocument(pageUrl)
	if (err != nil) {
		fmt.Printf(" Err: %v (trying again ...)\n", err)
		// try this page again
		i++
		continue
	}

	countErr = 0
	find = doc.Find(".discuss-details");
	fmt.Printf("\tpage %v: len(%v)\n", i, find.Length())
	allFinds = allFinds.AddBack() //main.go:45
    }

I'm trying some code for parsing, but keep getting this error for AddBack func:

```
    page 27
          page 27: len(6)
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x624202]

    goroutine 1 [running]:
    github.com/PuerkitoBio/goquery.(*Selection).AddBack(0x0, 0x12)
	/home/redhat/go/src/github.com/PuerkitoBio/goquery/expand.go:53 +0x22
    main.main()
	/home/redhat/go/src/jirasnatch/bitch/main.go:45 +0x2c7
    exit status 2
```
As you can see len(6) is printed. So I assume Node is not empty. What else it could be?
I'll send you myUrl string if needed. It's task from my job, not sure if I can publish url.
Tried AddSelection func, but then realized it's almost the same.

**Comment by mna** [comment]
Hello,

Can you print the full code (formatted with gofmt ideally)? I don’t see where `allFinds` come from, it might be nil. 

Martin

**Comment by mbaranovzuzex** [comment]
Hello, Martin. 
Above: `var allFinds *goquery.Selection`. You right, it's nil. I see I needed to declare not pointer but instanse of goquery.Selection. Sorry for bothering with dumb question, newer))
