### ISSUE TITLE
关于读取<meta name="description" content="">中content内容的问题

### ISSUE THREAD

**Issue by wuknet** [PuerkitoBio/goquery#265]
我试了一天，想办法读<meta name="description" content="aaa">content中内容的问题，我是想读取keywords和description的内容，Find了meta[name]然后不知道如何去取content的内容了。name有很多类型，但我只想取指定的keyword和description的内容。请群主指教。谢谢

**Comment by mna** [comment]
Leaving open in case anyone can help out, Google translate was not super useful to me.

**Comment by missdeer** [comment]
@wuknet 

```go
keywords, _ = doc.Find("meta[name=\"keywords\"]").Attr("content")
description, _ = doc.Find("meta[name=\"description\"]").Attr("content")
```

**Comment by wuknet** [comment]
> @wuknet
> 
> ```go
> keywords, _ = doc.Find("meta[name=\"keywords\"]").Attr("content")
> description, _ = doc.Find("meta[name=\"description\"]").Attr("content")
> ```

谢谢

**Comment by mna** [comment]
Seems to be resolved from what I understand, thank you @missdeer for helping out!

**Comment by wuknet** [comment]
> @wuknet
> 
> ```go
> 关键字，_ = doc。查找（“ meta [name = \” keywords \“ ] ”）。Attr（“内容”）
> description，_ = doc。查找（“ meta [name = \” description \“ ] ”）。Attr（“内容”）
> ```

不过有一个新问题，keywords这些关键字大小写，如何解决，比如KEYwords，就是不区分大写小写？
