### ISSUE TITLE
doc.Find("GetMatchingProductResult").Each has not worked

### ISSUE THREAD

**Issue by mikeshimura** [PuerkitoBio/goquery#266]
[matchingProductbu.txt](https://github.com/PuerkitoBio/goquery/files/2564737/matchingProductbu.txt)
with attached xml doc.Find("GetMatchingProductResult").Each first one include
both first part and second part

Best regards
Mike Shimura

**Comment by mna** [comment]
Hello,

Note that goquery is an **html** parser, not an **xml**. It uses the `golang.org/x/net/html` parser internally, which follows the html5 parsing spec. When it parses your xml, this is what is actually returned to goquery:

[data.txt](https://github.com/PuerkitoBio/goquery/files/2566275/data.txt)

Hope this helps,
Martin

**Comment by mikeshimura** [comment]
Thank you very much for your quick advise.
Fully understood.

Best regards,

Mike Shimura
