### ISSUE TITLE
Traverses only one level

### ISSUE THREAD

**Issue by Vliro** [PuerkitoBio/goquery#269]
Using r.Find traverses only one level of the tree, i.e. the immediate descendants. Should it not traverse the entire tree?

GO ENV:
`GOARCH="amd64"
GOBIN=""
GOCACHE="/home/a/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/a/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build061603218=/tmp/go-build -gno-record-gcc-switches"
`
For instance, if I want to find a specific node three levels down I have to
`r.Find("s1").Find("s2").Find("s3")`
Is this intended behaviour? As it seems pretty finicky. I am searching for class-names of the form "test-class-123", and it only returns an answer if it is a direct descendant.

**Comment by mna** [comment]
Hello,

Please provide a complete, minimal program with data to reproduce the issue. This simple example works as expected and does indeed search multiple levels down:

```
var data = `
<html>
  <head>
  </head>
  <body>
    <div class="c1">
      <div class="c2">
        <div class="c3">
          <div class="c4">
          </div>
        </div>
      </div>
    </div>
  </body>
</html>
`

func main() {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}
	s := doc.Find("body").Find(".c4")
	v, err := goquery.OuterHtml(s)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(v)
}
// prints <div class="c4"></div>
```

Martin

**Comment by Vliro** [comment]
I am trying to parse a local website, and it doesn't seem to work.
`func main() {
	res, err := http.Get("https://www.ica.se/recept/raw-knack-med-cashewnotter-724976/")
	if err != nil {
		return 
	}

	r, err := goquery.NewDocumentFromReader(res.Body)
	f := r.Find("body").Find(".cooking-step__content__instruction")
	fmt.Println(len(f.Nodes))`
}
`
I also tried
`	f := r.Find(".cooking-step__content__instruction")
`
I might be misunderstanding how to use goquery properly, but I've used a bunch of jquery and I thought it would behave similarly. Expected behaviour is returning the relevant nodes with the class specified.

**Comment by mna** [comment]
Unlike `jquery`, `goquery` doesn't run in the browser, and as such cannot (directly) access nodes that are created via javascript. The way you parsed the document, you can only see the nodes that are part of the `html` source, and there is no `.cooking-etc.` class element in the html. Those nodes get created dynamically in the browser via javascript.

You can take a look at the wiki for how javascript-based pages can be handled with goquery (https://github.com/PuerkitoBio/goquery/wiki/Tips-and-tricks#handle-javascript-based-pages), but note that this is helpful information provided by the community, I haven't used those myself.

Hope this helps,
Martin

**Comment by Vliro** [comment]
I can, however, manually access them. Is the class then set by javascript? Currently I do this

`	r.Find("#recipe-howto-steps").Each(func(i int, s *goquery.Selection) {
		f := s.Children()
		g := f.Children()
		//	k := g.Children()
		g.Children().Each(func(l int, ss *goquery.Selection) {
			n := ss.Nodes[0]
			if n.FirstChild == nil {
				return
			}
			if n.FirstChild == n.LastChild {
                       //data
			} else {
				//data
			}
		})
	})`
Which can access them just fine.

**Comment by mna** [comment]
I didn't check what node had the class you mentioned, but if it is under the id you use here, yes possibly that is the element that gets the `cooking` class via javascript. If that does what you want, you can use this approach to parse without javascript support.

You can use triple backquotes to insert pre-formatted code (i.e. ` ``` followed by newline, paste your code followed by newline, then end with another triple-quote ``` `).
