### ISSUE TITLE
Wildcards in selectors

### ISSUE THREAD

**Issue by seaguest** [PuerkitoBio/goquery#272]
Hello,

I am wondering if it is possible to use wildcard in selector.

For example, I have a html which contains:
```
<div id="NODE1"></div>
<div id="NODE2"></div>

```

I want to get all ids which stars with NODE*, is it possible?

**Comment by mna** [comment]
Hello,

You can achieve this with attribute selectors (https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors), the ID being only a special attribute:

```
var data = `
<div id="NODE1"></div>
<div id="NODE2"></div>
<div id="OTHER"></div>
`

func main() {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}
	doc.Find("[id^=NODE]").Each(func(i int, s *goquery.Selection) {
		h, err := goquery.OuterHtml(s)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println(i, h)
	})
}
// Prints NODE1 and NODE2
```

Hope this helps,
Martin

**Comment by dzpt** [comment]
@mna how about attribute? i've tried with `Attr("^data")` but doesn't work

**Comment by mna** [comment]
The `Attr` method takes an attribute name and returns its value, it doesn't take a selector. You have to use a method that takes a selector (such as `Find` as in the example) for this, e.g. `doc.Find("[attr^=data]")`.

**Comment by dzpt** [comment]
@mna This is for searching `attr` has value that begins with `data`. not what i wanted.
i want to seek for attribute name which begins with data, like `data-src`, `data-org` ....

**Comment by mna** [comment]
AFAIK: https://stackoverflow.com/a/36891269/1094941
