### ISSUE TITLE
How to get the value in the red box？

### ISSUE THREAD

**Issue by fengweiqiang** [PuerkitoBio/goquery#274]
How to get the value in the red box？
![image](https://user-images.githubusercontent.com/22905300/49776998-87e9a680-fd39-11e8-9118-806aa61bcc0f.png)
I didn't take the middle value with the not method.
![image](https://user-images.githubusercontent.com/22905300/49777190-7228b100-fd3a-11e8-92f8-bd2a7a130e82.png)

**Comment by fengweiqiang** [comment]
s.Find("a").ReplaceWithSelection(s.FindNodes(s.Find("span").Nodes[0],s.Find("i").Nodes[0])).Text()
I've got the value. Is there an unknown exception to do so?

**Comment by mynameiskreang** [comment]
@fengweiqiang 
`s.Find("span").Remove()`
`s.Find("i").Remove()`
result = `s.Text()`

**Comment by fengweiqiang** [comment]
Very well, thank you.

**Comment by fengweiqiang** [comment]
hello！Hello, I can't get the href content of label A.
![image](https://user-images.githubusercontent.com/22905300/49786720-b5494b00-fd5f-11e8-9029-6c2b33834564.png)

Getting label A does not get href content
![image](https://user-images.githubusercontent.com/22905300/49786815-f3df0580-fd5f-11e8-83d3-0005c991fa08.png)

You can't go through every content without getting the A tag and getting the whole content.
![image](https://user-images.githubusercontent.com/22905300/49786853-11ac6a80-fd60-11e8-8ea8-e78006cff433.png)


```
<div class="col-xs-12 col-sm-12 col-md-5 home_list180625_jtyw padd_180625_none" style="padding-left:1px;margin-bottom:-7px;">
					<h3><span style="cursor:pointer;" onclick="open_href('./jiaotongyaowen/')">交通要闻</span></h3>
					<div class="list-group ">
                                                
						<a href="./jiaotongyaowen/201812/t20181210_3142138.html" target="_blank" title="中国速度彰显大国气象 部领导参观改革开放40周年大型展览" class="list-group-item"><img src="./images/mot2016_bg50.png"><span>中国速度彰显大国气象 部领导参观改革开放40周...</span><span class="badge" style="float:right;">[12-10]</span></a>
						
						<a href="./jiaotongyaowen/201812/t20181210_3142137.html" target="_blank" title="刘小明会见世界银行客人" class="list-group-item"><img src="./images/mot2016_bg50.png"><span>刘小明会见世界银行客人</span><span class="badge" style="float:right;">[12-10]</span></a>
						
						<a href="./jiaotongyaowen/201812/t20181211_3142182.html" target="_blank" title="以严谨作风专业精神投身交通强国建设新征程——三论向“中国民航英雄机组”“中国民航英雄机长”学习" class="list-group-item"><img src="./images/mot2016_bg50.png"><span>以严谨作风专业精神投身交通强国建设新征程—...</span><span class="badge" style="float:right;">[12-11]</span></a>
						
						<a href="./jiaotongyaowen/201812/t20181211_3142187.html" target="_blank" title="交通运输行业媒体发展研讨会举行" class="list-group-item"><img src="./images/mot2016_bg50.png"><span>交通运输行业媒体发展研讨会举行</span><span class="badge" style="float:right;">[12-11]</span></a>
						
						<a href="./jiaotongyaowen/201812/t20181211_3142192.html" target="_blank" title="青海新增4条公路通车" class="list-group-item"><img src="./images/mot2016_bg50.png"><span>青海新增4条公路通车</span><span class="badge" style="float:right;">[12-11]</span></a>
						
						<a href="./jiaotongyaowen/201812/t20181211_3142193.html" target="_blank" title="第三批超限超载失信人名单公布" class="list-group-item"><img src="./images/mot2016_bg50.png"><span>第三批超限超载失信人名单公布</span><span class="badge" style="float:right;">[12-11]</span></a>
						
						<a href="./jiaotongyaowen/201812/t20181211_3142212.html" target="_blank" title="高速公路运输从零起步——访长安大学原校长陈荫三" class="list-group-item"><img src="./images/mot2016_bg50.png"><span>高速公路运输从零起步——访长安大学原校长陈荫三</span><span class="badge" style="float:right;">[12-11]</span></a>
						
					</div>
				</div>
```

**Comment by fengweiqiang** [comment]
I'm here again. It's settled.
	textUrl, b := s.Prepend("a").Attr("href")

**Comment by mynameiskreang** [comment]
@fengweiqiang 
`url,err:=s.Find("a").Attr("href")`
`url:=s.Find("a").AttrOr("href","default-value")`

`img:=s.Find("img").Attr("src")`

`s.Find("span").Each(func(i int, span *goquery.Selection) {
fmt.Println(span.Text())
})`
or
`s.Find("span").eq(0).Text()`
`s.Find("span").eq(1).Text()`
or
get span.badge then get span
`badge:=s.Find("span.badge').Remove()`
then `spanText:=s.Find("span").Text()`
