### ISSUE TITLE
I can't insert data to mongodb 

### ISSUE THREAD

**Issue by jirawat050** [PuerkitoBio/goquery#279]
panic: BSON field 'insert.documents.0' is the wrong type 'array', expected type 'object'

goroutine 1 [running]:
main.ExampleScrape.func1(0x0, 0xc00034d9e0)
        /Users/macbook/go/src/github.com/jirawat050/api/api.go:57 +0x557
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc00034d9b0, 0xc00048bf40, 0x16)
        /Users/macbook/go/src/pkg/mod/github.com/!puerkito!bio/goquery@v1.5.0/iteration.go:10 +0x53
main.ExampleScrape()
        /Users/macbook/go/src/github.com/jirawat050/api/api.go:41 +0x228
main.main()
        /Users/macbook/go/src/github.com/jirawat050/api/api.go:65 +0x20
exit status 2
My Code 
package main

import (
	"fmt"
	"log"
	"net/http"
	"time"

	"github.com/PuerkitoBio/goquery"
	"gopkg.in/mgo.v2"
	//"gopkg.in/mgo.v2"
)

type Data struct {
	Name string `json:"name" bson:"name"`
	Away string `json:"away" bson:"away"`
	// Pop       int       `json:"pop" bson:"pop"`
	CreatedAt time.Time `bson:"createdAt"`
}
type Datas []Data

func ExampleScrape() {
	// Request the HTML page.
	session, err := mgo.Dial("mongodb://127.0.0.1:27017")
	res, err := http.Get("https://www.edtguide.com/place/%E0%B8%AB%E0%B8%A1%E0%B8%A7%E0%B8%94%E0%B9%82%E0%B8%A3%E0%B8%87%E0%B8%9E%E0%B8%A2%E0%B8%B2%E0%B8%9A%E0%B8%B2%E0%B8%A5/%E0%B8%AA%E0%B8%A1%E0%B8%B8%E0%B8%97%E0%B8%A3%E0%B8%9B%E0%B8%A3%E0%B8%B2%E0%B8%81%E0%B8%B2%E0%B8%A3/view/P0")
	if err != nil {
		log.Fatal(err)
	}
	defer res.Body.Close()
	if res.StatusCode != 200 {
		log.Fatalf("status code error: %d %s", res.StatusCode, res.Status)
	}

	// Load the HTML document
	doc, err := goquery.NewDocumentFromReader(res.Body)
	if err != nil {
		log.Fatal(err)
	}

	// Find the review items
	doc.Find(".archive-list article ").Each(func(i int, s *goquery.Selection) {
		// For each item found, get the band and title
		band := s.Find("p").Text()

		title := s.Find("h2").Text()
		log.Printf("Review %d: %s  - %s\n", i, band, title)
		session.SetMode(mgo.Monotonic, true)
		d := session.DB("api").C("api")

		doc := Datas{
			Data{Name: title, Away: band},
		}

		err = d.Insert(doc)
		fmt.Println(doc)
		if err != nil {
			panic(err)
		}

	})

}

func main() {
	ExampleScrape()

}

**Comment by mna** [comment]
Hello,

This is unrelated to goquery, but it looks like the error message is pretty clear. You're passing an array (`type Datas []Data`) when the method seems to expect an object (i.e. a `Data`).

Martin
