### ISSUE TITLE
about vmerge cell

### ISSUE THREAD

**Issue by TimLiuDream** [PuerkitoBio/goquery#282]
i have an html file like this 
![image](https://user-images.githubusercontent.com/15154520/52162249-f2044380-270b-11e9-857a-d6c4727dee45.png)
![image](https://user-images.githubusercontent.com/15154520/52162306-c6ce2400-270c-11e9-9949-09071c58ae4b.png)
i want to parse the html table 
but i have problem 
how to calculate the "2c" column index in row 1?
i can't found any mathod
who can help me ?

**Comment by mna** [comment]
Hello,

I'm not sure what you mean by:

> calculate the "2c" column index in row 1?

You can iterate over all rows of the body of the table with `doc.Find("tbody tr").Each`, and inside each row use `row.Find("td")` to do what you need to do with each column (I mean, you can also use `doc.Find("tbody tr td")` if you want to select all cells directly, but I feel from your question that you need them row-by-row somehow?). If the "column index" is important to you, you will have to to take the `colspan` and `rowspan` attributes into account (you can get their value using e.g. `cell.Attr("colspan")`).

Hope that helps,
Martin

**Comment by TimLiuDream** [comment]
I know what you said, but it doesnot work for me, i have to know the each cell column index, because i want to parse html element to write word. No matter what, thanks, my english is poor. I don't know how to explain
