### ISSUE TITLE
Parsing HTML injects tags not present in the original source data

### ISSUE THREAD

**Issue by FooSoft** [PuerkitoBio/goquery#283]
I am using goquery to make modifications to arbitrary HTML documents and output modified versions in a static site generator. I noticed that after creating a document using `NewDocumentFromReader`, making some simple modifications (in this case, making all `src` and `href` paths absolute), and extracting the generated HTML via the `Html` method, goquery adds the `html`, `head`, and `body` tags even if they were absent in the source data.

For example:
```html
<p>Hello world</p>
```
gets turned into something like:
```html
<html><head></head><body>
<p>Hello world</p>
</body></html>
```

This causes problems for me since I am trying to process which could just be HTML fragments (for example, output from a markdown processor, which would normally be injected into a layout using Go templates).

I realize that I can just do something like:
```go
doc.Find("body").Html()
```

The problem with this is that in the interests of keeping things generic, I would like for goquery to not make any modifications to the document which were not requested. Is this a limitation of goquery, or is there a different approach that I could take to avoid this issue?

**Comment by mna** [comment]
Hello Alex,

You're right, nodes can be added/nesting modified when parsing an incomplete html document, that's the behaviour of the underlying `x/net/html` parser that is used by goquery, the `html.Parse` function comments mentions:

```
// Parse returns the parse tree for the HTML from the given Reader.
//
// It implements the HTML5 parsing algorithm
// (https://html.spec.whatwg.org/multipage/syntax.html#tree-construction),
// which is very complicated. The resultant tree can contain implicitly created
// nodes that have no explicit <tag> listed in r's data, and nodes' parents can
// differ from the nesting implied by a naive processing of start and end
// <tag>s. Conversely, explicit <tag>s in r's data can be silently dropped,
// with no corresponding node in the resulting tree.
```

However, it does have a `ParseFragment` function (https://godoc.org/golang.org/x/net/html#ParseFragment) that can be used to parse partial html docs. This workaround would get you the partial html without added nodes:

```
var data = `
<p>Hello world</p>
`

func main() {
	ctx := &html.Node{
		Type:     html.ElementNode,
		DataAtom: atom.Div,
		Data:     "div",
	}
	ns, err := html.ParseFragment(strings.NewReader(data), ctx)
	if err != nil {
		log.Fatal(err)
	}

	// because of the whitespace around data, there might be more than one
	// node returned, find the Element node.
	var p *html.Node
	for _, n := range ns {
		if n.Type == html.ElementNode {
			p = n
			break
		}
	}

	doc := goquery.NewDocumentFromNode(p)
	h, err := goquery.OuterHtml(doc.Selection)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(h)
}
```

It's tricky to generalize this and make it e.g. a `goquery.NewFragmentFromReader(r)`, because the context into which the node should be parsed is important (e.g. if you wanted to parse a "td", you'd need to be in a table row). It would likely require a context node just like `html.ParseFragment`, but then you need to be aware of the fragment you're parsing, which isn't much different at this point than using `goquery.NewDocument...` and finding the top node you want :/ 

In any case, hope this helps, if you have any idea how that could be generalized enough to make sense as a goquery function, I'd be happy to hear them!

Martin

**Comment by FooSoft** [comment]
Thank you for the prompt and thorough reply, I really appreciate your time and insight. 

One question I have about the sample code you provided is that it looks for an element (in this case the `p` tag), and then proceeds to parse that and its children, potentially ignoring other contents. For example:

```html
<p>hello</p>
<p>world</p>
```

I see where `html.ParseFragment` would be parsing it in the context of a `div` tag, that makes perfect sense. However tags that come after that are thrown out. Thus running the code on the HTML snippet above only returns `<p>hello</p>`. 

After messing around locally, I came up with the following solution:

```go
package main

import (
	"fmt"
	"log"
	"strings"

	"github.com/PuerkitoBio/goquery"
	"golang.org/x/net/html"
	"golang.org/x/net/html/atom"
)

var data = `
Foo
<p>Hello</p>
<div>World</div>
Bar
`

func main() {
	ctx := &html.Node{
		Type:     html.ElementNode,
		DataAtom: atom.Div,
		Data:     "div",
	}

	ns, err := html.ParseFragment(strings.NewReader(data), ctx)
	if err != nil {
		log.Fatal(err)
	}

	for _, n := range ns {
		ctx.AppendChild(n)
	}

	doc := goquery.NewDocumentFromNode(ctx)
	h, err := doc.Html()
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(h)
}
```

This appears to work for my slightly more complicated contrived example;  do you see any problems with this approach?

**Comment by mna** [comment]
That seems fine to me, if you have more than one node in the fragment, using the context node as "root" node makes a lot of sense, if you don't mind the additional parent "div".

**Comment by FooSoft** [comment]
Bah, after doing some testing, it appears that my solution has the problem of eliminating the `html` tag on documents that already have it. This is probably happening because the HTML parser decides to throw away `html` tags that are under `div` tags.

**Comment by mna** [comment]
ah yeah, definitely, that would only work for fragments. The `net/html` parser will tweak tags that don't make sense in the context it is parsed - either adding, removing or moving around.

**Comment by FooSoft** [comment]
I guess the thing to do is to try to find an `html` element, if it exists, parse normally. If it does not exist, create a dummy `div` element, stuff all fragments node inside of it and parse that instead. 

I'll update this issue with a version that does this, in case other folks run into this issue in the future.

**Comment by mna** [comment]
Cool thanks :+1: . Note that this still wouldn't work perfectly for some special tags that need specific parent tags (that don't fit in a "div"), e.g. "tbody", "td", "dt", "dd", etc.
