### ISSUE TITLE
some string lost

### ISSUE THREAD

**Issue by z0921** [PuerkitoBio/goquery#286]
the html is like this:

```
...
<div class="list-body">
					<div class="item">
						<p><a href="./201711/t20171108_9558760.htm" target="_blank" title="深圳市科技创新委员会关于不再办理企业研究开发费用税前扣除技术鉴定事项的通知">深圳市科技创新委员会关于不再办理企业研究开发费用税前扣除技术鉴定事项的通知</a><span class="t">2017年05月09日</span></p>
					</div>
					
					<div class="item">
						<p><a href="./201808/t20180808_13833769.htm" target="_blank" title="深圳市科技创新委员会关于征集重大项目专家库备选专家的通知">深圳市科技创新委员会关于征集重大项目专家库备选专家的通知</a><span class="t">2018年08月08日</span></p>
					</div>
					
					<div class="item">
						<p><a href="./201802/t20180201_10761225.htm" target="_blank" title="深圳市科技创新委员会关于征集专家库备选专家的通知">深圳市科技创新委员会关于征集专家库备选专家的通知</a><span class="t">2018年01月31日</span></p>
					</div>
</div>
...
```

my code is like this:
```
doc.Find(".list-body .item").Each(func(i int, selection *goquery.Selection) {
					url, _ := selection.Find("a").First().Attr("href")
					notice_url = strings.TrimSpace(notice_url)
					title, _ := selection.Find("a").Attr("title")
}
```

then i get the title is:
![image](https://user-images.githubusercontent.com/20654119/53728293-5c480980-3ead-11e9-8a60-29640d8f0b93.png)

why the title only half?

**Comment by mna** [comment]
It looks like some of those characters don't render correctly even on the github webpage (Unicode-encoded), but in any case, my guess is that it's because the input you passed to `goquery.NewDocument...` is not properly utf-8 encoded (you can see in your output the last character is an invalid rune one). The input has to be valid utf-8.

**Comment by z0921** [comment]
> 看起来这些字符中的一些甚至在github网页上都没有正确呈现（Unicode编码），但无论如何，我的猜测是因为你传递给的输入`goquery.NewDocument...`没有正确的utf-8编码（你可以看到）在你的输出中，最后一个字符是一个无效的符文）。输入必须是有效的utf-8。

```
doc, err := goquery.NewDocumentFromReader(res.Body)
s1, _ := doc.Html()
print(s)


doc, err := goquery.NewDocumentFromReader(res.Body)
doc.Find(".list-body .item").Each(func(i int, selection *goquery.Selection) {
s2, _ := selection.Html()
print(s)
}
```
i check the value of s1 and s2,s1 is normal,all the string is right,the s2 is incomplete,the location where s2 find is right in s1.s1 is normal is mean that the character is right,so i don't think is character error

the spider url is "http://stic.sz.gov.cn/xxgk/tzgg/"

**Comment by mna** [comment]
I don't know, my test shows that it prints the exact same thing that's in the document... I don't speak chinese so it's hard for me to assert visually, but if I select the text that this program prints, and searches for it in the html document (`page.html` is the content of the URL saved to a local file), it finds it and it is the complete content of the `title` attribute.

```
func main() {
	b, err := ioutil.ReadFile("./page.html")
	if err != nil {
		log.Fatal(err)
	}

	doc, err := goquery.NewDocumentFromReader(bytes.NewReader(b))
	if err != nil {
		log.Fatal(err)
	}

	doc.Find(".list-body .item a").Each(func(i int, s *goquery.Selection) {
		title := s.AttrOr("title", "")
                // prints the number of bytes and the text, if I select the text portion and search
                // for it in the page.html document (e.g. via Vim or grep), it finds it, and it matches
                // the full length of the "title" attribute, not just half of it.
		fmt.Println(len(title), title)
	})
}
```

Don't know what more I can do to help, sorry!

Martin

**Comment by z0921** [comment]
> I don't know, my test shows that it prints the exact same thing that's in the document... I don't speak chinese so it's hard for me to assert visually, but if I select the text that this program prints, and searches for it in the html document (`page.html` is the content of the URL saved to a local file), it finds it and it is the complete content of the `title` attribute.
> 
> ```
> func main() {
> 	b, err := ioutil.ReadFile("./page.html")
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 
> 	doc, err := goquery.NewDocumentFromReader(bytes.NewReader(b))
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 
> 	doc.Find(".list-body .item a").Each(func(i int, s *goquery.Selection) {
> 		title := s.AttrOr("title", "")
>                 // prints the number of bytes and the text, if I select the text portion and search
>                 // for it in the page.html document (e.g. via Vim or grep), it finds it, and it matches
>                 // the full length of the "title" attribute, not just half of it.
> 		fmt.Println(len(title), title)
> 	})
> }
> ```
> Don't know what more I can do to help, sorry!
> 
> Martin

I may have missed something,Thank you for answering me.
