### ISSUE TITLE
Quick question on some behaviour

### ISSUE THREAD

**Issue by jackmiller334** [PuerkitoBio/goquery#288]
Hi there. Just a quick question on some behaviour I'm seeing with Goquery. 

I wanted to get the entire HTML, perform a string replace and then pass that new HTML to goquery. 

(The html has already been parsed by goquery so I wish to try and avoid multiple rebuilding of by goquery)

The code I have is as follows

```
package main

import (
	"fmt"
	"log"
	"strings"

	"github.com/PuerkitoBio/goquery"
)

func main() {

	r := strings.NewReader(`<!DOCTYPE html>
	<head></head>
	<body>
		<p>
			some page content
		</p>
	</body>
	</html>`)

	// Load the HTML document
	doc, err := goquery.NewDocumentFromReader(r)
	if err != nil {
		log.Fatal(err)
	}

	e := doc.Find("html")
	html, err := e.Html()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(html)
	html = strings.Replace(html, "some page content", "replaced content", 1)
	fmt.Println("\n-----------\n")
	e.SetHtml(html)
	fmt.Println(doc.Html())
}

```

I get the following output:

```
<head></head>
	<body>
		<p>
			some page content
		</p>

	</body>

-----------

<!DOCTYPE html><html>

		<p>
			replaced content
		</p>

	</html> <nil>
```

It seems that when giving the "html" selection some new HTML, both head and body tags are missing. 

I understand that this may not be the regular way to do something like this with the goquery pakage, but just looking for an explanation as to why `<head>` and `<body>` tags are missing in the final output.

Thanks

**Comment by mna** [comment]
Hello Jack,

When using `SetHtml`, the provided html string must be parsed in a valid context, and goquery uses a generic `Element` node context, for which a `head` is not valid. I believe this is why you see this behaviour.

But in any case, if all you want to do is replace some inner text of a node, you should `SetText`:

```
	e := doc.Find("p")
	html, err := e.Html()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(html)
	e.SetText("replaced content")
	fmt.Println("\n-----------\n")
	fmt.Println(doc.Html())
```

Or if you really want to replace it with actual html markup, then `SetHtml` is still the one to use, but you should first find the closest node(s) that contain what you want to replace, instead of replacing the whole html.

Hope this helps!
Martin

**Comment by jackmiller334** [comment]
Hi Martin. Many thanks for your reply. 

My use case is a bit unusual as I also need to do replace any text inside <html> tags too. Maybe I could run through every node to check? 

For each node: 
Check node tag contents, for example <p class="replace-me">
Check node inner contents, for example, <p>replace-me</p>

**Comment by mna** [comment]
If it's all `<p>`s, you can select them all with `doc.Find("p")` and then loop over all and check whether there's some text to replace? Also, `SetText` will change the text for all matches in the selection, in case that's useful for you (i.e. if you want to replace them all with the same text).
