### ISSUE TITLE
nodes.find(" > a"), Can't start with >?

### ISSUE THREAD

**Issue by herozzm** [PuerkitoBio/goquery#289]
html
```html
<html>
<body>
 <p>
  <span>1</span>
  <span><a>2</a></span>
  <a>3</a>
 <p>
</body>
</html>
```
go
```go
nodes := doc.Find("p")
//some codes, nodes logic ...
nodes.Find(" > a") //I need return "<a>3</a>", But Find failure, Can't start with >?
```

**Comment by mna** [comment]
Hello,

Looks like this is a limitation CSS selectors, running the same selector with `document.querySelectorAll` in a browser gives the same error, and `cascadia`, the CSS selector package used by goquery, is based on that spec. That being said, it works in `jquery`, so if anyone is interested in implementing a well-tested PR that adds this feature, I'd consider adding support for this.

Martin

**Comment by herozzm** [comment]
thanks
