### ISSUE TITLE
How Find Is Case-insensitive(Find函数如何不区分大小写查找)

### ISSUE THREAD

**Issue by r1chb0ss** [PuerkitoBio/goquery#290]
HTML1
`
<meta name="keywords" content="123"/>
`

HTML2(K is uppercase)
`
<meta name="Keywords" content="123"/>
`

If I use this code, I can't find HTML2
`
doc.FInd("meta[name='keywords']")
`

How to find both HTML1 and HTML2?

**Comment by mna** [comment]
Looks like CSS selectors are case-sensitive, though a case-insensitive form is coming/is available. Haven't tried it in goquery, not sure if cascadia (the CSS selector package used by goquery) supports it, let me know if you do try it!

**Comment by r1chb0ss** [comment]
> Looks like CSS selectors are case-sensitive, though a case-insensitive form is coming/is available. Haven't tried it in goquery, not sure if cascadia (the CSS selector package used by goquery) supports it, let me know if you do try it!
> 
> https://stackoverflow.com/questions/7559205/are-css-selectors-case-sensitive/26721673#26721673

`doc.Find("meta[name='keywords' i]")`
no match

**Comment by kinoute** [comment]
Any news on this? Ignore case in CSS selectors will be awesome (I'm using GoQuery through Colly)

**Comment by mna** [comment]
This is not something that is done in goquery, css selectors are handled by the cascadia package. The author mentioned interest in receiving PRs that implement CSS4 features: https://github.com/andybalholm/cascadia/issues/49.

**Comment by kinoute** [comment]
@mna Good news, the feature was just merged in Cascadia: https://github.com/andybalholm/cascadia/pull/51

**Comment by mna** [comment]
Génial, merci pour l'info!
