### ISSUE TITLE
The resulting collection from .Add() is not sorted in document order

### ISSUE THREAD

**Issue by kidlj** [PuerkitoBio/goquery#293]
According to jQuery [api doc of .add()](https://api.jquery.com/add/):

>Do not assume that this method appends the elements to the existing collection in the order they are passed to the .add() method. When all elements are members of the same document, the resulting collection from .add() will be sorted in document order; that is, in order of each element's appearance in the document. If the collection consists of elements from different documents or ones not in any document, the sort order is undefined. To create a jQuery object with elements in a well-defined order and without sorting overhead, use the $(array_of_DOM_elements) signature.

Here are the tests:

1. With cheerio-1.0.0-rc.3 (the Node.js equivalent  of jQuery)

```
const cheerio = require("cheerio")
const $ = cheerio.load(`
<p>a paragraph</p>
<ul>
  <li>list item 1</li>
  <li>list item 2</li>
  <li>list item 3</li>
</ul>
<p>another paragraph with <a href="http://kidlj.com">a link</a></p>
`)

$li = $('li').add('p')
console.log($.html($li))
```

Output(formatted):

```
<p>a paragraph</p>
<li>list item 1</li>
<li>list item 2</li>
<li>list item 3</li>
<p>another paragraph with <a href="http://kidlj.com">a link</a></p>
```

2. With Goquery:

```
func ExampleAdd() {
	// Load the HTML document
	dom := `
	<p>a paragraph</p>
	<ul>
		<li>list item 1</li>
		<li>list item 2</li>
		<li>list item 3</li>
	</ul>
	<p>another paragraph with <a href="http://kidlj.com">a link</a></p>
	`
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(dom))
	if err != nil {
		log.Fatal(err)
	}
	sel := doc.Find("li").Add("p")

	wrapper := `<html><head><meta charset="utf-8"></head><body></body></html>`
	new, _ := goquery.NewDocumentFromReader(strings.NewReader(wrapper))
	new.Find("body").AppendSelection(sel)

	html, err := new.Html()
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(html)
}
```

Output(formatted):

```
<html>

<head>
  <meta charset="utf-8" />
</head>

<body>
  <li>list item 1</li>
  <li>list item 2</li>
  <li>list item 3</li>
  <p>a paragraph</p>
  <p>another paragraph with <a href="http://kidlj.com">a link</a></p>
</body>

</html>
```

**Comment by mna** [comment]
Hello,

This is the documentation from jQuery, not from goquery, which doesn't make any such guarantees about ordering. If having the same behaviour in that is something you care strongly about, I wouldn't mind reviewing a PR that would make them behave the same, although note that in your specific example, you do add nodes from two different documents, which in jQuery is undefined.

Martin

**Comment by kidlj** [comment]
> although note that in your specific example, you do add nodes from two different documents, which in jQuery is undefined.

IThe `Add()` is happening in the same document. The later `.AppendSelection()` operates on two different documents.

Btw, is there any advice/idea for rendering the current selection's Dom tree(outputs like the above example) without loading a new document? Thanks.

**Comment by mna** [comment]
> The Add() is happening in the same document.

Oh right, I missed that.

> is there any advice/idea for rendering the current selection's Dom tree

I think you're looking for `OuterHtml` (https://godoc.org/github.com/PuerkitoBio/goquery#OuterHtml)?

**Comment by mna** [comment]
Closing due to performance issues of the PR.
