### ISSUE TITLE
How to use the .Not() function?

### ISSUE THREAD

**Issue by electronicous** [PuerkitoBio/goquery#295]
This is the HTML, I'm trying to not have the span tag's text appear.
![image](https://user-images.githubusercontent.com/45419292/58187408-fd797b80-7cb6-11e9-8a60-97dff1104873.png)

This is what I've tried 
`row.Find("td:nth-child(1) strong:nth-hild(2)").Not("span.word__category").Text()`
`row.Find("td:nth-child(1) strong:nth-child(2)").NotSelection(row.Find("span.word__category")).Text()`

It finds the strong tag but doesn't remove the contents of the span tag so it remains the same as on the page.

**Comment by electronicous** [comment]
I solved it by getting the element's text and removing it with the `strings`'s module function, but would still like to know if this can be done some other way.

**Comment by mna** [comment]
There are different ways of doing this, basically the problem is that you have free text mixed with elements, and free text isn't targetable via css selectors. For this specific case, this would work:

```
var data = `
<html>
<body>
</body>
	<strong>
		letexte
		<span>pas lui</span>
	</strong>
</html>
`

func main() {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}
	txt := doc.Find("strong").Contents().FilterFunction(func(i int, s *goquery.Selection) bool {
		return !s.Is("span")
	}).Text()
	fmt.Println(txt)
}
```

**Comment by electronicous** [comment]
Thanks.
