### ISSUE TITLE
Function to get node own Text()

### ISSUE THREAD

**Issue by esrrhs** [PuerkitoBio/goquery#296]
// Text gets the combined text contents of each element in the set of matched
// elements, including their descendants.
func (s *Selection) Text() string {

is there has func OwnText() just get node own text, not including their descendants.

**Comment by mna** [comment]
Hello, 

There's no such function, you can use something like what was mentioned in #287 to isolate the text part of the element.

Hope this helps,
Martin

**Comment by esrrhs** [comment]
ok thanks
