### ISSUE TITLE
How to get <span> value

### ISSUE THREAD

**Issue by liusese** [PuerkitoBio/goquery#298]
![image](https://user-images.githubusercontent.com/19590382/60579937-b652d000-9db6-11e9-8c72-ae0accc8a5b3.png)

Which method can get a <span> element value? 
s.Find("span").Text()[Html()] can not get any?

![image](https://user-images.githubusercontent.com/19590382/60580142-1fd2de80-9db7-11e9-8f5e-93313345a5ff.png)

![Uploading image.png…]()

**Comment by mna** [comment]
Hello,

Looks like in your case `doc.Find("#todayweek").Text()` would do the trick. Using `Find("span").Text()` will get you the combined text of all spans in the document. Also, your document might not be properly formatted or the character set might not be utf-8 (it has to be).

If you can paste a simplified version of a working example of the code and html (text, not screen captures), I can try it out and point out what might be going on.

Martin

**Comment by davidAg9** [comment]
I have an issue where the value I want to get isn't in the span tag but beside it 
`   <span class="fas fa-user"></span> Published By <a href="mailto:ur@gctu.edu.gh"> University Relations Directorate</a> |
                            <span class="fas fa-calendar">  </span>     Monday October 3, 2022  |   <span class="fas fa-clock"></span> 2:27 pm`

how do I go about writing it
