### ISSUE TITLE
How to handle the comment?

### ISSUE THREAD

**Issue by surpassly** [PuerkitoBio/goquery#300]
```go
content := "<!--comment--><p></p><!--comment-->"
doc, _ := goquery.NewDocumentFromReader(strings.NewReader(content))
docHtml, _ := doc.Html()
fmt.Println(docHtml)
```
The output is:

`<!--comment--><html><head></head><body><p></p><!--comment--></body></html>`

Is there any way to put the first comment inside the `<body>`?

**Comment by mna** [comment]
Hello,

Not really. If you know that you have a body content, you can wrap it in an html-body tags before passing it to goquery.

Hope this helps,
Martin
