### ISSUE TITLE
can't get <image> attribute

### ISSUE THREAD

**Issue by orestonce** [PuerkitoBio/goquery#301]
I find the image tag, bug can't get the attribute of it.
````
package main

import (
	"github.com/PuerkitoBio/goquery"
	"strings"
	"fmt"
)

func main() {
	reader := strings.NewReader(`<html><image xlink:href="123">image text</image></html>`)
	doc, _ := goquery.NewDocumentFromReader(reader)
	fmt.Println(1, doc.Find(`image`).AttrOr(`xlink:href`, ``))

	reader = strings.NewReader(`<html><h2 xlink:href="123">image text</h2></html>`)
	doc, _ = goquery.NewDocumentFromReader(reader)
	fmt.Println(2, doc.Find(`h2`).AttrOr(`xlink:href`, ``))

	reader = strings.NewReader(`<html><image data-src="123">image text</image></html>`)
	doc, _ = goquery.NewDocumentFromReader(reader)
	fmt.Println(3, doc.Find(`image`).AttrOr(`data-src`, ``))
}

// output
// 1
// 2 123
// 3
````

**Comment by mna** [comment]
Hello,

That's because you're using an obsolete tag that gets automatically
converted to the correct `img` tag by the html5 parser (see
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/image).

If you use `img` instead, it works.

Hope this helps,
Martin

**Comment by orestonce** [comment]
Okay, thank you.

**Comment by orestonce** [comment]
So, can the selector automic convert the `<image>` tag to `<img>` ?

**Comment by mna** [comment]
It's not the selector, it's the parser that automatically converts it when `NewDocumentFromReader` is called. So from this point on, it is an `img` and must be selected using that name.
