### ISSUE TITLE
how to get a value out of elements?

### ISSUE THREAD

**Issue by godcong** [PuerkitoBio/goquery#302]
example:
```
<p class="mui-ellipsis">
<font class="colred">Element:</font> firstvalue
<font class="colred">Total:</font> secondvalue
</p>
```

if i want to get `firstvalue` and `secondvalue`
how to use in goquery?

**Comment by mna** [comment]
Hello,

You can see an approach to do that in #287 . 

Hope this helps!
Martin

**Comment by godcong** [comment]
thanks a lot.
