### ISSUE TITLE
Suggestion: Continuous Fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [PuerkitoBio/goquery#305]
Hi, I'm Yevgeny Pats Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- [go-fuzz](https://github.com/dvyukov/go-fuzz) fuzzers (This is generic step not-connected to fuzzit)
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [fuzzitdev/example-go](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [google/syzkaller](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Cheers,
Yevgeny

**Comment by mna** [comment]
Hey Yevgeny,

That's a really cool idea, super useful! For goquery itself, I don't think there'd be much benefit, as it only works with parsed nodes, it doesn't do any parsing directly, it uses net/html to parse html, and the cascadia package to parse the selector strings (this package might want that continuous fuzzing though!).

However, I have a package that could really benefit from this, pigeon, a PEG parser generator. I'm not the maintainer anymore, but I think it would make a lot of sense there and potentially help catch subtle bugs. If you haven't asked already, the repo is github.com/mna/pigeon.

Thanks!
Martin

**Comment by yevgenypats** [comment]
Hi @mna , Thanks for warm reply:) I would for sure ask there and mention you, thanks for the reference it seems like indeed a very good candidate for fuzzing.
