### ISSUE TITLE
Non displayed divs on screen don't have any child

### ISSUE THREAD

**Issue by muhammet-mucahit** [PuerkitoBio/goquery#306]
I am parsing html page from google search engine result page. There are 10 news as a carousel but I can access only the first three (Displayed news on screen). Why I cannot access to non-displayed items infos?

**Comment by mna** [comment]
Hello,

The page might be generated by javascript, in which case grabbing the html will not get the same document you see in the browser. Also note that google has an API for search results, which might be a better fit (https://developers.google.com/custom-search/v1/overview).

Hope this helps,
Martin

**Comment by muhammet-mucahit** [comment]
Okay thanks Martin I will try it and share my experience.

**Comment by muhammet-mucahit** [comment]
I tried your response but the Google API is a bit expensive and insufficient. I am trying to parse Google SERP and probably as you said, some elements generated by javascript that's why I can't access them. I can't see any solution other than Selenium to run scripts.

**Comment by mna** [comment]
Gotcha, ok. Regarding parsing pages with javascript, there are some tips as to how to use goquery with other tools to achieve that: https://github.com/PuerkitoBio/goquery/wiki/Tips-and-tricks#handle-javascript-based-pages. Note that those are community-provided, I haven't tried them myself.

Good luck with your project!
Martin
