### ISSUE TITLE
How to get class of <a> tag

### ISSUE THREAD

**Issue by LeMoussel** [PuerkitoBio/goquery#313]
Let's say I have this code:
```
<ul class="class1">
	<li>
		<a href="/upload">Upload</a>
	</li>
	<li class="class2">
		<a href="/data">Data</a>
	</li>
	<li>
		<a class="class3" href="/info">Info</a>
	</li>
</ul>
```

For each anchor link I want to extract href, text and the value of the class if present, if not the value of the parent class

**Result:**

> href: /upload
> text: Upload
> class: class1
> 
> href: /data
> text: Data
> class: class2
> 
> href: /info
> text: Info
> class: class3

I do this code
```
doc.Find("a").Each(func(i int, s *goquery.Selection) {
		href, ok := s.Attr("href")
		if ok {
			fmt.Printf("Link #%d:\nhref: %s\ntext: %s\nclass: %s\n", i, href,  s.Text(), "????")
		}
})

```
But I don't know how to get the value of the class if present, if not the value of the parent class

**Comment by mna** [comment]
Bonjour,

Something like that would work regardless of the structure of the document. It could get a bit slow on deeply nested structures without a class attribute, though, you may want to limit the number of parents you look at if you process arbitrary html documents.

```
var data = `
<body class="class0">
	<ul class="class1">
		<li>
			<a href="/upload">Upload</a>
		</li>
		<li class="class2">
			<a href="/data">Data</a>
		</li>
		<li>
			<a class="class3" href="/info">Info</a>
		</li>
	</ul>
	<div>
		<a href="/home">Home</a>
	</div>
</body>
`

func main() {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}

	doc.Find("a").Each(func(i int, s *goquery.Selection) {
		href, ok := s.Attr("href")
		if ok {
			classes, ok := s.Attr("class")
			if !ok {
				for p := s.Parent(); p.Size() > 0 && !ok; p = p.Parent() {
					classes, ok = p.Attr("class")
				}
			}
			fmt.Printf("Link #%d:\nhref: %s\ntext: %s\nclass: %s\n\n", i, href, s.Text(), classes)
		}
	})
}
```

Hope this helps,
Martin

**Comment by LeMoussel** [comment]
Bonjour Martin,

It helped me a lot (I'm starting with GoQuery)
Thank you for your help.
