### ISSUE TITLE
rendered pages

### ISSUE THREAD

**Issue by LucaPaterlini** [PuerkitoBio/goquery#314]
hello,
is there a method that allows the rendering of the page before starting to parse it?
something similar to phantomJs or https://github.com/chromedp/chromedp
just for the rendering of the page, I mean all the tags and attributes added at loading time of the page.

My understanding is that the default settings of goquery is allowing to parse only the plain HTML source code.

**Comment by mna** [comment]
Hello,

There is no such method as that is not something goquery itself should provide, there are various options to parse javascript-generated pages, you can find some in the community-provided wiki: https://github.com/PuerkitoBio/goquery/wiki/Tips-and-tricks#handle-javascript-based-pages.

Hope this helps,
Martin

**Comment by LucaPaterlini** [comment]
thanks for the suggestions, 
after googling a bit more I find out this one.
https://github.com/geziyor/geziyor#making-js-rendered-requests

**Comment by mna** [comment]
Oh nice! I didn't know about this project, it uses goquery to query the document. I'll add it to the list of related projects of goquery.
