### ISSUE TITLE
`text` Non-html formats are filtered

### ISSUE THREAD

**Issue by wazidw** [PuerkitoBio/goquery#315]
For example, xml format can't use text()
```
<?xml version="1.0" encoding= "UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans">
xxxx
</beans>
```

The results：
```
xxxx
```

**Comment by mna** [comment]
Hello,

Goquery is an html parser (it uses the `net/html` html5 parser internally), it doesn't parse arbitrary xml. You can use the stdlib's `xml` package for that or I know there are some userland packages that support xpath and more specific xml features.

Martin
