### ISSUE TITLE
how to find div without class?

### ISSUE THREAD

**Issue by zychappy** [PuerkitoBio/goquery#316]
if there is only style in div like below,how to locate this div?
```
<div style="font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1.6;text-align:left;color:#aaaaaa;">zyc</div>
```

**Comment by mna** [comment]
Hello,

If that's the only div with a style, you can isolate it like that:

```
var data = `
<html>
<body>
	<div style="font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1.6;text-align:left;color:#aaaaaa;">zyc</div>
	<div>other</div>
</body>
`

func main() {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}
	doc.Find("div[style]").Each(func(i int, s *goquery.Selection) {
		fmt.Println(goquery.OuterHtml(s))
	})
}
```

If it has a stable index in the list of divs, you can use `doc.Find("div").Eq(index)`. Basically, you have to find a way to identify the div with your selector. If there's no way to tell it apart from other divs, there's not much goquery can do to help.

Martin
