### ISSUE TITLE
Fails with has and direct child selector

### ISSUE THREAD

**Issue by ViRb3** [PuerkitoBio/goquery#318]
## Problem
Goquery seems to fail with the `has` psudo-class and a direct child selector

## [From MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:has)
>The following selector matches only <a> elements that directly contain an <img> child:
> `a:has(> img)`

## goquery implementation
```go
package main

import (
	"fmt"
	"strings"

	"github.com/PuerkitoBio/goquery"
)

func main() {
	html := `<html><a><img></img></a></html>`
	doc, _ := goquery.NewDocumentFromReader(strings.NewReader(html))
	fmt.Println(doc.Find("a:has(> img)").Length())
}
```
### Result
Results in 0, while it should be 1
### Playground
https://goplay.space/#BgCuFU-aVvr

**Comment by mna** [comment]
Hello Victor, 

The selector engine used by goquery is cascadia (https://github.com/andybalholm/cascadia), you may want to try this directly with it and see if it is supported (I'm not sure offhand). You can check / ask on this repo if there seems to be an issue.

Martin

**Comment by ViRb3** [comment]
Indeed, the problem is in Cascadia. I have opened an issue there: https://github.com/andybalholm/cascadia/issues/43. Can we keep this open in case Cascadia gets the feature and a dependency update is required?

**Comment by ViRb3** [comment]
Also somewhat off-topic, but is there a way to achieve what I want with the current goquery/cascadia? I am trying to find an element that has specific _direct_ children.

**Comment by mna** [comment]
Something like this should work:

```
func main() {
	html := `<html><a class="a1"><img></img></a><a class="a2"></a><a class="a3"><img></img></a></html>`
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(html))
	if err != nil {
		log.Fatal(err)
	}

	doc.Find("a > img").Parent().Each(func(i int, s *goquery.Selection) {
		h, _ := goquery.OuterHtml(s)
		fmt.Printf("%d:\n%s\n\n", i, h)
	})
}
```

**Comment by ViRb3** [comment]
The problem is in a more complicated case you may have a node which you cannot express in a single global query, and you may want to find its _direct_ children which have a matching structure. I ended up doing the following and it works, but if there's a better way please let me know:
```go
elem.
	ChildrenFiltered("nav").
	ChildrenFiltered("ul").
	ChildrenFiltered("li").
	ChildrenFiltered(".category").
		Parent()
```

Cascadia's developer responded to the issue and said that state/context is out of scope of the library.

**Comment by mna** [comment]
Gotcha, thanks for the info. That's not something I plan on implementing, I'll close this.
