### ISSUE TITLE
Feature request: ReplaceFunction

### ISSUE THREAD

**Issue by skuzzymiglet** [PuerkitoBio/goquery#319]
I'd like to be able to replace each selection node according to a `func` which would change `Node` properties:

`Selection.ReplaceFunction(f func(Node) Node) *Selection`

**Comment by mna** [comment]
Hello,

Note that there's already `ReplaceWithNodes` that makes this possible either as a replace every item in the selection with the same nodes, or replace each item with different nodes if you run this in an `Each` loop. https://godoc.org/github.com/PuerkitoBio/goquery#Selection.ReplaceWithNodes

That said, I'd be open to add a `ReplaceWithFunction` that would mimic jquery's behaviour: https://api.jquery.com/replaceWith/ 

If anyone is interested in working on this.

Martin

**Comment by mna** [comment]
There doesn't seem to be much interest in tackling this, closing for now, but a PR implementing such feature would be considered.
