### ISSUE TITLE
support sibling selector

### ISSUE THREAD

**Issue by axetroy** [PuerkitoBio/goquery#320]
```html
<style type="text/css">
    h1 + p {
        margin-top:50px;
        color:red;
    }
</style>
<p>This is paragraph.</p>
<h1>This is a heading.</h1>
<p>This is paragraph.</p>
<p>This is paragraph.</p>
```

**Comment by mna** [comment]
Hello,

Please provide a minimal, complete and reproducible example that illustrates the issue you're having (in the spirit of https://stackoverflow.com/help/minimal-reproducible-example), I don't understand the issue you're raising with just this excerpt.

Thanks,
Martin

**Comment by mna** [comment]
Bump.

**Comment by axetroy** [comment]
@mna 

I mean support `sibling selector` like `jQuery/css` did for document finder.

This is useful for some situations

```go
  // Load the HTML document
  doc, err := goquery.NewDocumentFromReader(res.Body)
  if err != nil {
    log.Fatal(err)
  }

  // Find the review items
  doc.Find("h1 + p").Each(func(i int, s *goquery.Selection) {
    // For each item found, get the band and title
  })
```

**Comment by mna** [comment]
Gotcha, the selector engine used by goquery is cascadia, that should be discussed on that project's repo (see https://github.com/PuerkitoBio/goquery/issues/318#issuecomment-573046983). I'm not sure if the author will be interested in adding support for this, though.
