### ISSUE TITLE
how find node by attribute?

### ISSUE THREAD

**Issue by xilu0** [PuerkitoBio/goquery#326]
for example:
<a href="/contributors" `data-hovercard-type="contributors">contributors</a>`
I want to find the node by  attribute data-hovercard-type.
who tell me, thank you very much!

**Comment by mna** [comment]
Hello, 

This is the syntax to select by attribute: https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors

Note that cascadia, the selector package used by goquery, may not support all syntax.

Hope this helps,
Martin
