### ISSUE TITLE
Creates document from openwrt firmware without error

### ISSUE THREAD

**Issue by edwvee** [PuerkitoBio/goquery#327]
Creates *goquery.Document from a file with openwrt firmware with no error and even finds there h3 tag.
Working example in my repository (just "go run main go"):
https://github.com/edwvee/goquery_bug_example
Link to the code:
https://github.com/edwvee/goquery_bug_example/blob/master/main.go

**Comment by mna** [comment]
What is the issue exactly? The parser is an html5 parse, which is very lenient and tries very hard to accept and fix incorrect html files, so that's quite likely what is going on here.

**Comment by edwvee** [comment]
So how should I get whether it is html or not? Is there any way to get type of document from goquery?
Such cases create a big amount of useless data in my app. 
"tries very hard to accept and fix incorrect html files," - that works fine when it's html.

**Comment by guidog** [comment]
It's completely up to you to determine if you should feed a file to goquery or not.
goquery assumes you're using it for the intended purpose.

**Comment by mna** [comment]
Goquery is a package to manipulate html documents, it is not the parser itself - it uses `golang.org/x/net/html` which is the html5 parser I mentioned. As Guido mentions, if you don't know what data you're feeding to goquery, you should do that check before calling goquery, that's not its purpose to validate the input (and I don't believe that's something even the html parser provides).

If you know that the documents you process need to be complete are relatively-correct html documents, you can check for a `<doctype>` node at the start (perhaps after a BOM marker) or an `<html>` element. For a slightly more powerful approach (but still heuristics-based) you can use https://golang.org/pkg/net/http/#DetectContentType.

Hope this helps,
Martin

**Comment by edwvee** [comment]
Thank you. However, it would be good mentioning that goquery doesn't care about data's content type.
