### ISSUE TITLE
It doesn't work when there's more than one class value in a class property delimited by a space.

### ISSUE THREAD

**Issue by hyp530** [PuerkitoBio/goquery#33]
...

**Comment by GreenRaccoon23** [comment]
I'm trying to figure this out too. If an html tag's class's value has a space in it, is there a way to search for it with `Find()`?

**Comment by PuerkitoBio** [comment]
This means that there are multiple classes on the tag. You can select on multiple classes with the ".class1.class2" notation.

**Comment by GreenRaccoon23** [comment]
Awesome! Thanks so much! And thanks for creating such a phenomenal package for us!

**Comment by PuerkitoBio** [comment]
You're welcome! Glad you like it :)
