### ISSUE TITLE
How to parse empty tags

### ISSUE THREAD

**Issue by bohrasankalp** [PuerkitoBio/goquery#331]
How would we remove empty tags recursively, any example?

like my HTML
```html
<article>
    <div></div>
    <p>
        <br/>\n</p>\n\t
    <p><span></span></p>
</article>
```

How would I remove tags in some cases I have `\n` or `\t` I need to strip that as well.
1. Stripping all `\n` so that tag would become empty.
2. If it is empty its parent would also be empty, that also needs to be strip recursively.

**Comment by mna** [comment]
This is very inefficient, but this would work:

```
var data = `
<html>
  <body>
    <article>
      <div></div>
      <p> <br/>
      </p>
      <p> <span> </span> </p>
      <div>content</div>
    </article>
  </body>
</html>`

func main() {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}

	els := doc.Find("*")
	els.Each(func(i int, s *goquery.Selection) {
		if txt := s.Text(); strings.TrimSpace(txt) == "" {
			s.Remove()
		}
	})

	h, _ := goquery.OuterHtml(doc.Selection)
	fmt.Println(h)
}
```

It selects all elements and removes each one that has only whitespace text in it. I wouldn't use this for anything serious, though, it would be much more efficient (but a bit more complex) to use the `net/html` parser directly and walk the tree of nodes.

Hope this helps,
Martin

**Comment by bohrasankalp** [comment]
I consider as an enhancement, the option should be there to find empty tags.
