### ISSUE TITLE
Multiple tabs between HTML tags confuse GoQuery

### ISSUE THREAD

**Issue by olegkrutikov** [PuerkitoBio/goquery#333]
The HTML code to parse was like this:

```html
<div id="photos">
<ul>
    /n/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t<li>stuff</li>
    /n/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t<li>stuff</li>
    /n/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t<li>stuff</li>
    /n/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t<li>stuff</li>
</ul>
</div>
```

< ul > is supposed to have 4 children li tags here (e.DOM.Find("div[id=photos]").Find("ul")), but it only "finds" children like "/n/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t/t" of various lengths (and it is shorter that the actual number of tabs in code)

e.DOM.Find("div[id=photos]").Find("ul").Find("li") finds nothing at all as a result

I had to first put the page through a proxy script to delete all the tabs (but not the new lines, just forgot them), then e.DOM.Find("div[id=photos]").Find("ul").Find("li") worked as expected (found 4 li tags)

UPD: corrected the closing tag in "photos"

**Comment by olegkrutikov** [comment]
Here it is in the debugger:
![screenshot](http://dl4.joxi.net/drive/2020/05/03/0009/3845/638725/25/4b85541a2c.jpg)

**Comment by mna** [comment]
Note that you are missing a closing quote in `div id="photos`.

**Comment by mna** [comment]
Also, is that meant to be newlines and tabs escapes? Because you used forward slashes instead of backslashes, please make sure the html example is exactly the source that causes the issue.

**Comment by mna** [comment]
For example, this code correctly selects and prints all 4 `li`s in the html (which are separated from the ul with newlines and tabs):

```
var data = `
<html>
<body>
  <div id="photos">
    <ul>
			<li>stuff1</li>
 			<li>stuff2</li>
			<li>stuff3</li>
			<li>stuff4</li>
    </ul>
  </div>
</body>
</html>
`

func main() {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}
	sel := doc.Find("div[id=photos]").Find("ul").Find("li")
	sel.Each(func(i int, s *goquery.Selection) {
		h, err := goquery.OuterHtml(s)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println(h)
	})
}
```

**Comment by olegkrutikov** [comment]
Sorry, those are all my mistakes when reproducing the example (tried to simplify). The code that I actually parsed had all tags closed and slashes the right way.

Here it is in the playground (not working as expected) - https://play.golang.org/p/Cl7jTc7m60L

**Comment by olegkrutikov** [comment]
Cannot reproduce the error in the same code I had initially problems with in my project (though I did not "fix" anything), so I guess I messed up somehow, sorry

**Comment by mna** [comment]
No problem, have fun with your project!
