### ISSUE TITLE
what's wrong with the selector for <a class>?

### ISSUE THREAD

**Issue by guest6379** [PuerkitoBio/goquery#334]
Hi 
If the html given like below:
```html
...
<a class="c1" href="hello.php?id=1">hello1</a>
<a class="c1" href="hello.php?id=2">hello2</a>
<a class="c1" href="hello.php?id=3">hello3</a>

<a class="d1 c1" href="hello.php?id=1">hello</a>
...
```

golang code shown as below:
```golang
...
n := len(doc.Find("a.d1.c1").Nodes)
fmt.Println(n) // print 1, which is my expectation

n := len(doc.Find("a.c1").Nodes)
// why this print 4 ? I expect print 3, because there are only 3 a with class="c1"
fmt.Println(n)  
...

```

Thank you in advance.

**Comment by mna** [comment]
Hello,

All 4 `<a>` anchors have the "c1" class in your example, so it is correct that it selects all 4 (the last one has classes "d1" AND "c1").  Note that you can use `doc.Find("a.c1").Length()` to get the number of elements in the selection.

Martin

**Comment by guest6379** [comment]
> Hello,
> 
> All 4 `<a>` anchors have the "c1" class in your example, so it is correct that it selects all 4 (the last one has classes "d1" AND "c1"). Note that you can use `doc.Find("a.c1").Length()` to get the number of elements in the selection.
> 
> Martin

I got it, thank you for the quick respond. 
But, how can I write to only select the only 3 <a> anchors with class="c1" ?? In short, I need to select exactly the class="c1"  elements.

**Comment by mna** [comment]
`doc.Find("a[class='c1']")` but note that this will fail if the class attribute has any whitespace before or after "c1" (that is, it matches exactly the string, so it is not very robust).
