### ISSUE TITLE
Text find and replace?

### ISSUE THREAD

**Issue by austincollinpena** [PuerkitoBio/goquery#339]
I'm looking to achieve a find and replace functionality with this library and am wondering if that is possible. 

I of course could use ```doc.Find("p")``` and target other common text nodes, but it isn't a guarantee that text nodes will exist inside of the proper tag. 

Where should I start to get this done? When I run:

```go
// Data to look through
var easyData = `
<p>Goodbye</p>
<p>Hello</p>
`

s := doc.Find("*")
s.Contents().Each(func(i int, s *goquery.Selection){
	if strings.Contains(s.Text(), "Hello"){
		s.SetText("changed")
	}
})
htmlResult, _ := doc.Html()
```

My result is (as you could guess):

```html
<html><head></head><body>changed</body></html>
```

**Comment by mna** [comment]
Yeah it's probably not the best tool for this job, it works very well with elements but not so much with text and other non-element  nodes. For something like that I'd probably just walk the raw `html.Node` tree (i.e. use the `text/html` package directly - https://pkg.go.dev/golang.org/x/net/html?tab=doc).

**Comment by austincollinpena** [comment]
Thanks mna!

I actually wrote an implementation where I manually ensure I'm not messing with anything within HTML tags or inside <script> / <style> tags. Do you have any insight as to why I would use the package vs just modifying the byte array?

**Comment by mna** [comment]
Just to make sure you don't overwrite text that isn't actually a text node, as you mention there are a lot of cases to watch out for (attributes, scripts, styles, comments) and the html5 parser is very lenient and will reorganize nodes as required, e.g. if closing tags are missing, it tries hard to make sense of any malformed html so it is very tricky (well, impossible) to do this without a full parser. If you can live with a few false positives that replaces text that wouldn't be actual text nodes, then of course feel free to process the byte array manually.

**Comment by austincollinpena** [comment]
Your point about malformed HTML is well taken.
