### ISSUE TITLE
goquery Find method not compatibe with jQuery

### ISSUE THREAD

**Issue by taitelman** [PuerkitoBio/goquery#349]
I tried several jQuery search queries in the browser. 
For a jQueryt hat returns 5 results :  goQuery :  0 results. (same css selector string)
it seems goQuery is good at finding only simple css selector. Not nested selector like ``` a > b.ins.pro > c  ``` or anything complex.
I suggest changing the README and remove the link to jQuery.
goQuery is not really compatible with jQuery even if the lib name sounds the same. 
it might confuse users.
with goQuery you need to work hard to drill into the DOM structure .

**Comment by mna** [comment]
Hello,

> it seems goQuery is good at finding only simple css selector. Not nested selector like a > b.ins.pro > c or anything complex.

Sure it does:

```
const data = `
<html>
  <head>
  </head>
  <body>
    <div>
      <p class="ins">
        <span>A</span>
      </p>
      <p class="pro">
        <span>B</span>
      </p>
      <p class="ins pro">
        <span>C</span>
      </p>
    </div>
  </body>
</html>
`

func main() {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}
	doc.Find("div > p.ins.pro > span").Each(func(i int, s *goquery.Selection) {
		fmt.Println(i, s.Text())
	})
}
// prints: 0 C
```

I don't know where you've seen that goquery was _compatible_ with jQuery, here's what the README says:

> goquery brings a syntax and a set of features similar to jQuery to the Go language

What you may have seen, although it's hard to tell given the lack of details in your issue, is that the document you query with jQuery is actually modified via javascript, so when run in the browser, it has a different set of nodes (different html) than what you give to goquery (which only gets the static html source). See https://github.com/PuerkitoBio/goquery/wiki/Tips-and-tricks#handle-javascript-based-pages for community-provided options to handle this.

As for the Find method and the selector support, as noted in the README, goquery relies on the cascadia package which handles a pretty large number of complex selectors, but not necessarily all those supported by jQuery's sizzle selector library.
 
Martin
