### ISSUE TITLE
":contains" selector sometimes returns all parents instead of one

### ISSUE THREAD

**Issue by juliensalinas** [PuerkitoBio/goquery#350]
Hello team,

I've been using Goquery for several years and I love it, thanks for the good work!
For the first time I'm running into an issue I'm unable to solve though...

I'm trying to retrieve the surrounding element around some text.
So I'm using the `:contains` selector. But the latter seems to behave weirdly and sometimes selects all the parent elements instead the first parent only. It even sometimes invents elements...

Let me give you an example.

```go
html := "<html><body><div>Julien, Developer</div><div>Martin, Developer</div></body></html>"
doc, _ := goquery.NewDocumentFromReader(strings.NewReader(html))
doc.Find(":contains('Developer')").Each(func(j int, s *goquery.Selection) {
    fmt.Println(goquery.NodeName(s))
}
```

The above returns:
```
html
body
div
#text
div
#text
```

While it should return:
```
div
div
```

Do you know if there's a way to bypass this weird behaviour?
Can you think of a better way to look for some text and then return the surrounding element?

Thank you very much!

EDIT: I think I would need a way to refine searches by text content, like Beautifulsoup does in Python, but not sure it's supported by Goquery: https://stackoverflow.com/questions/9007653/how-to-find-tag-with-particular-text-with-beautiful-soup/13348425

**Comment by mna** [comment]
Salut Julien,

I'm not super familiar with `:contains`, but shouldn't that be `containsOwn`? I.e. the following (slightly modified) code does what you want:

```
func main() {
	const html = "<html><body><div>Julien, Developer</div><div>Martin, Developer</div></body></html>"
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(html))
	if err != nil {
		log.Fatal(err)
	}
	doc.Find(":containsOwn('Developer')").Each(func(i int, s *goquery.Selection) {
		fmt.Println(i, goquery.NodeName(s), s.Text())
	})
}

// prints 
// 0 div Julien, Developer
// 1 div Martin, Developer
```

I think `:contains` returns all nodes that contain that text, so every node does?

Hope this helps,
Martin

**Comment by mna** [comment]
Oh, looks like `:containsOwn` is not even a jQuery selector, but a jsoup one, that somehow cascadia (the selector package used by goquery) decided to support. See https://jsoup.org/apidocs/org/jsoup/select/Selector.html

But yeah, from what I read, it seems like `:contains` behaves as expected.

**Comment by juliensalinas** [comment]
Merci Martin !

Indeed `:containsOwn` perfectly works. Sorry I did not look into Cascadia's docs, but I will from now on.

Thanks again Martin ;)
