### ISSUE TITLE
Inconsistent results using doc.find() 

### ISSUE THREAD

**Issue by Neguhs** [PuerkitoBio/goquery#352]
For some reason doc.find() is able to detect an element but after trying consecutive tries it doesn't work 99% of the time

**Comment by mna** [comment]
Hello,

Can you please provide a minimal, runnable example (with the html data) to reproduce the issue, with logs of what it prints when it doesn't work?

Thanks,
Martin

**Comment by roachadam** [comment]
This is also happening to me for no apparent reason. will update with example if I get the chance
