### ISSUE TITLE
No way to get first decendents

### ISSUE THREAD

**Issue by sooxt98** [PuerkitoBio/goquery#353]
``` html
<div>
    <div>
        <p><a>1</a></p>
    </div>
    <p><a>2</a></p>
    <p><a>3</a></p>
</div>
```

Find("div > p > a").Each always return 1,2,3 instead of 2,3

**Comment by mna** [comment]
This is correct, as `<a>1</a>` is also directly under a `p` that is directly under a `div`. If you had for example this html:

```
<div>
    <h1>
        <p><a>1</a></p>
    </h1>
    <p><a>2</a></p>
    <p><a>3</a></p>
</div>
```

Then it would return only 2 and 3.

Martin

**Comment by sooxt98** [comment]
@mna so is it possible to only get 2,3 with that original html?

**Comment by sooxt98** [comment]
I think goquery is giving wrong result, this should work like https://stackoverflow.com/questions/977883/selecting-only-first-level-elements-in-jquery

**Comment by sooxt98** [comment]
Solved! https://stackoverflow.com/questions/977883/selecting-only-first-level-elements-in-jquery
