### ISSUE TITLE
fail to find id with $ sign 

### ISSUE THREAD

**Issue by sooxt98** [PuerkitoBio/goquery#354]
```html
<span id="blah$0">1</span>
```
`Find('#blah$0')` not working as expected, it just return empty

**Comment by mna** [comment]
The dollar sign is not a valid id character: https://stackoverflow.com/questions/448981/which-characters-are-valid-in-css-class-names-selectors

**Comment by sooxt98** [comment]
@mna hey thanks for the info, I can't imagine how a big Enterprise still using $$$ all around the site

**Comment by mna** [comment]
If you're stuck dealing with this, you can always use the attribute selector, as if id was just any other attribute:

```
doc.Find("[id='blah$0']")
```

Not sure of the performance of that, but at least you can get to that element.
