### ISSUE TITLE
Is it possible to get text after html tag?

### ISSUE THREAD

**Issue by sooxt98** [PuerkitoBio/goquery#355]
```html
<span></span>1
<span></span>2
<span></span>3
```

i want to get 1,2,3 out;

i tried with `doc.Contents().Each` it just return the whole text out at once

**Comment by mna** [comment]
Not directly with a selector, but see https://github.com/PuerkitoBio/goquery/issues/287 .

**Comment by sooxt98** [comment]
@mna i think goquery cant separate that example code into 6 chucks, it just return one big whole chunk with all the text inside ; so .Contents().Each is useless for me

**Comment by mna** [comment]
What do you mean? Did you try the example in the issue I linked?

```
const data = `
<div>
<span></span>1
<span></span>2
<span></span>3
</div>
`

func main() {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}
	doc.Find("div").Contents().Each(func(i int, s *goquery.Selection) {
		if goquery.NodeName(s) == "#text" {
			fmt.Printf(">>> (%d) >>> %s\n", i, s.Text())
		}
	})
}

// Prints:
// >>> (0) >>> 
// >>> (2) >>> 1
// >>> (4) >>> 2
// >>> (6) >>> 3
```

**Comment by sooxt98** [comment]
@mna please try not to wrap with parent div

**Comment by mna** [comment]
Just change the "div" selector (which obviously won't work) with "body".

**Comment by sooxt98** [comment]
Okay thanks, I think i might manually add the tag around it

**Comment by mna** [comment]
Oh you don't have to, if all you have is the three spans, when parsed with the net/html parser, it will automatically add the html/head/body tags to make it a proper document (the Go html parser uses the same logic as the official html5 parser unsed in browsers, so it tries hard to "fix" documents to make them valid). When in doubt, you should print the full html document after the call to `goquery.NewDocument...` (using `goquery.OuterHtml(doc.Selection)`).
