### ISSUE TITLE
WrapHtml documentation is not clear...

### ISSUE THREAD

**Issue by darkermatter** [PuerkitoBio/goquery#358]
Hi!

Currently the documentation for ```func (s *Selection) WrapHtml(htmlStr string) *Selection``` is:

> WrapHtml wraps each element in the set of matched elements inside the inner- most child of the given HTML.
> It returns the original set of elements.

It doesn't make clear that the ```htmlStr string``` should all be one line. I almost gave up when it started stripping elements out!

Maybe it would be good to run a ```strings.Join(htmlStr, "\n")``` in the function?

Thanks for a great tool!

**Comment by mna** [comment]
Hello,

Not sure what you mean by "one line", i.e. the following works as expected and has multiple lines:

```
const data = `
<html>
  <head>
  </head>
  <body>
    <p>
      <span>a</span>
      <span>b</span>
    </p>
    <p>
      <span>c</span>
    </p>
  </body>
</html>
`

func main() {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}
	sel := doc.Find("span")
	sel.WrapHtml("<div><p>\n</p>\n</div>")
	h, _ := goquery.OuterHtml(doc.Selection)
	fmt.Println(h)
}
```

I think maybe you mean that it has to be a single "branch" of nodes, i.e. it has to be rooted in a single top-level element, without siblings? That's indeed the case and I'd welcome a PR that made that clearer in the documentation.

Martin
