### ISSUE TITLE
Can't read text of a <span>

### ISSUE THREAD

**Issue by ecaglar** [PuerkitoBio/goquery#360]
I am trying to get text from a span

`<span id="product_SKU_44752" class="sku">SKU: 124356 </span>`

I can successfully get the span object however Text() returns empty. I can successfully get the text for other types but not for span.

This is the code I am using:

```
func visit(url string) {
	fmt.Println("Visiting: " + url)
	res, err := http.Get(url)
	if err != nil {
		log.Fatal(err)
	}

	defer res.Body.Close()
	if res.StatusCode != 200 {
		log.Fatalf("status code error: %d %s", res.StatusCode, res.Status)
	}
	doc, err := goquery.NewDocumentFromReader(res.Body)


	if err != nil {
		log.Fatal(err)
	}
	doc.Find(".sku").Each(func(i int, s *goquery.Selection) {
		fmt.Println("SKU is: " + s.Text())

	})
}
```

When I debug the code and Text() medhod, I see that Type is "TextNode" however Data shows as  "\n\t\t      \n\t            "
![image](https://user-images.githubusercontent.com/343758/100555956-cd1f7f80-3253-11eb-9373-e0a3b5dbbb79.png)

Any idea? Is it the doc structure that was not constructed correctly or there is another way to get a text from a span?

**Comment by mna** [comment]
Hello,

I guess the html or the code is not exactly what you provided, as this works as expected:

```
const data = `
<span id="product_SKU_44752" class="sku">SKU: 124356 </span>
`

func main() {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}
	txt := doc.Find(".sku").Text()
	fmt.Println(txt)
}

// Prints:
// SKU: 124356
```

Please provided a minimal yet complete runnable example of code + html that reproduces the issue.
Martin

**Comment by ecaglar** [comment]
Thanks @mna 

I have used [this URL](https://www.basspro.com/shop/en/federal-champion-brass-centerfire-handgun-ammo) to get SKU
As you can see there is a span with text **SKU: 3193780.**

_(Sorry I couldn't send the playground link as it does not support real network calls.)_
The minimal code is shown below: 

```
package main

import (
	"fmt"
	"github.com/PuerkitoBio/goquery"
	"net/http"
)

func main() {
	urlScrape := "https://www.basspro.com/shop/en/federal-champion-brass-centerfire-handgun-ammo"
	client := &http.Client{}
	req, _ := http.NewRequest("GET", urlScrape, nil)
	req.Header.Add("Accept", `text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`)
	req.Header.Add("User-Agent", `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11`)
	res, _ := client.Do(req)
	defer res.Body.Close()
	doc, _ := goquery.NewDocumentFromReader(res.Body)
	doc.Find("span.sku").Each(func(i int, selection *goquery.Selection) {
		fmt.Println("SKU found: " + selection.Text())
	})
}
```



**The output is:**

```
/private/var/folders/jr/2_y012z902lgt8c04cww83_80000gn/T/___go_build_StockMiner_main
SKU found: [
                        
                ]

Process finished with exit code 0
```
Thanks!

**Comment by vhodges** [comment]
Adding my .02...

When I look at the source for that page, there is no span with a class of sku.  The markup for the sku is

<div id="sku_3074457345620130797">SKU: 3193780</div>

Such is the danger of scaping.  There is a parent div with a class that might be easy to do a selector for, but the sku is the 3rd child of that parent.  Good luck!

**Comment by ecaglar** [comment]
Thanks @vhodges 

When I "inspect" the page I see the following span with class:

![image](https://user-images.githubusercontent.com/343758/100658227-8f7a2f80-3303-11eb-95f1-8e743ce2278c.png)

However If I "View Page Source" I see the tag without class as you comment

`<div id="sku_3074457345620130797">SKU: 3193780</div>
`

**In that case, the question is, which one should I depend on when scraping? "Inspect" or "View Page Source"?**

Thanks

**Comment by vhodges** [comment]
@ecaglar Sorry, I see what I did now.  I inspected the sku in the 'product chart'.  

However, try printing the document you get back. When I try to curl (even with a valid User-Agent) that url, I get an error back from the server "Permission denied" (not sure of the status code returned is - not enough curlfu)

**Comment by vhodges** [comment]
sorry @ecaglar I inspected the wrong thing.  I just curled the document (once I figured out how to pass a valid user-agent to curl :-/) and this is what I get for the span:

```
	<span id="product_SKU_3074457345620130194" class="sku">
		        
        </span>	
```

My guess is that the data is filled in by some piece of Javascript.

**Comment by mna** [comment]
Yeah, as Vince mentions, the page is probably modified by javascript. What you provide to goquery is the equivalent of "View Page Source", i.e. the original html document itself. There are a couple of community-provided tips in the wiki to get javascript-modified html to goquery, but I can't help you with that, I haven't used those tools: https://github.com/PuerkitoBio/goquery/wiki/Tips-and-tricks#handle-javascript-based-pages
