### ISSUE TITLE
Add stitcherd to related projects list

### ISSUE THREAD

**Issue by vhodges** [PuerkitoBio/goquery#361]
hi... my apologies if this is not the right way to do this!

I have been working on a project called stitcherd which is essentially a server for server side includes using css selectors and dom updates .  

From the home page:

"Stitcherd can automatically modify the element tree of a page before serving it to users. You can tell it where to insert new content using CSS selectors." 

Home page:  https://stitcherd.vhodges.dev/
Source: https://github.com/vhodges/stitcherd

**Comment by mna** [comment]
Hello Vince,

Awesome, yeah feel free to send a PR adding it to the README (you can just follow the formatting of the other ones), I'll make sure to get it merged quickly!

Thanks,
Martin

**Comment by vhodges** [comment]
Excellent, Thanks!

https://github.com/PuerkitoBio/goquery/pull/362
