### ISSUE TITLE
String to html goquery.Selection

### ISSUE THREAD

**Issue by Shynghys** [PuerkitoBio/goquery#363]
I parse table, then go for each table data, where one table cell has multiple values, i need to append them into slice separately. Firstly, i want to divide them(tablecell.Html() in ; using strings package Split method, then convert them again to to Html, so i could use methods such as Attr() and others.
My code:
example of table cell
```
<td>
(+1.0)
<u title="max. 2200 $" data-bc="vnxFBr_26qrv0709DJgv"
  ><a id="r3108_123_LNGcwR4LIUzTQbwE4f4o"
    ><i class="blank" id="-593193506">1.23</i></a
  ></u
>; (+1.5)
<u title="max. 2900 $" data-bc="jnhBCrO67qrv0709DJgv"
  ><a id="r3108_117_XKFL0W6.ygZ2rlFx^uVz"
    ><i class="blank" id="391917315">1.17</i></a
  ></u
>; (–1.0)
<u title="max. 95 $" data-bc="onMNzrgq4rrq460pzKgq"
  ><a id="r3108_625_^ZaU6FRhZ0YBFvtskCM6"
    ><i class="blank" id="271706906">6.25</i></a
  ></u
>;
</td>
```

```
rowhtml.Find("td").EachWithBreak(func(indextd int, tablecell *goquery.Selection) bool {
html := tablecell.Contents()
						
btbArr := strings.Split(tablecell.Html(), ";")
for i:=0;i<len(btbArr);i++{
id,_:=btbArr[i].Attr(id)
}
})
```

**Comment by mna** [comment]
Hello,

I don't understand exactly what you're trying to do, but you cannot call `Attr` on `btbArr[i]`as this is a string, not a `*goquery.Selection`. What is the id you want to get? Is it the id of the `<a>` element in the table cell? If so, you can use something like that (note that I assumed your html was actually well-formed, and the `<td>`s live in a `<table><tr>` as they should to be correctly parsed):

```
const data = `
<table>
  <tr>
    <td>
    (+1.0)
    <u title="max. 2200 $" data-bc="vnxFBr_26qrv0709DJgv"
      ><a id="r3108_123_LNGcwR4LIUzTQbwE4f4o"
        ><i class="blank" id="-593193506">1.23</i></a
      ></u
    >; (+1.5)
    <u title="max. 2900 $" data-bc="jnhBCrO67qrv0709DJgv"
      ><a id="r3108_117_XKFL0W6.ygZ2rlFx^uVz"
        ><i class="blank" id="391917315">1.17</i></a
      ></u
    >; (–1.0)
    <u title="max. 95 $" data-bc="onMNzrgq4rrq460pzKgq"
      ><a id="r3108_625_^ZaU6FRhZ0YBFvtskCM6"
        ><i class="blank" id="271706906">6.25</i></a
      ></u
    >;
    </td>
  </tr>
</table>
`

func main() {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}
	doc.Find("td a").Each(func(i int, s *goquery.Selection) {
		id, _ := s.Attr("id")
		fmt.Println(i, id)
	})
}
```

Hope this helps,
Martin

**Comment by Shynghys** [comment]
Yes, there is a table with table row and etc. I need something like a node that i can append to a slice. So for example
	values := make([]*goquery.Selection, 0)
        node := tablecell.Find("u")
		
 ```
       if len(node.Nodes) > 1 {
	values = append(values, node.First(), node.Last())
	} else {
	values = append(values, node.First())
        }
```
I need to wrap string back to html, so i could  use goquery method Attr() to get an id.

**Comment by Shynghys** [comment]
Well, i did what i wanted. Just parsed string then with strings Index method locate id and other things that i need.
