### ISSUE TITLE
Tree containing self-closing element misread

### ISSUE THREAD

**Issue by zzwx** [PuerkitoBio/goquery#365]
Hello,
I've been successfully using goquery for processing `xml` files so far, but recently bumped into a file that contains a self-closing element that somehow puzzles goquery (or underlying libraries). As soon as I either remove the element or convert it into a regular `<></>`, it works as expected. I'm hoping to get your input, or may be point me to the fact that goquery can't be used for such xml files and so I'll be looking for another solution (with great sadness).

https://github.com/zzwx-bug-reports/goquerypossiblebug

**Comment by mna** [comment]
Hello,

Indeed, unfortunately goquery is for html data only, it uses the net/html parser internally, which implements an html5 parser (https://godoc.org/golang.org/x/net/html). Parsing xml with it can definitely hit some issues.

Martin
