### ISSUE TITLE
Don't work ExampleScrape() from readme

### ISSUE THREAD

**Issue by 4n70w4** [PuerkitoBio/goquery#366]
Hi! Found nothing by selector `.sidebar-reviews article .content-block` on page http://metalsucks.net

https://github.com/PuerkitoBio/goquery/blame/master/README.md#L125

**Comment by mna** [comment]
Hi! Yeah it's possible they changed the structure of their web page, if you want to send a PR to fix it I'll be happy to merge this.

**Comment by j0nimost** [comment]
@mna  just made a PR for this
