### ISSUE TITLE
how to spider "javascripts:void;" in html?

### ISSUE THREAD

**Issue by 1978robin** [PuerkitoBio/goquery#368]

**Comment by mna** [comment]
If you mean to parse whatever popup or html generated by a javascript-based link, you can't do that directly with goquery. It is not a headless browser or a javascript execution environment, it only parses the html you provide to it in the call to `goquery.NewXxx...`. There are some community-provided examples of how you can parse javascript-generated pages in the wiki, which might help you: https://github.com/PuerkitoBio/goquery/wiki/Tips-and-tricks#handle-javascript-based-pages

Note that I can't help you with this though, I haven't used those patterns myself.

Martin

**Comment by 1978robin** [comment]
Thank you for your help. 发自我的华为手机-------- 原始邮件 --------发件人： Martin Angers <notifications@github.com>日期： 2021年1月5日周二 07:41收件人： PuerkitoBio/goquery <goquery@noreply.github.com>抄送： 1978robin <robin_liu1978@sina.com>, Author <author@noreply.github.com>主    题： Re: [PuerkitoBio/goquery] how to spider "javascripts:void;" in html? (#368)
If you mean to parse whatever popup or html generated by a javascript-based link, you can't do that directly with goquery. It is not a headless browser or a javascript execution environment, it only parses the html you provide to it in the call to goquery.NewXxx.... There are some community-provided examples of how you can parse javascript-generated pages in the wiki, which might help you: https://github.com/PuerkitoBio/goquery/wiki/Tips-and-tricks#handle-javascript-based-pages
Note that I can't help you with this though, I haven't used those patterns myself.
Martin
