### ISSUE TITLE
[Question] Is it possible to fetch text between two given nodes?

### ISSUE THREAD

**Issue by maxiride** [PuerkitoBio/goquery#369]
The library has been powerful! However, I am stuck on resolving a little caveat.

Given the below minimal example, how can I retrieve the text "Get me!"?
The given methods like .Text yields all the text in a given node, as shown here the first node `<span id="id1000">` might contain a lot of other parts of the document, however I can be certain it will end with the next `<h1>`.

    <span id="id1000">
    <h1 class="title">Title</h1>
     Get me!
    <br>
    <br>
    <h1 class="title"></h1>
    ... truncated
    </span>

**Comment by mna** [comment]
Hello Federico,

You're correct about the `Text()` method, that's how it works. There's no direct method to do what you want, but you can use the solution mentioned in #287 .

Hope this helps!
Martin

**Comment by maxiride** [comment]
Thanks, it somewhat worked but I am afraid the page I am trying to parse is simply badly written.
