### ISSUE TITLE
Reversed Each() / Reversed EachWithBreak()

### ISSUE THREAD

**Issue by mjheller** [PuerkitoBio/goquery#371]
Hi, Can you add the ability to iterate through the selections in reverse order?

     func (s *Selection) ReversedEach(f func(int, *Selection)) *Selection {
	
        for i:= len(s.Nodes) -1 ; i >=0; i-- {
		f(i, newSingleSelection(s.Nodes[i], s.document)){
			return s
		}
	    }
	     return s
     }

    func (s *Selection) ReversedEachWithBreak(f func(int, *Selection) bool) *Selection {

	    for i:= len(s.Nodes) -1 ; i >=0; i-- {
		if !f(i, newSingleSelection(s.Nodes[i], s.document)){
			return s
		}
	    }
	    return s
    }

**Comment by mna** [comment]
Hello,

There's no specific method for it, but you can easily get this behaviour with a standard for loop, see https://github.com/PuerkitoBio/goquery/issues/263#issuecomment-435030366

Hope this helps,
Martin
