### ISSUE TITLE
:nth-child  is required and necessary. Please consider adding it. Thanks

### ISSUE THREAD

**Issue by agclqq** [PuerkitoBio/goquery#372]
`:nth-child`  is often used in situations where there is no proper CSS selector. so `:nth-child` is very important. Please consider adding it. Thanks!

**Comment by mna** [comment]
Hello,

What is the problem you're having? Please provide a minimal, runnable example with code and data (html). Also see https://github.com/PuerkitoBio/goquery/issues/329 regarding :nth-child.

Martin

**Comment by agclqq** [comment]
I guess I didn't read the documentation properly. Thank you for solving my problem.  @mna 
haha
