### ISSUE TITLE
Are there any ways to find NodeId?

### ISSUE THREAD

**Issue by yigitkonur** [PuerkitoBio/goquery#376]
While parsing HTML, we also need to find NodeId like scraper.rs library does in Rust:

![image](https://user-images.githubusercontent.com/9989650/114894747-923f7200-9e17-11eb-815e-48346c308ea0.png)

Are there any way to find relevant NodeID info by using goquery?

**Comment by yigitkonur** [comment]
Actually, we need to find the position of parsed divs in HTML. It may be a line position or character position or even NodeId that can give us hints about the positions of parsed values.

**Comment by mna** [comment]
Hello Yiğit,

AFAIK the nodeid is not a "thing" i.e. not a dom property or anything, it looks like it's just an incrementing ID that the Rust library assigns to each node in the tree? It doesn't exist as-is in goquery, but if the actual value is not important, just that it is unique, then if you store a reference of the internal node (the `*html.Node` corresponding to a `goquery.Selection`), it gives you a "unique identity" for that node (and you can access all the other relevant tree items from that node, as per the `golang.org/x/net/html` package's API - https://pkg.go.dev/golang.org/x/net/html#Node).

That being said, you also mention finding the position of elements in html, there's something I implemented a while ago in a branch that could give you what you want (or a good starting point), take a look at this issue and comment: https://github.com/PuerkitoBio/goquery/issues/198#issuecomment-323737717 and the code is here: https://github.com/PuerkitoBio/goquery/blob/wip-selector/utilities.go#L21-L75 . Note that I don't remember how extensively it was tested, so use with care :)

Hope this helps!
Martin

**Comment by mna** [comment]
Closing as it seems like that addressed your issue, feel free to re-open if there's more to discuss about this.
