### ISSUE TITLE
Is it possible to save html that was manipulated using `goquery`?

### ISSUE THREAD

**Issue by inliquid** [PuerkitoBio/goquery#377]
If I understand correctly there are few methods that allow changing of HTML structure such as `Add*` and `Remove*`. I would like to change loaded document and then save it back to say, a file, or  using a `io.Writer` interface. Is it possible?

**Comment by mna** [comment]
Hello,

Yes, you understand correctly and you're right, such a function to render the document back to an `io.Writer` is currently lacking.

If you (or anyone else reading this) is interested in preparing a PR, I think something like that would make sense:

```
// Render renders the html of the first item in the selection s to w.
func Render(w io.Writer, s *goquery.Selection) error
```

This would be a top-level function, so it would be called as `err := goquery.Render(w, s)`. Rendering a complete document would be done by passing `doc.Selection` as `s`. This is similar in signature and implementation to `OuterHtml` and as such  should also be implemented in `utilities.go`, and tests should be provided for a few scenarios (i.e. render a top-level document, a Selection with 0, 1 and many items). Internally it would use `html.Render` (https://pkg.go.dev/golang.org/x/net/html#Render) from the net/html package.

I think this is a good first issue/first PR for someone interested in collaborating to goquery, not too complex and well isolated change.

Martin

**Comment by anthonygedeon** [comment]
Thanks for the quick reply, I'll start working on this issue then.
