### ISSUE TITLE
why goquery.NewDocument is null

### ISSUE THREAD

**Issue by thefireb** [PuerkitoBio/goquery#382]
like title，goquery.NewDocument

**Comment by mna** [comment]
Hello,

You should provide a minimal but complete program that demonstrates the issue you're having, so I can reproduce and give more helpful details. That being said, `NewDocument` is deprecated (https://pkg.go.dev/github.com/PuerkitoBio/goquery#NewDocument), you should use `NewDocumentFromReader` and make the request for the URL yourself beforehand, checking any error or status code problem before creating a goquery document.

If `NewDocument` returns a nil document, it returns a non-nil error. You should print that error, it will give you information about what went wrong.

Martin
