### ISSUE TITLE
insert at index

### ISSUE THREAD

**Issue by kdsch** [PuerkitoBio/goquery#383]
I need to clean up some HTML tables containing rowspans, where each row in the table does not have the same number of cells. Before rendering the tabular data to CSV, I need the row lengths to be consistent. (I do not need HTML rendering.)

Others have [solved](https://github.com/rocheio/wiki-table-scrape/blob/master/wikitablescrape/parse.py#L85) this problem in Python using Beautiful Soup. I am adapting this algorithm to my application while porting it to Go and goquery.

The algorithm relies on bs4's [insert](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#insert) method, which works like Python's list insert: inserts the item at a particular index in the list, moving the tail of the list after the inserted element.

I struggled to implement this behavior with goquery Selections. I understand tree manipulation is not a strong focus of the library; nevertheless, I suspect it is possible and am not worried about code quality, as this is a tool for a transient job.

**Comment by mna** [comment]
Hello Karl,

I think something like this would do the job, at the cost of two iterations over the rows of the table (if you trust the colspan values, you could do it by just looking at the first `tr` and read the `colspan` values to get the max cells of the table):

```
const data = `
<html>
  <head>
  </head>
  <body>
    <table>
      <tr>
        <td>1.1</td>
        <td>1.2</td>
        <td>1.3</td>
      </tr>
      <tr>
        <td>2.1</td>
        <td>2.2</td>
      </tr>
      <tr>
        <td>3.1</td>
      </tr>
      <tr>
        <td>4.1</td>
        <td>4.2</td>
        <td>4.3</td>
        <td>4.4</td>
        <td>4.5</td>
      </tr>
    </table>
  </body>
</html>
`

func main() {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}

	rows := doc.Find("tr")

	maxCells := 0
	rows.Each(func(i int, s *goquery.Selection) {
		if n := s.Find("td").Length(); n > maxCells {
			maxCells = n
		}
	})
	fmt.Printf("Maximum cells: %d\n", maxCells)

	rows.Each(func(i int, s *goquery.Selection) {
		n := s.Find("td").Length()
		if missing := maxCells - n; missing > 0 {
			html := strings.Repeat("<td>(added)</td>", missing)
			s.AppendHtml(html)
		}
	})
	fmt.Println(goquery.OuterHtml(doc.Selection))
}
```

Hope this helps,
Martin

**Comment by kdsch** [comment]
That code indeed makes the rows a consistent length, and though it does not demonstrate exactly what I needed, it is a very useful starting point! I've learned a lot by tinkering with it.

I should state the requirement clearly: It needs to insert copies of elements from elsewhere in the table at an arbitrary position in the row. I now understand that inserting copies requires `Clone()`.

One idea is to iterate over the row with `Each()`, and when the index reaches the desired value, use `Before()` to insert an element at that position.

```
package main

import (
	"strings"
	"fmt"
	"log"

	"github.com/PuerkitoBio/goquery"
)

const data = `
<html>
  <head>
  </head>
  <body>
    <table>
      <tr>
        <td>1</td>
        <td>2</td>
        <td>3</td>
      </tr>
    </table>
  </body>
</html>
`

func main() {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}

	rows := doc.Find("tr")
	rows.Each(func(_ int, row *goquery.Selection) {
		row.Find("td").Each(func(i int, cell *goquery.Selection) {
			if i == 1 {
				cell.BeforeHtml("<td>new</td>")
			}
		})
	})
	fmt.Println(goquery.OuterHtml(doc.Selection))
}
```

It works.

Another idea, closer to what I had initially tried, is to select an element at a certain position in the row using `Eq()`, then insert a cloned selection relative to that position using `Before...()`.

```
rows := doc.Find("tr")                           
rows.Each(func(_ int, row *goquery.Selection) {  
  row.Find("td").Eq(1).BeforeHtml("<td>new</td>")
})                                               
fmt.Println(goquery.OuterHtml(doc.Selection))    
```

This also works.

I have a little doubt about the robustness of these implementations, to be resolved by testing in my application.
