### ISSUE TITLE
Is it possible to get the text in a element line by line

### ISSUE THREAD

**Issue by ChathuraDR** [PuerkitoBio/goquery#384]
Let's say there's a html like this,
```html
  <td>
      Line 1
      <br>
      Line 2
      <br>
  </br>
```
 I managed to get the text inside the `<br>` tags. Is it possible to get each lines separately line by line ?

**Comment by mna** [comment]
Hello,

There is no way to do this directly, but you can take a look at my comment on another similar issue, it should work in your case too: https://github.com/PuerkitoBio/goquery/issues/287#issuecomment-471043149 (i.e. get the contents of the `<td>` and iterate over the nodes, finding the `#text` nodes).

Hope this helps,
Martin
