### ISSUE TITLE
how get all class element？

### ISSUE THREAD

**Issue by baerwang** [PuerkitoBio/goquery#387]
```go
	doc.Find("*").Each(func(i int, s *goquery.Selection) {

		if attr, exists := s.Children().Attr("class"); exists {
			fmt.Println("children:", attr)
		}

		if attr, exists := s.Attr("class"); exists {
			fmt.Println("s:", attr)
		}
	})
```

**Comment by mna** [comment]
Hello,

I'm not sure what issue you're facing, your code looks correct to me at least regarding how to get each element's class in the original selection (i.e. the second `if` in the `Each`). As you can see in the doc, `Attr` will return the attribute's value for the first element in the selection, so if you want all elements' values, you use the `Each` loop (or `Map): https://pkg.go.dev/github.com/PuerkitoBio/goquery#Selection.Attr.

The `s.Children().Attr(...)` call would get the `class` attribute's value of the first children only, maybe that's what was confusing in your results?

Hope this helps,
Martin

**Comment by mna** [comment]
Feel free to reopen with more info if there's anything else regarding this issue!
