### ISSUE TITLE
handling unsupported protocol scheme ""

### ISSUE THREAD

**Issue by iateadonut** [PuerkitoBio/goquery#388]
I think maybe, if a url with no protocol, like "google.com" is passed in, we can automatically affix the http protocol.

If you think this idea will work for your package, let me know and I'll create the commit and make a PR.

**Comment by mna** [comment]
Hello,

I assume you mention this for the `NewDocument` function that takes a url as argument, but this function is deprecated, and as such will not be modified (https://pkg.go.dev/github.com/PuerkitoBio/goquery#NewDocument). The recommended approach is to make the http request via other means (e.g. Go's net/http.Client) and validate the response before using goquery on the html body (using `NewDocumentFromReader`).

Have fun with your project!
Martin
