### ISSUE TITLE
Can it be adapted to the native js method to obtain the current node text

### ISSUE THREAD

**Issue by OneSeven** [PuerkitoBio/goquery#390]
```
<div>
    text document
    <span>span</span>
    das
</div>
<script>
    let text = document.querySelector("div").firstChild.nodeValue
    console.log(text.trim())
</script>
```

**Comment by mna** [comment]
I think what you're asking for is a way to get the text content inside the div but before the span element? This comment may be what you're looking for: https://github.com/PuerkitoBio/goquery/issues/287#issuecomment-471043149

Hope this helps,
Martin

**Comment by OneSeven** [comment]
> I think what you're asking for is a way to get the text content inside the div but before the span element? This comment may be what you're looking for: [#287 (comment)](https://github.com/PuerkitoBio/goquery/issues/287#issuecomment-471043149)
> 
> Hope this helps,
> Martin

thanks
