### ISSUE TITLE
AppendHTML broken after v1.6.0

### ISSUE THREAD

**Issue by lox** [PuerkitoBio/goquery#401]
I'm just trying to update a complicated codebase that uses goquery 1.5.1 to a more recent version and I've run into what is either a regression or possibly an intended breaking change that I don't quite understand.

The test code is:

```go
package main

import (
	"fmt"
	"log"
	"strings"

	"github.com/PuerkitoBio/goquery"
)

func main() {
	// Load an empty HTML document
	doc, err := goquery.NewDocumentFromReader(strings.NewReader("<body></body>"))
	if err != nil {
		log.Fatal(err)
	}

	// append a new container element
	doc.AppendHtml(`<div id="normalized"></div>`)

	// lookup the container element
	normalized := doc.Find(`#normalized`)

	// expect <div id="normalized"></div>
	fmt.Println(goquery.OuterHtml(normalized))
}
```

In v1.5.1, I get the container div output correctly:

```
<div id="normalized"></div>
```

In v1.6.1 I get an empty string output.

Any ideas?

**Comment by lox** [comment]
This appears to be fixed by changing the append line to `doc.Find("body").AppendHtml(`<div id="normalized"></div>`)`.

**Comment by mna** [comment]
I would think this is a change in the golang.org/x/net/html dependency, the html5 parser, but I'm not 100% sure? I'll try to take  a closer look when I have a moment, unless you can try that out to identify if it caused this change in behaviour.

**Comment by lox** [comment]
Might it be worth bumping the major version?

**Comment by mna** [comment]
Considering that 1.6 has been out for almost a year and a half, and that 1.7 and 1.8 have been released since, I'd say that even assuming this deserved a bump (which I'm not convinced it does), that ship has sailed. The reason I'm not convinced is that the code it broke relied on an arguably incorrect use / a bug (appending to the "doctype" node), otherwise the API is completely compatible.

**Comment by lox** [comment]
Fair enough! Shall I close the issue?

**Comment by mna** [comment]
Yeah I think we're good to close this now, I'll do it with this comment. Thanks for raising this!
