### ISSUE TITLE
ZWNBSP causes goquery html head to parse improperly.

### ISSUE THREAD

**Issue by imjdl** [PuerkitoBio/goquery#403]
target:  http://195.110.124.154
ZWNBSP Wiki: [https://en.wiktionary.org/wiki/ZWNBSP](https://en.wiktionary.org/wiki/ZWNBSP)
Description: 
This problem was found when using goauery to parse responses from Internet species.

```golang
package main

import (
	"bytes"
	"fmt"
	"github.com/PuerkitoBio/goquery"
	"io/ioutil"
	"net/http"
)

func main() {
	res, err := http.Get("http://195.110.124.154")
	if err != nil {
		panic("meh")
	}
	body, err := ioutil.ReadAll(res.Body)
	if err != nil {
		panic("meh")
	}
	doc, err := goquery.NewDocumentFromReader(bytes.NewReader(body))
	if err != nil {
		panic("meh")
	}
	// Unable to get title
	doc.Find("head").Each(func(i int, s *goquery.Selection) {
		pageTitle := s.Find("title").Text()
		fmt.Println(pageTitle)
	})
	// You can get the title in the body
	doc.Find("body").Each(func(i int, s *goquery.Selection) {
		pageTitle := s.Find("title").Text()
		fmt.Println(pageTitle)
	})
}
```
The presence of ZWNBSP prevents goquery from correctly parsing html.

**Comment by mna** [comment]
Hello,

Please provide a static html string that replicates the issue. Note that goquery itself does not do the parsing, it is done by the Go net/html package.

Martin

**Comment by imjdl** [comment]
> Hello,
> 
> Please provide a static html string that replicates the issue. Note that goquery itself does not do the parsing, it is done by the Go net/html package.
> 
> Martin

Ok Thanks for the answer. It doesn't seem to be a goquery problem. Thanks again
