### ISSUE TITLE
goquery returns empty data, while trying to scrape the data, which is present inside the head tag.

### ISSUE THREAD

**Issue by sdpatel1026** [PuerkitoBio/goquery#408]
I am trying to fetch data, which is present inside head tag, but it didn't work for this [url](https://hcservices.ecourts.gov.in/hcservices/) . It's working fine with other urls.

**My code:-**
```
doc, err := goquery.NewDocumentFromReader(strings.NewReader(string(data)))
	if err != nil {
		return err
	}
	res := doc.Find(`head > title`)
	fmt.Println("text: ", res.Text()) 
```

**Comment by mna** [comment]
Hello,

Please provide a minimal but complete example that reproduces the issue, based on a static html string (the url you provided could've changed, maybe there was a failure fetching the page, the status code wasn't checked, etc.).

Keep in mind that some web pages are dynamically modified by javascript, so if you inspect the page in the browser's console, you may see a structure that doesn't match the one of the raw html you get from the url itself.

Martin

**Comment by sdpatel1026** [comment]
My Go code:-
`
package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"os"
	"strings"

	"github.com/PuerkitoBio/goquery"
	"github.com/hashicorp/go-retryablehttp"
)

func main() {
	highCourtUrl := "https://hcservices.ecourts.gov.in/hcservices"
	// highCourtUrl := "https://www.google.com"
	// highCourtUrl := "https://www.microsoft.com"
	// highCourtUrl := "https://tweakers.net/nieuws/103412/ontwikkelaar-schrijft-software-voor-opvragen-sites-via-tor-in-php.html"
	request, err := retryablehttp.NewRequest("GET", highCourtUrl, nil)
	if err != nil {
		log.Println("Error in making request to main.php:", err.Error())
		return
	}
	retryablehttpClient := retryablehttp.NewClient()
	retryablehttpClient.RetryMax = 0
	response, err := retryablehttpClient.Do(request)
	if err != nil {
		log.Println("Error in calling main.php:", err.Error())
		return
	}
	writeResponseToHTMLFile(response)
	err = scrapeValuedFromFile()
	if err != nil {
		log.Println("Error in scraping: ", err.Error())
		return
	}
}

func scrapeValuedFromFile() error {

	data, err := ioutil.ReadFile("./response.html")
	if err != nil {
		log.Printf("Error in reading response.html file:%s", err.Error())
		return err
	}
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(string(data)))
	if err != nil {
		return err
	}
	text := doc.Find(`head title`).Text()
	fmt.Println("title: ", text)
	return nil
}

func writeResponseToHTMLFile(response *http.Response) error {
	body, _ := ioutil.ReadAll(response.Body)
	var file *os.File
	var err error
	file, err = os.Create("./response.html")
	if err != nil {
		return err
	}
	defer file.Close()
	_, err = file.WriteString(string(body))
	if err != nil {
		log.Printf("Error in writing  error: %s", err.Error())
		return err
	}
	return nil
}
`

response.html file present [here](https://github.com/sdpatel1026/FIles/blob/master/response.html)

**Comment by mna** [comment]
I haven't tried your exact code with third-party packages, but this minimal program works as expected (which is basically your `scrapeValuedFromFile` function, it prints the title as present in the html, note that I've saved your `response.html` file in `data.html`):

```
func main() {
	f, err := os.Open("./data.html")
	if err != nil {
		log.Fatal(err)
	}
       defer f.Close()

	doc, err := goquery.NewDocumentFromReader(f)
	if err != nil {
		log.Fatal(err)
	}
	text := doc.Find(`head title`).Text()
	fmt.Println("title: ", text)
}

// prints: title:  Home - eCourt India High Courts Services
```
