### ISSUE TITLE
More of jQuery selectors

### ISSUE THREAD

**Issue by mitar** [PuerkitoBio/goquery#413]
Hm, this package does not expose many of jQuery selectors, just CSS selectors. I really hoped that I could use it like jQuery but it seems this is not really so. See here is the list of [jQuery extension selectors available](https://api.jquery.com/category/selectors/jquery-selector-extensions/). Any plans to support them? Especially `:has()` would be cool.

**Comment by mitar** [comment]
What about `:has()`?

**Comment by mna** [comment]
Oh sorry, missed the part about `has` in your comment, this is actually supported:

```
const data = `
<html>
  <body>
    <div class="c1">
      <div class="c2"><p>Paragraph</p></div>
    </div>
    <div class="c3">
      <div class="c4"><span>Text</span></div>
    </div>
  </body>
</html>
`

func main() {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}
	sel := doc.Find("div:has(p)")
	sel.Each(func(i int, s *goquery.Selection) {
		h, _ := goquery.OuterHtml(s)
		fmt.Println(i, h)
	})
}
```

I don't think `parent` is supported though.

Hope this helps,
Martin

**Comment by mitar** [comment]
Oh. Maybe then cascadia needs a list of supported selectors. :-(

Thanks!
