### ISSUE TITLE
Support :scope selector

### ISSUE THREAD

**Issue by mitar** [PuerkitoBio/goquery#414]
See related issue in cascadia: https://github.com/andybalholm/cascadia/issues/43

I think this or that library should provide a `:scope` selector to be able to do the following:

```go
table.Find(":scope > tbody > tr > th")
```

To find only `th` directly under the top-level table, and not find some nested table. But it seems this is currently not possible.

**Comment by mna** [comment]
Hello,

Cascadia is the selector library that goquery uses. If such support is to be added, it would happen in cascadia.

Martin

**Comment by mitar** [comment]
Cascadia does support `:root` selector. So maybe `selection.FindWithRoot` could be introduced which would make every element of `selection` be seen as document root. Then it would be possible to separate longer selection into pieces which is currently not possible without `:scope`. E.g., I am trying this to get to work:

```golang
	var table *goquery.Selection
	doc.Find("section").EachWithBreak(func(_ int, section *goquery.Selection) bool {
		for _, level := range []string{"h1", "h2", "h3", "h4", "h5", "h6"} {
			heading := section.ChildrenFiltered(level).Text()
			if heading == "Summary" {
				table = section.Find(":scope > table")
				return false
			}
		}
		return true
	})
	if table != nil {
		table.Find(":scope > tbody > tr > th")...
	}
```

In theory `section > h2:contains('Summary') + table > tbody > tr > th` should be the same, but it is not because `:contains` seems to work differently. So combining it with custom Go code is necessary. But without `:scope` it does not really work. Omitting `:scope` in those selectors could lead to matching some nested tables.

**Comment by mna** [comment]
Sorry, I don't plan to add features to compensate for missing selectors. It would be easy to support different selector matchers (satisfying the goquery.Matcher interface), but the best approach would definitely be to try to add support to the battle-tested cascadia package (though I have no idea if the maintainer is interested in either doing the work or accepting such a PR).

**Comment by mitar** [comment]
> though I have no idea if the maintainer is interested in either doing the work or accepting such a PR

[It seems not](https://github.com/andybalholm/cascadia/issues/43#issuecomment-1112173906). So it is a bit of chicken and egg problem. You say that this is out of scope of this package, maintainer of cascadia is saying it is out of scope of that package.

**Comment by mna** [comment]
That's unfortunate but I wouldn't call this a chicken and egg problem - it is a selector, it belongs in a query selector package. Now, the maintainer surely knows better than anyone how feasible that would be, but if you want to give it a shot anyway in a fork, as I said, it wouldn't be too hard to support different selector packages in goquery assuming you can add the feature while maintaining the interface compatibility. If it can be done cleanly, it's not impossible that Andy would reconsider his position, and if not, it wouldn't be a huge amount of work to export a configuration function in goquery to swap the selector package.

**Comment by mna** [comment]
That being said, I'm not sure I completely understand the `:scope` pseudo-selector, but if what you're mostly interested in is to use `:scope > someElement`, wouldn't that be roughly equivalent?

```
const data = `
<div id="context">
    <div id="element-1">
        <div id="element-1.1"></div>
        <div id="element-1.2"></div>
    </div>
    <div id="element-2">
        <div id="element-2.1"></div>
    </div>
</div>
<p>
    Selected elements ids :
    <span id="results"></span>
</p>
`

func main() {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}
	sel := doc.Find("#context")
	subSel := sel.ChildrenFiltered("div")
	subSel.Each(func(i int, s *goquery.Selection) {
		h, _ := goquery.OuterHtml(s)
		fmt.Println(i, h)
	})
}
```

I.e. it selects only the direct "div" children of the selection (which acts like the ":scope")?

**Comment by mitar** [comment]
You are right, I could probably do `table.ChildrenFiltered("tbody").ChildrenFiltered("tr").ChildrenFiltered("th")` in this particular case, too.
