### ISSUE TITLE
Match tag name with certain suffix

### ISSUE THREAD

**Issue by CaledoniaProject** [PuerkitoBio/goquery#418]
I'm trying to find `<a:publication_date>` and `<b:publication_date>` and more. How can I do all similar tags ending with `publication_date`?

This does not work:

```
sel.Find(".*publication_date").Each(...)
```

**Comment by mna** [comment]
Hello,

It looks like you're trying to parse XML, not HTML? goquery works with HTML, not XML (you may want to use the stdlib's xml package or a third-party library for this).

Martin

**Comment by CaledoniaProject** [comment]
@mna Yes, I'm parsing XML. The selector `b\\:publication_date` works in this case but I can't match a suffix with goquery. Is that supported?

**Comment by mna** [comment]
No, goquery is an **html** parser, not an **xml**. It uses the golang.org/x/net/html parser internally, which follows the html5 parsing spec.
