### ISSUE TITLE
How can I parse single element

### ISSUE THREAD

**Issue by xiyichan** [PuerkitoBio/goquery#426]
```html
<speak><voice name=\"en-US-JennyNeural\"><prosody rate=\"1\" >aaaaaaaa<break time=\"5s\" /> bbbb. <break time=\"2s\" />cccccc       <break       time=\"3.5s\" />dddddddd  <break time=\"3.5s\" />adsfasdf</prosody></voice></speak>
```
i  use this code to parse and get 
```go 
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(text))
	if err != nil {
		return "", err
	}
	ssml, err := doc.Find("body").Html()
	if err != nil {
		return "", err
	}

```

```html
<speak><voice name="en-US-JennyNeural"><prosody rate="1">aaaaaaaa<break time="5s"> bbbb. <break time="2s">cccccc       <break time="3.5s">dddddddd  <break time="3.5s">adsfasdf</break></break></break></break></prosody></voice></speak>

```

I dont want to get </break>. Does goquery support?

**Comment by mna** [comment]
Hello,

This is not html, goquery only manipulates html - it uses Go's html5 parser internally. I'm not sure what you were trying to do (your last sentence "I dont want to get." seems incomplete), but regardless, goquery will break in weird and surprising ways when parsing anything other than html. You probably want an xml parser instead.

Hope this helps,
Martin

**Comment by xiyichan** [comment]
> Hello,
> 
> This is not html, goquery only manipulates html - it uses Go's html5 parser internally. I'm not sure what you were trying to do (your last sentence "I dont want to get." seems incomplete), but regardless, goquery will break in weird and surprising ways when parsing anything other than html. You probably want an xml parser instead.
> 
> Hope this helps, Martin

Thanks, i will find a go package to parse this xml(ssml). If you know which package is good, please tell my.

**Comment by mna** [comment]
I haven't used other xml packages besides Go's stdlib xml package, but a good place to look for such packages is on pkg.go.dev, searching for ssml even shows some packages specifically for this format: https://pkg.go.dev/search?q=ssml

Have fun!
Martin

**Comment by xiyichan** [comment]
> I haven't used other xml packages besides Go's stdlib xml package, but a good place to look for such packages is on pkg.go.dev, searching for ssml even shows some packages specifically for this format: https://pkg.go.dev/search?q=ssml
> 
> Have fun! Martin

thanks
