### ISSUE TITLE
href written via SetAttr query params encoding oddly

### ISSUE THREAD

**Issue by tmountain** [PuerkitoBio/goquery#436]
Hi, I have the following code:

```
package main

import (
	"fmt"
	"strings"

	"github.com/PuerkitoBio/goquery"
)

func main() {
	// Load the HTML document
	inputHTML := `
	<html>
	<body>
	<a href="http://example.com/">Example</a>
	</body>
	</html>`
	doc, _ := goquery.NewDocumentFromReader(strings.NewReader(inputHTML))

	// Modify the href attribute of all links on the page
	doc.Find("a").Each(func(i int, s *goquery.Selection) {
		// Set the modified URL as the new href value
		s.SetAttr("href", "http://example.com/app?foo=bar&baz=qux")
	})

	// Render the HTML to a string
	html, _ := doc.Html()
	fmt.Println(html)
}
```

When I run it, I get the following:

```
<html><head></head><body>
        <a href="http://example.com/app?foo=bar&amp;baz=qux">Example</a>

        </body></html>
```

As you can see, the ampersand between foo=bar&baz=qux is being encoded to &amp;

How can I avoid this behavior? It's preventing me from changing hrefs in the way that I need to. Thanks!

**Comment by mna** [comment]
Hello Travis,

Yes that seems like correct behaviour, the encoding of the attribute is properly html-escaped (i.e. the `&` is encoded as `&amp;`). Does that cause you any issue? E.g. if you read the attribute after setting it, you'll get the correct (decoded) value:

```
func main() {
	// Load the HTML document
	inputHTML := `
	<html>
	<body>
	<a href="http://example.com/">Example</a>
	</body>
	</html>`
	doc, _ := goquery.NewDocumentFromReader(strings.NewReader(inputHTML))

	// Modify the href attribute of all links on the page
	doc.Find("a").Each(func(i int, s *goquery.Selection) {
		// Set the modified URL as the new href value
		s.SetAttr("href", "http://example.com/app?foo=bar&baz=qux")
	})

        // print the href
	doc.Find("a").Each(func(i int, s *goquery.Selection) {
		// print the attribute
		fmt.Println(s.Attr("href"))
	})
}
```

This prints `http://example.com/app?foo=bar&baz=qux` as expected. Similarly, if you load this html into a web browser, it will work as expected (clicking the link will take you to `example.com/app?foo=bar&baz=qux`).

If it did not do that html escaping, then say you wanted to use `foo=bar&amp;=qux` and you really wanted that to mean `foo=bar` and `amp;=qux`, it wouldn't work.

Hope this helps,
Martin
