### ISSUE TITLE
dealing with profiles in script tags.

### ISSUE THREAD

**Issue by fils** [PuerkitoBio/goquery#440]
I am looking at the JSON-LD docs and specifically at 

https://www.w3.org/TR/json-ld/#iana-considerations

I use your package as part of my tool that pulls JSON-LD documents from pages.   We look for the tags like

```html
<script type="application/ld+json>....</script>
```

However, if we had people start to use profiles like in 

```html
<script type="application/ld+json;profile=http://www.w3.org/ns/json-ld#frame">
````

Would an implementation like 

```go
doc.Find("script[type='application/ld+json']").Each(func(i int, s *goquery.Selection) {...})
````

still find / match on the second example above?   I guess the question is, is the stuff beyond the ; ignored with respect to Find?

**Comment by mna** [comment]
Hello Douglas,

The string you pass to `doc.Find` is a CSS selector, which is a web standard. What you want in this case, I think, is to find a `script` that has the `type` attribute that _starts with_ the `application/ld+json` string. You can achieve this using `script[type^=application/ld+json]` selector (more info about the various supported attribute selectors here: https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors#syntax.

Here's an example program that shows this in context:

```
const data = `
<body>
	<script type="application/ld+json;profile=http://www.w3.org/ns/json-ld#frame">"js";</script>
</body>
`

func main() {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(doc.Find("script[type^='application/ld+json']").Text())
}
```

Hope this helps!
Martin

**Comment by fils** [comment]
@mna Thanks!   I'll work up a test and try it but this does sound like what I need.  

Appreciate the help!

**Comment by mna** [comment]
Sounds good, feel free to reopen if you have follow-up comments/questions (or of course open a new issue if needed).
