### ISSUE TITLE
BUG:  Attr func can not get  data if  attr data have " Symbols

### ISSUE THREAD

**Issue by mengxifl** [PuerkitoBio/goquery#446]
html example
```
<div title=" this is a "title"  ">
```

**Comment by mna** [comment]
Hello,

This is in invalid html, the quotes inside the title need to be escaped (see https://validator.w3.org/nu/#textarea to validate your html, https://stackoverflow.com/questions/4015345/how-do-i-properly-escape-quotes-inside-html-attributes on how to properly escape quotes).

Martin
