### ISSUE TITLE
GoQuery Not Matching Element

### ISSUE THREAD

**Issue by Vedant-Gandhi** [PuerkitoBio/goquery#449]
Hey there ,
I am working on a project using GoQuery and am facing an issues. So I am trying to remove  the link tag from the page. Theoretically this should work just like normal elements but whatever I do the link tag is not being found.My sample input is - 
`<html><head><link rel='preload' as='script' href='critical.js'><script>var x=0</script></head><body><p>Hello</p><script   > let x=false; if(x === true) console.log('hello') </script></body></html>`

**Comment by mna** [comment]
Hello,

You haven't provided the program to reproduce the issue, but this works for me:

```
func main() {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}
	doc.Find("link").Remove()
	fmt.Println(goquery.OuterHtml(doc.Selection))
}

// Prints:
// <html><head><script>var x=0</script></head><body><p>Hello</p><script> let x=false; if(x === true) console.log('hello') </script></body></html> <nil>
```

Hope this helps,
Martin

**Comment by Vedant-Gandhi** [comment]
@mna Sorry seems that I  did not understood the documentation properly and was using RemoveFiltered() instead of Remove()
