### ISSUE TITLE
How to count the number of words before and after a selection across a document?

### ISSUE THREAD

**Issue by lazharichir** [PuerkitoBio/goquery#451]
Imagine you have a blog post with contains various tags such as `<section>`, `<p>`, `<a>`, `<span>`, `<em>`, and so on. You parse it with `goquery` and select a specific element, let's say a `<span id="something">some sentence here</span>`.

How would you go to count the number of words or characters before that element in the entire article, as well as after?

**Comment by lazharichir** [comment]
Alright, I found a hack to make it work... and can also work with char offset rather than words.

```go
func CountWordsBeforeAndAfterSelection(doc *goquery.Document, sel *goquery.Selection) (before int, after int) {
	beforeMarker := generateUUID()
	afterMarker := generateUUID()

	sel.BeforeHtml(fmt.Sprintf(`<span>%s</span>`, beforeMarker))
	sel.AfterHtml(fmt.Sprintf(`<span>%s</span>`, afterMarker))

	text := doc.Text()

	textBeforeMarker := strings.Split(text, beforeMarker)
	textAfterMarker := strings.Split(text, afterMarker)

	wordsBeforeMarker := strings.Fields(textBeforeMarker[0])
	wordsAfterMarker := strings.Fields(textAfterMarker[1])

	return len(wordsBeforeMarker), len(wordsAfterMarker)
}
```

**Comment by mna** [comment]
This is more a CSS selector question than something to do with goquery. I don't know how you'd do that, you may have more helpful answers on stackoverflow using the jquery tag.
