### ISSUE TITLE
How to query a shadow DOM?

### ISSUE THREAD

**Issue by drgrib** [PuerkitoBio/goquery#465]
Background on what a shadow DOM is [here](https://stackoverflow.com/a/34119775/130427). I'm trying to query the shadow DOM parented by `#history-app` in Chrome under `chrome://history/`.

When I query `#history-app` using `goquery` and check its `Children().Nodes`, the slice is empty. There are several shadow DOMs below that before I can get to the `#time-accessed` fields I'm looking for. Trying to query `#time-accessed` directly, predictably, returns nothing.

Any way I can access these using `goquery`?

For some background on possible solutions, people seem to be doing this is Javascript / Dart [in StackOverflow](https://stackoverflow.com/questions/29629492/how-to-query-elements-within-shadow-dom-from-outside-in-dart) and in a [Github Repo](https://github.com/webdriverio/query-selector-shadow-dom).

**Comment by drgrib** [comment]
> I believe the shadow DOM is something that only exists "at runtime" when the page is loaded in a browser, right?

From clicking "View page source", it looks like you are right. I usually develop my `goquery` calls from the Elements tab where the shadow DOM content actually is available. I've had bad experiences with what at least the `chromedp` headless browsers does to my Chrome instance and I'm not sure if `otto` can help me access the shadow DOMs or not. But thank you for the response and pointers to possible solutions.

**Comment by mna** [comment]
No problem, good luck and have fun with your project! I'll close for now, but if you find a way to make that work it would be awesome if you could comment back on how you handled it, in case others are facing the same situation (either a comment on this issue or by editing the wiki page).
