### ISSUE TITLE
Release Request for Current HEAD of golang.org/x/net with Security Updates

### ISSUE THREAD

**Issue by catatsuy** [PuerkitoBio/goquery#471]
I noticed that the master branch of `golang.org/x/net` includes updates for security vulnerabilities, which is great. However, these changes have not been officially released yet. 

Thanks for all your work on this project.

**Comment by mna** [comment]
Thanks, feel free to ping me once they release a new version (or send a PR with the changes to `go.mod`) and I'll get that update merged in.

**Comment by catatsuy** [comment]
@mna Thank you for your response. The update has already been handled by Dependabot, so it would be great if you could release it. Looking forward to the updated version!

**Comment by mna** [comment]
Oh you mean goquery has updates, I thought you meant `golang.org/x/net`! Yeah I guess I can cut a new version, but keep in mind that you can always control the dependencies you use in your project, no need to rely on `goquery` or any `go.mod` of your dependent packages. Here's an example of a new `main` program that uses goquery and that upgrades `golang.org/x/net` independently of goquery:

```
$ go mod init
go: creating new go.mod: module <programname>
go: to add module requirements and sums:
	go mod tidy

# go-getting goquery gets the outdated x/net version
$ go get github.com/PuerkitoBio/goquery@latest
go: downloading github.com/PuerkitoBio/goquery v1.9.1
go: downloading github.com/andybalholm/cascadia v1.3.2
go: downloading golang.org/x/net v0.21.0
go: added github.com/PuerkitoBio/goquery v1.9.1
go: added github.com/andybalholm/cascadia v1.3.2
go: added golang.org/x/net v0.21.0

$ cat go.mod
module <programname>

go 1.22.2

require (
	github.com/PuerkitoBio/goquery v1.9.1 // indirect
	github.com/andybalholm/cascadia v1.3.2 // indirect
	golang.org/x/net v0.21.0 // indirect
)

# explicitly upgrade the x/net dependency
$ go get -u golang.org/x/net
go: downloading golang.org/x/net v0.24.0
go: upgraded golang.org/x/net v0.21.0 => v0.24.0

$ cat go.mod
module <programname>

go 1.22.2

require (
	github.com/PuerkitoBio/goquery v1.9.1 // indirect
	github.com/andybalholm/cascadia v1.3.2 // indirect
	golang.org/x/net v0.24.0 // indirect
)

# double-check that the correct version is what gets built in the binary
$ go build ./main.go 
$ go version -m ./main
./main: go1.22.2
	path	command-line-arguments
	dep	github.com/PuerkitoBio/goquery	v1.9.1	h1:mTL6XjbJTZdpfL+Gwl5U2h1l9yEkJjhmlTeV9VPW7UI=
	dep	github.com/andybalholm/cascadia	v1.3.2	h1:3Xi6Dw5lHF15JtdcmAHD3i1+T8plmv7BQ/nsViSLyss=
	dep	golang.org/x/net	v0.24.0	h1
       ...
```

But yeah, I'll still create a new release just to save the manual upgrade step.

**Comment by mna** [comment]
v1.9.2 released.

**Comment by catatsuy** [comment]
Thank you!
