### ISSUE TITLE
Как добавить "github.com/PuerkitoBio/goquery" в свой код в визуал студио коде?

### ISSUE THREAD

**Issue by Genesys3** [PuerkitoBio/goquery#473]
Написал прогу для просмотра инфы о каналах, но визуал код студо не хочет запускать, ведь надо как-то добавить "github.com/PuerkitoBio/goquery" в прогу
package main

import (
	"fmt"
	"log"
	"strings"

	"github.com/PuerkitoBio/goquery"
)

func main() {
	channelURL := "https://www.youtube.com/@RickAstleyYT"
	doc, err := goquery.NewDocument(channelURL)
	if err != nil {
		log.Fatal(err)
	}

	doc.Find(".yt-lockup-title a").Each(func(i int, s *goquery.Selection) {
		title := strings.TrimSpace(s.Text())
		link, _ := s.Attr("href")
		fmt.Printf("Video Title: %s\n", title)
		fmt.Printf("Video Link: https://www.youtube.com%s\n", link)
	})

	subscribers := doc.Find(".yt-subscription-button-subscriber-count-branded-horizontal").Text()
	description := doc.Find(".about-description").Text()
	channelName := doc.Find(".qualified-channel-title-text").Text()

	fmt.Printf("Количество подписчиков: %s\n", subscribers)
	fmt.Printf("Описание канала: %s\n", description)
	fmt.Printf("Название канала: %s\n", channelName)
}

**Comment by mna** [comment]
I don't speak Russian but Google Translate gave me this:

```
I wrote a program to view information about channels, but the visual studo code does not want to run, because I need to somehow add "github.com/PuerkitoBio/goquery" to the program
```

So what you need to do is run `go mod init` in your directory where you have your `main` Go file, and then `go get github.com/PuerkitoBio/goquery`. Note that this is not related to goquery in any way, this is how the Go tooling works. You may find it useful to look at some [Go tutorials](https://go.dev/learn/#tutorials) if you do speak English (I'm not sure if they have good translations?), and this part in particular should be relevant, it's about creating a Go module and importing it/calling it from another program (this is what you tried to do, use the goquery module from your program): https://go.dev/doc/tutorial/call-module-code. It will give you some insights about how Go modules work too.

Hope this helps! Have fun,
Martin
