### ISSUE TITLE
помогите с установкой GOPATH И GOROOT

### ISSUE THREAD

**Issue by Genesys3** [PuerkitoBio/goquery#474]
Помогите пж с установкой и настройкой GOPATH и GOROOT

**Comment by mna** [comment]
See https://github.com/PuerkitoBio/goquery/issues/473#issuecomment-2094344338. For additional help with how Go works, please use Go's community channels, there are many options listed here: https://go.dev/help. I think the `golang-nuts` mailing list is best, but I haven't used it in a while.
