### ISSUE TITLE
Has anyone ever tried goquery in a webbrowser with wasm?

### ISSUE THREAD

**Issue by nickchomey** [PuerkitoBio/goquery#476]
One knock against jquery is it is slower than vanilla javascript. Has anyone ever tried compiling goquery to wasm and running it in the browser? It probably cant manipulate the DOM directly, but could run via a service or webworker to manipulate other HTML fragments (such as returned via AJAX calls).

**Comment by mna** [comment]
Probably best to ask things like that on discussion forums.
