### ISSUE TITLE
Support thanks.dev for sponsors

### ISSUE THREAD

**Issue by mitar** [PuerkitoBio/goquery#500]
We use https://thanks.dev to distribute donations and it would be great if you could enable yourself as recipient so that we could also donate to you through it (not much, but still).

**Comment by mna** [comment]
Hey, thanks for the intention, much appreciated and I'm glad you use and like goquery! As for donations, I already have a couple options setup and I'm not too keen on adding more, I understand some folks or companies may not be able to use Github sponsors, but that's allright, it's very nice of you to let me know you wanted to, though!

Thanks and have fun with your projects!
Martin

**Comment by mitar** [comment]
Thanks.dev combines with GitHub Sponsors (among others), so that should not be a problem. You just have to sign-in once and ack that you are OK with donations and this is it.

**Comment by mna** [comment]
Gotcha, I'll take a closer look a bit later then!

**Comment by mna** [comment]
I created an account/enabled thanks.dev. Thanks!

**Comment by mitar** [comment]
Awesome! Thanks.
