### ISSUE TITLE
Got an error when executing go get

### ISSUE THREAD

**Issue by wanghongfei** [PuerkitoBio/goquery#61]
After executing `go get github.com/PuerkitoBio/goquery`, I got following prompt:
```
abort: code.google.com certificate error: certificate is for *.googleusercontent.com, *.blogspot.com, *.bp.blogspot.com, *.commondatastorage.googleapis.com, *.doubleclickusercontent.com, *.ggpht.com, *.googledrive.com, *.googlesyndication.com, *.sandbox.googleusercontent.com, *.storage.googleapis.com, blogspot.com, bp.blogspot.com, commondatastorage.googleapis.com, doubleclickusercontent.com, ggpht.com, googledrive.com, googleusercontent.com, static.panoramio.com.storage.googleapis.com, storage.googleapis.com
(configure hostfingerprint 70:03:d2:44:35:d0:d4:64:85:f0:3e:c8:15:9c:4d:e7:59:91:50:0d or use --insecure to connect insecurely)
package github.com/PuerkitoBio/goquery
	imports code.google.com/p/cascadia: exit status 255

```

I'm a newbie to Golang. Could anyone tell me how to fix it? Thanks!

**Comment by PuerkitoBio** [comment]
Just tried a clean install and everything worked fine, you could try to run the command with -v to get verbose output, but your error message is pretty clear. Something is not happy with the TLS certificate, but I have no idea why...

**Comment by wanghongfei** [comment]
@PuerkitoBio Thank you very much. I've fixed it by adding `70:03:d2:44:35:d0:d4:64:85:f0:3e:c8:15:9c:4d:e7:59:91:50:0d` to configuration file.
