### ISSUE TITLE
How to find html attribute whose value begins with a number?

### ISSUE THREAD

**Issue by GreenRaccoon23** [PuerkitoBio/goquery#62]
Say the html document I'm parsing has the attribute `class="1post"`. Is there a way to use the `Find()` function for this class? If I run `doc.Find(".1post")`, I get this error:
`panic: expected identifier, found 1 instead`

This might be a cascadia issue. Do you know of a way around it?

**Comment by PuerkitoBio** [comment]
In theory a class name cannot start with a number, except if the number is escaped. So I guess cascadia is doing the right thing here. You may want to try with the escaped syntax, I haven't tested it, but you can read the details here:

**Comment by GreenRaccoon23** [comment]
Sorry I guess I forgot to reply. I didn't test this, but I found a workaround (for my case, at least). The page I was parsing had something like `span class="apost 1post"`, so I just did this:
```
doc.Find("span").Each(func(i int, s *goquery.Selection) {
    class, _ := s.Attr("class")
    switch class {
    case "1post":
        fmt.Println("got it")
    default:
        fmt.Println("wrong")
    }
})
```

**Comment by PuerkitoBio** [comment]
Thanks for the reply, that may help others with the same problem.
