### ISSUE TITLE
'*goquery.Document' to 'io.Reader'

### ISSUE THREAD

**Issue by GreenRaccoon23** [PuerkitoBio/goquery#63]
This isn't an issue; it's an idea/feature request. It'd be cool if there were a way to convert a goquery.Document type to an io.Reader type. The `NewDocumentFromReader` function does the reverse. A `NewReaderFromDocument` function would be cool too.

**Comment by PuerkitoBio** [comment]
There's no obvious way to generate a Reader from goquery, you could create a strings.Reader from doc.Html(), though. I don't think there's enough value to add it to the API, honestly.

**Comment by baixiaoshi** [comment]
no, doc.Html() is read all on memory，not stream read

**Comment by baixiaoshi** [comment]
no, doc.Html() is read all on memory，not stream read
