### ISSUE TITLE
Get the code failed

### ISSUE THREAD

**Issue by liwp-stephen** [PuerkitoBio/goquery#65]
Hello, I want to use your code, and after run the command:
go get github.com/PuerkitoBio/goquery

It will report the following error:
package code.google.com/p/cascadia: Get https://code.google.com/p/cascadia/source/checkout?repo=: dial tcp 173.194.38.5:443: i/o timeout
package golang.org/x/net/html: unrecognized import path "golang.org/x/net/html"

It seems the packages the project depends can't loaded.

**Comment by PuerkitoBio** [comment]
Looks like you're using an outdated version, did you try to run `go get -u
github.com/PuerkitoBio/goquery`? The cascadia author did fix the import
paths for the new golang.org/x/ thing a while ago.

**Comment by liwp-stephen** [comment]
Thanks for your help.
I use vpn to get the code, it seems the vpn's problem.

**Comment by necramongher** [comment]
thanks very much!

**Comment by jennyiya** [comment]
I met the same issue as well, hope for a solution ASAP!!!
