### ISSUE TITLE
Unable to filter using .Not("script") and .Not("style")

### ISSUE THREAD

**Issue by radiofreejohn** [PuerkitoBio/goquery#66]
I may be doing something wrong, but I assumed this would work as it was. I can do doc.Find("script") and doc.Find("style") and get the right elements, but .Not doesn't seem to filter them out, if for example I do doc.Find("head").Not("script") then the script node is still there.

**Comment by PuerkitoBio** [comment]
Hey John,

I think the error is that you assume that `Not` will filter children nodes. It doesn't, it filters out nodes in the matching set, so if you do doc.Find("head"), then the set of matching nodes is very likely only a "head" element (so there are no "script" elements to remove).

`Not` is useful, for example, if you want all `div`s that don't have the `foo` class, then you can do doc.Find("div").Not(".foo").

Martin

**Comment by radiofreejohn** [comment]
Hey Martin, you're right, I had assumed that Not would apply recursively, sorry about that, and thanks for clearing this up!
