### ISSUE TITLE
http.DefaultTransport and http.DefaultClient are not available in App Engine

### ISSUE THREAD

**Issue by alfredvaa** [PuerkitoBio/goquery#71]
When trying to use this library with App Engine I get this error:

http.DefaultTransport and http.DefaultClient are not available in Google App Engine

Is there a way to use the urlfetch method in App Engine instead, or could it be added?

Regards
Alfred

**Comment by PuerkitoBio** [comment]
Thanks for letting me know about this, I'm not familiar with App Engine, but the `NewDocument` is just one of the ways to get a goquery document, you can use `NewDocumentFromResponse` and use a custom-configured http client to get that response first (whatever App Engine allows you to use to fetch an URL). There is also `NewDocumentFromReader`.

I wouldn't want to add a dependency to an AppEngine specific package, but I believe you can get around that limitation with the existing NewDocument* variants.

**Comment by alfredvaa** [comment]
Ah, thanks!

I did solve it with one of the other NewDocument functions, like below:
	
    c := appengine.NewContext(r)
	client := urlfetch.Client(c)
	resp, _ := client.Get(uri)
	doc, _ := goquery.NewDocumentFromResponse(resp)
