### ISSUE TITLE
Fail to parse framework specific tags

### ISSUE THREAD

**Issue by klrkdekira** [PuerkitoBio/goquery#75]
```html
<script type="text/html" id="international-result-template">
<td><%= item.deliveryService %></td>
<td><%= item.zone %></td>
</script>
```
Trying to parse document containing the above gives error `invalid URL escape "%= "`

I think whatever inside script should be ignored and treated as text.

**Comment by PuerkitoBio** [comment]
This is not valid html, goquery processes html using the net/html parser.
