### ISSUE TITLE
Prematurely terminate iteration

### ISSUE THREAD

**Issue by csaunders** [PuerkitoBio/goquery#76]
This would probably require breaking the API, but you could do it in a way similar to how BoltDB handles transactions, by returning an error. Or the way jQuery handles it, by explicitly returning `false`.

For now the work around is something like:

```go
done := false
selection.Each(func(i int, s *goquery.Selection){
  if done {
    return
  }
  done := performComputations(s)
})
```

**Comment by PuerkitoBio** [comment]
See EachWithBreak.
