### ISSUE TITLE
How to close connection?

### ISSUE THREAD

**Issue by yurgon** [PuerkitoBio/goquery#77]
Hi

I have error like

too many open files
exit status 1

**Comment by PuerkitoBio** [comment]
Goquery doesn't directly use file descriptors. It could be because you made too many concurrent requests, or did not properly close request bodies. In any case, if you're on a *nix you can use lsof to see open FDs and the parent process, and ulimit to see the configured limits.

**Comment by yurgon** [comment]
Thanks its helps
But I has another erroк)

dial tcp 144.76.243.190:80: i/o timeout
