### ISSUE TITLE
Video Tag Support

### ISSUE THREAD

**Issue by souzadevinicius** [PuerkitoBio/goquery#78]
Hello guys, I'm using goquery to list all the elements with video tag, but it doesn't return any results.

**Comment by wfreeman** [comment]
How are you doing this?

**Comment by souzadevinicius** [comment]
a little piece of my code:
```go
url := "http://foo.bar"
doc, err = goquery.NewDocument(url)
doc.Find("video").Each(func(i int, s *goquery.Selection) {
//make something inside the loop
}
```

**Comment by wfreeman** [comment]
Are you checking that err?

**Comment by wfreeman** [comment]
Anyway, your code works for me for a document I created, so it's not that video tags aren't supported.

**Comment by PuerkitoBio** [comment]
Did you find out what the issue was, @souzadevinicius ? Been a few days, so I'll close, feel free to open a new one with new information if you're still having issues.
