### ISSUE TITLE
Unable te extract page title and meta description tags for certain page

### ISSUE THREAD

**Issue by rogierlommers** [PuerkitoBio/goquery#79]
I'm using GoQuery for extracting two specific fields out of saved pages: the page title (`<head><title>this text</title>`) and the meta tag `description`. My code mostly works, but for [this site](http://tweakers.net/nieuws/103412/ontwikkelaar-schrijft-software-voor-opvragen-sites-via-tor-in-php.html) it doesn't. And I can't figure out why it isn't working. It gives me the following values:

*title* --> "`Tweakers`", but I would expect "`Ontwikkelaar schrijft software voor opvragen sites via Tor in php - update - IT Pro - Nieuws - Tweakers`"
*description* --> `nil`, but I would expect: "`Een softwareontwikkelaar heeft een onlinedienst in elkaar gezet waarmee websites via het Tor-netwerk kunnen worden bezocht. TORelay, zoals de software heet, is geschreven in het php-micro-framework Lumen.`"

My code is as follows. Can someone please help me improving my code so it's more stable and works on 100% of the use cases?

	doc, err := goquery.NewDocument("the above mentioned url")
	if err != nil {
		glog.Error("error scraping article with id %d -- > ", storedArticle.ID, err)
	}

	// start scraping page title
	doc.Find("head").Each(func(i int, s *goquery.Selection) {
		pageTitle := s.Find("title").Text()
		storedArticle.Name = sql.NullString{String: strings.TrimSpace(pageTitle), Valid: true}
	})

	// now get meta description field
	doc.Find("meta").Each(func(i int, s *goquery.Selection) {
		if name, _ := s.Attr("name"); strings.EqualFold(name, "description") {
			description, _ := s.Attr("content")
			storedArticle.Description = sql.NullString{String: strings.TrimSpace(description), Valid: true}
		}
	})

**Comment by siriustnt** [comment]
Running this gives me the correct title and description.

	package main

	import (
		"fmt"
		"strings"

		"github.com/PuerkitoBio/goquery"
	)

	func main() {
		doc, err := goquery.NewDocument("http://tweakers.net/nieuws/103412/ontwikkelaar-schrijft-software-voor-opvragen-sites-via-tor-in-php.html")
		if err != nil {
			panic("bla")
		}

		// start scraping page title
		doc.Find("head").Each(func(i int, s *goquery.Selection) {
			pageTitle := s.Find("title").Text()
			fmt.Println(pageTitle)
		})

		// now get meta description field
		doc.Find("meta").Each(func(i int, s *goquery.Selection) {
			if name, _ := s.Attr("name"); strings.EqualFold(name, "description") {
				description, _ := s.Attr("content")
				fmt.Println(description)
			}
		})
	}

PS: Nice to have someone else from belgium using go :)

**Comment by mantyr** [comment]
You get a different page content in the following cases:
1. request a page through your browser
2. request a page through net/nttp
In the second case, that would achieve the same response should be:
1. The use cookies
2. to take into account input name, if the page obtained by submitting the form
3. use the correct referrer
4. use the correct agent-browser

wget 'http://tweakers.net/nieuws/103412/ontwikkelaar-schrijft-software-voor-opvragen-sites-via-tor-in-php.html' see:
```
<h1>Cookies op Tweakers</h1>
<p>Tweakers is wettelijk verplicht om je toestemming te vragen voor het gebruik van cookies en soortgelijke technieken, en je te informeren over het gebruik daarvan op de site.<A0></p>
```
And in Browser source code page see:
```
<meta itemprop="name" content="Tweakers">
<meta itemprop="url" content="http://tweakers.net/">
<meta itemprop="logo" content="http://tweakers.net/logo.png">
```

**Comment by rogierlommers** [comment]
Sorry, you're right.. it that damn "[cookie-law](http://www.cookielaw.org/blog/2014/12/19/dutch-cookie-law-fine-is-largest-so-far/)", here in the Netherlands. Thanks for your help; this issue can be closed.
