### ISSUE TITLE
Can't install using go get

### ISSUE THREAD

**Issue by let4be** [PuerkitoBio/goquery#81]
go get github.com/PuerkitoBio/goquery
package code.google.com/p/cascadia: unable to detect version control system for code.google.com/ path

**Comment by PuerkitoBio** [comment]
You probably have an old commit of goquery, it has switched to the github-hosted version of cascadia since the announce of the closing of code.google.com.

Try running `go get -u github.com/PuerkitoBio/goquery`, or removing the goquery directory and reinstalling.
