### ISSUE TITLE
golang.org/x/net/html

### ISSUE THREAD

**Issue by bigpyer** [PuerkitoBio/goquery#83]
the module golang.org/x/net/html has moved to github.com/golang/net,go get didn't work.

**Comment by PuerkitoBio** [comment]
No, the github repo is just a mirror (see the package comment in doc.go: `package html // import "golang.org/x/net/html"`, the golang.org repo is the canonical one). There may have been a temporary issue with the redirect or something, I just installed it to a fresh $GOPATH without problem.

**Comment by bigpyer** [comment]
It's caused by GFW..,thx!!
