### ISSUE TITLE
Get tag <℅

### ISSUE THREAD

**Issue by tommoholmes** [PuerkitoBio/goquery#87]
Hai.. I want to get some data
But I see, they use <℅
How to get <℅

**Comment by PuerkitoBio** [comment]
Hello,

Looks like what you are parsing is some templating language, not valid html. Goquery uses the net/html parser and the cascadia CSS-style selector, so it handles only html. It is possible that this input can be parsed correctly into the html nodes, but it will probably be very hard to query it with a selector as it may not have an element name, classes or other well-formed attributes.

For future reference, I would suggest reading through this on how to ask good questions: https://github.com/golang/go/wiki/HowToAsk, that would help people help you better.

Martin
