### ISSUE TITLE
User-Agent

### ISSUE THREAD

**Issue by raichu** [PuerkitoBio/goquery#9]
Can we a way of configuring the user-agent?
I'm getting problems recently because of it :(

**Comment by lucumt** [comment]
@mna Sometimes gocrawl do not meet our requirements and we need to use goquery to parse and fetch data,if we use goquery to frequently,it may be blocked by the website,so user-agent configuration is necessary.
Do you have any plan to implement it?

**Comment by greedmonkey** [comment]
@raichu 
hello,
Maybe this code can help you.
`req, _ := http.NewRequest("GET", link, nil)
		req.Header.Add("Content-Type", "application/x-www-form-urlencoded")
		req.Header.Add("user-agent", "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36")
		if resp, err := http.DefaultClient.Do(req); err == nil {
			if doc, err := goquery.NewDocumentFromResponse(resp); err == nil {
				
				})
			}
		}`
