### ISSUE TITLE
Best way to check for "contains" by string?

### ISSUE THREAD

**Issue by jordan-wright** [PuerkitoBio/goquery#92]
Awesome library - thanks for all the hard work!

Quick question - I'm trying to make a check to see if my DOM has a certain selector by string (e.g. "h1"). I know we can ```Find()``` via a selector string, but checking to see if the result is nil doesn't seem to work. The same issues are had via ```Has```, etc.

My current method is to ```Find("h1").Length() == 0```, but I just wanted to check - is there a cleaner way to see if a document has a certain selector via string?

**Comment by PuerkitoBio** [comment]
Hi Jordan,

Yeah, using `Length` (or `Size`) is the correct way, methods that return a `Selector` never return nil (to support the chaining interface) but may return an empty selector.

Martin

**Comment by jordan-wright** [comment]
Excellent, glad to hear I wasn't just missing something :smile:.

Thanks!
