### ISSUE TITLE
link with javascript

### ISSUE THREAD

**Issue by oikomi** [PuerkitoBio/goquery#94]
hi @PuerkitoBio 

I want to parse "page4.html"  from the following code, goquery can do this ?

```javascript

 <li><a href='javascript:location.href="page4.html"'>page 4</a></li>  
```

**Comment by PuerkitoBio** [comment]
You have to get the href attribute, goquery won't help you parse the inner value of the attribute (the `javascript:location:...` part, you're on your own for this one). So you can do something like `doc.Find("a").Attr("href")`.

**Comment by oikomi** [comment]
Hmm, you are right. So do you have any good suggestion to deal with this situation, maybe your crawler need to deal with it? thank you!

**Comment by PuerkitoBio** [comment]
From the html parser's point of view, this string is just the value of the `href` attribute, it doesn't know nor care about the content of attributes. You can summon regexp to the rescue, though, or `strings.SplitN(hrefValue, "=", 2)` depending on what you expect to find as possible values. At the other end of the spectrum, I guess you would have to detect that it starts with "javascript:" and then use a full-blown javascript parser for the rest of the value.
