### ISSUE TITLE
Inbuilt setText?

### ISSUE THREAD

**Issue by chrisflatley** [PuerkitoBio/goquery#95]
I see there's a Text() and ReplaceWithHtml() function but its there a setText equivalent? I couldn't see it.

Something like (apologies... just started using this today) : 

````
func (s *Selection) SetText(s *goquery.Selection, text string) *goquery.Selection {
	for _, n := range s.Nodes {
		s.ReplaceWithHtml(fmt.Sprintf("<%s>%s</%s>", n.Data, text, n.Data))
	}
	return s
}
````

**Comment by PuerkitoBio** [comment]
Hello Chris,

No, there is no `SetText()` available at the moment. Mutation functions have been added on an as-needed basis by collaborators, as typically with a static "DOM" there is little interest in modifying the document. I'm open to merge such a PR, but it would have to mimic pretty closely what jQuery does for the same action, and have good test coverage (I prefer to mention this upfront in case you're interested in sending one, but no obligation at all obviously).

Thanks,
Martin

**Comment by chrisflatley** [comment]
Sorry, I completely forgot about this. We've moved from Go for this project. Obviously this can remain closed, but here's another function we found useful just for others:

~~~~
// Add html to the selection and then get the html we added as a selection
func selectionAppendAndGet(s *goquery.Selection, html string) *goquery.Selection {
	// TODO: This seems very hard way of doing it.  We basically diff the children
	nodes := parseHTML(html)
	oldChildren := s.Children()
	s.AppendNodes(nodes...)
	return s.Children().NotSelection(oldChildren)
}
~~~~

We also needed to parseHTML(h string) from https://github.com/PuerkitoBio/goquery/blob/master/manipulation.go as a useful utility. Perhaps it should be public.

**Comment by PuerkitoBio** [comment]
Hey Chris,

No worries, thanks for the feedback. parseHtml doesn't really add any value to the html package's ParseFragment function, so there's no real incentive to export it.

Martin
