### ISSUE TITLE
Error when go-getting the package

### ISSUE THREAD

**Issue by linghutf** [PuerkitoBio/goquery#97]
When I'm get the goquery,fatal error:<br/>
annot find package "golang.org/x/net/html" in any of<br/>
the new site may change to [https://godoc.org/golang.org/x/net/html]

**Comment by PuerkitoBio** [comment]
Hello,

I changed the title to better match the error you're getting (I'm not stopping the library :). You may be hitting a temporary network error or a proxy error of some sort, `go get` is working fine for me and the net/html package path that you mention is the right one.

You can try running `go get -v` to get more details, and post the results here if the problem persists.

- Martin

**Comment by linghutf** [comment]
I tried it again,and success via vpn
sorry!

**Comment by PuerkitoBio** [comment]
No worries, have fun!
