### ISSUE TITLE
div inside h3

### ISSUE THREAD

**Issue by marshauf** [PuerkitoBio/goquery#99]
Hi,

I got the following html text:
``html
<a>
 <img/>
 <h3>
  Title
  <div>
   <a>
   <span></span>
   </a>
  </div>
 </h3>
</a>
``

The img is a child of a but not the h3. I know a div in a h3 is not allowed. How can I get the h3 node anyway?

Edit:
rendering all a.Nodes also omits the h3 node and it's content.

**Comment by PuerkitoBio** [comment]
Seems like doing `doc.Find("h3")` works, although it does seem like the HTML parser makes some automated corrections. Render the `h3.Html()` gives me `<a> Title </a><div><a> </a><a> <span></span> </a> </div>`.

**Comment by marshauf** [comment]
This is the code I experimented with: https://gist.github.com/marshauf/2ac1f5b8720385d448ef
I am probably not considering something and that's why the one line works and the other doesn't
